### ISSUE TITLE
New-AzureRmRecoveryServicesAsrReplicationProtectedItem does not work with managed disk

### ISSUE THREAD

**Issue by CICDSimplified** [MicrosoftDocs/azure-docs-powershell#1003]
When used the command, i am getting the error, "Cannot validate argument on parameter 'AzureToAzureDiskReplicationConfiguration'. The argument is null or 
empty. Provide an argument that is not null or empty, and then try the command again." But when i run the command New-AzureRmRecoveryServicesAsrAzureToAzureDiskReplicationConfig, i get the output as 
VhdUri                         : 
LogStorageAccountId            : /subscriptions//resourceGroups/eyinexus/providers/Microsoft.Storage/storageAccounts/eyinexussta
RecoveryAzureStorageAccountId  : 
IsManagedDisk                  : True
DiskId                         : /subscriptions//resourceGroups/eyinexus/providers/Microsoft.Compute/disks/linuxvm_disk1_3ce1954ac267
                                 4492aa673698bf3972f9
RecoveryReplicaDiskAccountType : Premium_LRS
RecoveryResourceGroupId        : /subscriptions//resourceGroups/eyRinexus
RecoveryTargetDiskAccountType  : Premium_LRS

The vhduri is empty in the above object, what should i do ?

**Comment by sptramer** [comment]
This would be a product bug. Please file an issue with the engineering team: https://github.com/azure/azure-powershell/issues
