### ISSUE TITLE
M36125: Ambiguity: "Added Sql server in Azure VM support"

### ISSUE THREAD

**Issue by v-makoud** [MicrosoftDocs/azure-docs-powershell#1004]
Hello @huypub,
Translator has reported possible source content issue.
Link to Github file: https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.5.0/release-notes-azureps.md
Row where the issue is located: 26
Comment: Translator wants to know the exact meaning of this string: "Added Sql server in Azure VM support". Will support be offered for SQL Server or will SQL Server be supported by Azure VM?

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by sptramer** [comment]
@markcowl Can you please provide an update to the release notes which resolves this localization ambiguity? (cc @v-makoud)

**Comment by sptramer** [comment]
@markcowl - Ping, please update the release notes content to remove ambiguity

**Comment by sptramer** [comment]
@dcaro - Do you have any information on how the release notes can be updated to address the ambiguity?

**Comment by v-maudel** [comment]
#please-close

**Comment by v-maudel** [comment]
This is an old request and the file doesn't exist anymore in repo

**Comment by srvbpigh** [comment]
Hello, @v-makoud
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @v-makoud
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by dcaro** [comment]
The release notes are build based on the comments from the PRs, the meaning of this log entry is that the recovery services operations for SQL databases in Azure VM supported. https://docs.microsoft.com/en-us/azure/backup/backup-sql-server-database-azure-vms  
This issues can be closed.

**Comment by Mike-Ubezzi-MSFT** [comment]
#please-close
