### ISSUE TITLE
Uninstall-AzureRm work only after installation of the latest Azure for PowerShell and .Net Framework 4.7.2

### ISSUE THREAD

**Issue by cafenroy** [MicrosoftDocs/azure-docs-powershell#1009]
This finally worked:
- Install the latest Azure For Power shell
- When I run Connect-AzAccount, it did not work. (I had to upgrade the .net Framework to version 4.7.2 )
- After installing .net Framework 4.7.2 the Connect-AzAccount worked.
- Then I where able to run Uninstall-AzureRm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e330eac7-fb4f-b6f7-b141-ca1e075cd001
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.6.0#feedback)
* Content Source: [docs-conceptual/azps-1.6.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.6.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
.NET 4.7.2 is listed as an installation requirement when using PowerShell 5, so closing this comment.
