### ISSUE TITLE
Azure CLI

### ISSUE THREAD

**Issue by jordanchang** [MicrosoftDocs/azure-docs-powershell#1013]
What does this mean for the future of Azure CLI? Is Azure CLI now obsolete and we should shift to Powershell Azure Az?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 894a6c45-b019-ca28-ba22-8725559f4d30
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.6.0)
* Content Source: [docs-conceptual/azps-1.6.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.6.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The Azure CLI is a separate product and will continue to be maintained. It's not going anywhere, and will continue to be updated with new features.

This update is a replacement for the previous Azure PowerShell module only, and isn't a replacement for the CLI. But if you're a user familiar with PowerShell and on a UNIX-like system, PowerShell 6.x, and the Azure PowerShell modules, will run on your environment now.
