### ISSUE TITLE
Connect-AzAccount : Invalid provider type specified.

### ISSUE THREAD

**Issue by nnamedieh** [MicrosoftDocs/azure-docs-powershell#1018]
Hi all,

unfortunately I'm not able to connect to Azure with service principal using certificate with the following command:

Connect-AzAccount -ServicePrincipal -TenantId $tenantId -CertificateThumbprint "d655e2ba5e887028f3b4fe28b4aa2268492864db" -ApplicationId "3b288c07-a867-4dea-aabd-3c68d7e5125a"

I get the following error message: 
"Connect-AzAccount : Invalid provider type specified."

AzureRM module gives me the same error message. I'm using the latest Az.Accounts Module (1.4.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92cb0e4-67cb-4136-d487-21aeb1cade43
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.6.0)
* Content Source: [docs-conceptual/azps-1.6.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.6.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@nnamedieh Please make sure that you've followed all of [the instructions](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-1.6.0#certificate-based-authentication) for signing in with a service principal, including storing the certificate information in a local certificate store.

There should also be much more information contained in the error message, which will be needed to diagnose the issues if this is a product bug.

**Comment by nnamedieh** [comment]
Hi @sptramer ,

thanks for your reply. I'll test this again and would contact you, when it's not working.

**Comment by sptramer** [comment]
@nnamedieh Is it safe to close this issue, or are you still encountering problems?

**Comment by nnamedieh** [comment]
Hi @sptramer yes, it's working like a charm. Thanks for your interest in this case. You can close it.

**Comment by Adikota** [comment]
@nnamedieh Hello, How did you get this working? I am running into an "Connect-AzAccount : Invalid provider type specified." error

**Comment by nnamedieh** [comment]
Hi @Adikota ,
actually I do not exactly know what was the right solution for me. What version of Az Module do you use? Can you copy the code you are using? 

Do you use a registered app or a service principal for login? Take a look [here](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-2.7.0#certificate-based-authentication) to choose the correct Login-method.

**Comment by m00nd** [comment]
Hi,
I am facing the same issue.Can you please help me?

**Comment by tasgray** [comment]
I recently had this issue and the fix is really simple. I posted it on my blog - https://tasgray.com/connect-azaccount-invalid-provider-type-specified/

**Comment by BharathNimmala-MSFT** [comment]
Thank you @tasgray for sharing the blog. 

@Adikota , @nnamedieh , @m00nd - Thanks for reaching out, requesting you to please look through the blog provided by @tasgray and see if its fixing the issue. However if you have any further queries or the issue still exists for you please feel free to tag us in your reply. Will be more than happy to reopen this thread and continue the conversation. Thank you.

**Comment by ig-tr** [comment]
> https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1018#issuecomment-570036886

I had issue in connect with Connect-ExchangeOnline
i had error:
`Error connection in Exchange Online: Invalid provider type specified. .
`
i use your way. and it work for me. thnks

**Comment by GrizzInt** [comment]
@tasgray 's blog no longer loads but his solution worked for me.  It seems Connect-AZAccount doesn't like certs without a Microsoft provider string.  I was able to find a copy of his blog on archive.org: 
https://web.archive.org/web/20230129222058/https://tasgray.com/connect-azaccount-invalid-provider-type-specified/

Here's a copy paste of his solution that worked for me: 

> Connect-AzAccount : Invalid provider type specified.
> 
> Creating a service principal in Azure AD and using certificate based authentication is a common practice when building automation scripts in PowerShell. 
> 
> If you’ve landed on this blog post there’s a very good chance that you’ve followed the [steps provided by Microsoft] and been unsuccessful. Not to worry, the fix is actually quite simple.
> 
> To ensure that your certificate based authentication works, you’ll need to add the -Provider parameter to New-SelfSignedCertificate PowerShell cmdlet with the value “Microsoft Enhanced RSA and AES Cryptographic Provider”. For example –
> 
> `New-SelfSignedCertificate -dnsname some.domain.com -CertStoreLocation cert:\LocalMachine\My -Provider “Microsoft Enhanced RSA and AES Cryptographic Provider”`
> 
> Now when you export the certificate and import to your Azure Service Principal you should be able to successfully connect using Connect-AzAccount. Eg,
> 
>` Connect-AzAccount -ServicePrincipal -TenantId $TenantId -ApplicationId $AppId -CertificateThumbprint $CertThumb`

**Comment by quintencls** [comment]
I ran into the same 'Invalid provider type specified' error because the user running the script didn’t have read access to the private key in certlm. Once I fixed the access, the error went away.
