### ISSUE TITLE
Could not authenticate with tenant

### ISSUE THREAD

**Issue by kasunsjc** [MicrosoftDocs/azure-docs-powershell#1027]
I authenticate Azure PowerShell using Connect-AzAccount but after device login, when I try to execute commands it says  could not authenticate with tenant.

OS - MacOS 10.14.4
Az PowerShell - 1.7.0  

I tried with verbose and debug mode both says successfully sign in. Following is the verbose & debug output 

Verbose 

`{I ♥ PS} /Users/kasunrajapakse&gt; Connect-AzAccount -Verbose
VERBOSE: Performing the operation "log in" on target "User account in environment 'AzureCloud'".
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HV2KX9JPB to authenticate.
                                                                                       
{[AzureGermanCloud, AzureGermanCloud], [AzureUSGovernment, AzureUSGovernment], [AzureCloud, AzureCloud...

{I ♥ PS} /Users/kasunrajapakse&gt; Get-AzSubscription        
WARNING: Unable to acquire token for tenant 'Common'
Get-AzSubscription : Could not authenticate with tenant . Please ensure that your account has access to this tenant and log in with Connect-AzAccount
At line:1 char:1
+ Get-AzSubscription
+ ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzSubscription], PSArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand`
 
Debug Output

`{I ♥ PS} /Users/kasunrajapakse&gt; Connect-AzAccount -Debug         
DEBUG: 21:02:01 - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 21:02:06 - using account id '&lt;email&gt;@hotmail.com'...

Confirm
Are you sure you want to perform this action?
Performing the operation "log in" on target "User account in environment 'AzureCloud'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 21:02:11 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 21:02:11 - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 21:02:11 - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-00000000', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-00000000', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HULAF79NY to authenticate.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 00000000-6d90-4328-8880-00000000
Accept-Language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 11998
x-ms-request-id               : 00000000-b156-4476-a010-00000000
x-ms-correlation-request-id   : 00000000-b156-4476-a010-00000000
x-ms-routing-request-id       : SOUTHEASTASIA:20190412T153310Z:00000000-b156-4476-a010-00000000
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 12 Apr 2019 15:33:10 GMT

Body:
{
  "value": [
    {
      "id": "/tenants/00000000-9f40-470d-b4e0-00000000",
      "tenantId": "00000000-9f40-470d-b4e0-00000000"
    },
    {
      "id": "/tenants/00000000-d116-49ea-bcdb-00000000",
      "tenantId": "00000000-d116-49ea-bcdb-00000000"
    },
    {
      "id": "/tenants/00000000-342e-4d74-825e-00000000",
      "tenantId": "00000000-342e-4d74-825e-00000000"
    },
    {
      "id": "/tenants/00000000-b5ac-44c3-961b-00000000",
      "tenantId": "00000000-b5ac-44c3-961b-00000000"
    },
    {
      "id": "/tenants/00000000-4a52-403b-8a2e-00000000",
      "tenantId": "00000000-4a52-403b-8a2e-00000000"
    }
  ]
}

DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '00000000-9f40-470d-b4e0-83b6a36e591e', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/00000000-9f40-470d-b4e0-83b6a36e591e/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '00000000-9f40-470d-b4e0-83b6a36e591e', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'ea567613-d116-49ea-bcdb-3030108e001c', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/00000000-d116-49ea-bcdb-3030108e001c/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '00000000-d116-49ea-bcdb-3030108e001c', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '00000000-342e-4d74-825e-c50a669d5bba', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/0e15146b-342e-4d74-825e-c50a669d5bba/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '00000000-342e-4d74-825e-c50a669d5bba', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '00000000-b5ac-44c3-961b-4ce74413ce87', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/00000000-b5ac-44c3-961b-4ce74413ce87/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '00000000-b5ac-44c3-961b-4ce74413ce87', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '00000000-4a52-403b-8a2e-e97c111417fb', Endpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/00000000-4a52-403b-8a2e-e97c111417fb/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '00000000-4a52-403b-8a2e-e97c111417fb', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob

DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - True; Duration - 00:01:13.3503918; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 21:03:16 - ConnectAzureRmAccountCommand end processing.
DEBUG: 21:03:16 - ConnectAzureRmAccountCommand end processing.
Environments
------------                                                                                             
{[AzureGermanCloud, AzureGermanCloud], [AzureUSGovernment, AzureUSGovernment], [AzureCloud, AzureCloud...`

  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b833d-aff2-3d27-6277-dfb5b098e0c1
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.7.0#feedback)
* Content Source: [docs-conceptual/azps-1.7.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.7.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@kasunsjc If your tenant is in an environment with its own data restrictions, such as Germany or China, you must also use the `-Environment` flag. See the documentation for [Connect-AzAccount](https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-1.8.0) for examples and also the [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-1.8.0) article.

If you continue to encounter problems, please either [file a support request](https://azure.microsoft.com/en-us/support/create-ticket/) or [a product bug](https://github.com/azure/azure-powershell/issues).
