### ISSUE TITLE
Missing breaking changes description for New-AzureRmADGroup in Az module

### ISSUE THREAD

**Issue by borys86** [MicrosoftDocs/azure-docs-powershell#1028]
hi there. I was trying to migrate existing scripts. One issue I have encountered is the migration of New-AzureADGroup to New-AzADGroup.
1. it does not allow to set  -Description if we use **New-AzADGroup**
2. after running Enable-AzureRMAlias it says that:
"New-AzADGroup : A parameter cannot be found that matches parameter name 'Description'."

Please advise on how we suppose to replace existing New-AzureRmADGroup with  New-AzADGroup. We need, very much to set description. Does this mean that we need to roll back into using AzureRM package? How to know when such missing property support will be implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ab9cb7-b334-1f3b-16d2-8c90e404847c
* Version Independent ID: 18cf0a41-ce42-1583-6511-6d28c1635d23
* Content: [Breaking changes for Microsoft Azure PowerShell 6.0.0](https://docs.microsoft.com/en-us/powershell/azure/azurerm/migration-guide.6.0.0?view=azurermps-6.13.0#breaking-changes-to-azurermresources-cmdlets)
* Content Source: [docs-conceptual/azurermps-6.13.0/migration-guide.6.0.0.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/migration-guide.6.0.0.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@borys86 You are looking at the wrong migration document - the correct one is [Migration Guide for Az 1.0.0](https://docs.microsoft.com/en-us/powershell/azure/migrate-az-1.0.0?view=azps-1.8.0). If this document doesn't contain the correct information please leave another comment.

**Comment by sptramer** [comment]
Closing due to lack of response on `help-wanted` in over 30 days.
