### ISSUE TITLE
After following instructions, az comdlet not found

### ISSUE THREAD

**Issue by joshmouch** [MicrosoftDocs/azure-docs-powershell#1029]
I followed these instructions to the letter on both the Powershell that comes with windows and the newer Powershell Core. In both cases when I type in "az" afterward, I get:

`The term 'az' is not recognized as the name of a cmdlet...`

I'm assuming there's a PATH variable that is not being installed by the install script.

UPDATE: I tried manually adding the path and also manually importing the module, but no luck:
```
PS C:\WINDOWS\system32> Import-Module Az -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Az\1.7.0\Az.psd1'.
PS C:\WINDOWS\system32> Az
Az : The term 'Az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Az
+ ~~
    + CategoryInfo          : ObjectNotFound: (Az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>

```

**Comment by sptramer** [comment]
That's correct, because `Az` is not a cmdlet name. The set of commands that come in the `Az` module are what allow you to interact with Azure. See the [complete cmdlet reference](https://docs.microsoft.com/en-us/powershell/module/?term=Az.)
