### ISSUE TITLE
The "Download PDF" feature yields a "404 - Page not found" error

### ISSUE THREAD

**Issue by AzureMentor** [MicrosoftDocs/azure-docs-powershell#1030]
Just wanted to inform the Azure PowerShell team and the Microsoft Docs team that the **Download PDF** feature on the bottom left corner of https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-1.7.0 is yielding a "**404 - Page not found**" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44e490-bfce-8a78-629b-a8886af52f64
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-1.7.0#feedback)
* Content Source: [docs-conceptual/azps-1.7.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.7.0/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@SyntaxC4 This looks like it might be an OPS issue, the PDF settings in the repo are correct.

**Comment by sptramer** [comment]
@AzureMentor It looks like PDF builds are now working again.
