### ISSUE TITLE
Wrong command specified

### ISSUE THREAD

**Issue by kaareschmidtalso** [MicrosoftDocs/azure-docs-powershell#1034]
It's Remove-AzRoleAssignment - not Delete-AzRoleAssingment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad7cd03-a502-9eb0-26da-233d10b2a418
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.7.0)
* Content Source: [docs-conceptual/azps-1.7.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.7.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Will be fixed at the next site publish.
