### ISSUE TITLE
Instructions for Azure Classic, Not AzureRM

### ISSUE THREAD

**Issue by jayallenmsft** [MicrosoftDocs/azure-docs-powershell#1037]
You're now recommending we use the AzureRM module, but these instructions are for Azure Classic. Given that this is the first search result for this topic in Google, these instructions should be updated for AzureRM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad7cd03-a502-9eb0-26da-233d10b2a418
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.7.0#)
* Content Source: [docs-conceptual/azps-1.7.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.7.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by jayallenmsft** [comment]
Hm, okay, I did find the correct documentation: 

https://docs.microsoft.com/en-us/powershell/azure/azurerm/create-azure-service-principal-azureps?view=azurermps-6.13.0

So maybe it would be better in the old Azure PowerShell docs to include links to the new AzureRM module? As someone using Azure PowerShell for the first time, I found the fact that there are two separate sets of PS commands/modules really confusing. Consider having each topic call out at the top that it is the documentation for Azure PowerShell Classic, and have links to the corresponding AzureRM PowerShell docs.

**Comment by sptramer** [comment]
Documentation already makes it clear that the new "Az" module is the preferred method for interacting with Azure, and the original page you link is the documentation for the Az module, which does not use the Classic deployment model. Please follow those instructions and use the Az module. See [Introducing the new PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.8.0).

**Comment by jayallenmsft** [comment]
Actually, the source of my confusion is between Azure PowerShell 1.8.0 and Azure RM PowerShell 6.13.0 - e.g.: https://docs.microsoft.com/en-us/powershell/azure/azurerm/create-azure-service-principal-azureps?view=azurermps-6.13.0

1.80. commands for creating an SP did not work at all on my machine, whereas I got everything to work fine with the Azure RM module. It's not clear to me why two separate packages exist and what the difference is. Would be good to have a clear description on how the two modules differ, and in which case one should use one over the other.
