### ISSUE TITLE
Unable to run the Az v_1.7.0 modules From Windows PowerShell 5.1

### ISSUE THREAD

**Issue by cloudsavara** [MicrosoftDocs/azure-docs-powershell#1039]

**Comment by cloudsavara** [comment]
![Az_Modules](https://user-images.githubusercontent.com/24710462/56442182-0bbb2d00-62f0-11e9-92db-f50d90d0fde6.JPG)
Followed this link: Install the Azure PowerShell module
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.7.0

PS C:\Users> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  1689   

PS C:\Users> Install-Module -Name Az -AllowClobber -RequiredVersion 1.7.0 -Force

PS C:\Users> Install-Module -Name Az -RequiredVersion 1.7.0 -Force

PS C:\Users> Update-Module -Name Az -RequiredVersion 1.7.0 -Force

PS C:\Users>Connect-AzAccount

PS C:\Users>New-AzStorageAccount -Name $storageAccountName -ResourceGroupName $resourceGroup -Type Standard_LRS -Location $location
Error:
New-AzStorageAccount : The 'New-AzStorageAccount' command was found in the module 'Az.Storage', but the module could not be loaded. For more 
information, run 'Import-Module Az.Storage'.
At line:1 char:1
+ New-AzStorageAccount -Name $storageAccountName -ResourceGroupName $re ...
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzStorageAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

Followed this link: Potential Reason 1: Older Version Stored in User or Global Scope
https://github.com/Azure/azure-powershell/blob/master/documentation/troubleshoot-module-load.md#potential-reason-1-older-version-stored-in-user-or-global-scope

**Comment by sptramer** [comment]
@cloudsavara I need some more information:

* Please show the error message that comes from running `Import-Module Az.Storage`
* Which version of .NET Framework or .NET Core is installed
* The results of `Get-InstalledModule -Name Az.Storage -AllVersions`

**Comment by sptramer** [comment]
Requested information not provided in over 30 days, closing as inactive.
