### ISSUE TITLE
DHCP address for RecoveryNIC

### ISSUE THREAD

**Issue by diegopietruszka** [MicrosoftDocs/azure-docs-powershell#1040]
I was not able to assign DHCP or dynamic address as the target IP on the recovery network interface. It is a simple task using the portal, but don't seems to be a way to do it using powershell.
Am I missing something or is this feature still don't available?

**Comment by sptramer** [comment]
@rayne-wiselman - Do you have any information from a docs perspective that might help here?

@markcowl - Is this currently possible within the recovery/networking cmdlets, or would it be a feature request?

**Comment by rayne-wiselman** [comment]
@diegopietruszka Hi, can you provide some context about which disaster recovery scenario you're setting up with Site Recovery, or the document that you're following. Thx!

**Comment by diegopietruszka** [comment]
@rayne-wiselman Hi, I created my own script based on this article https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-powershell
We have multiple environments in Azure West Europe Data Center (Each environment is a group of VMs belonging to a country), what the scrip does is basically create a recovery service vault for each of those environments, create a replication policy, add all the VMs as replicated items and create a recovery plan. All that using Azure North Europe Data Center as target.
Of course there are more details on the script but that is the idea.

On the target VNET we have multiple subnets (one per environment). When each VM is added as a Protected Item using “New-azurermrecoveryservicesASRReplicationProtectedItem”, Azure assigns as target subnet the first one in alphabetical order on the target VNET and an IP on it.
For that reason after the VMs are added, I change the target subnet and IP address using “Set-AzureRmRecoveryServicesAsrReplicationProtectedItem”. 
The problem about assigning a fix IP to a protected item on the target subnet is that Azure does not consider the assigned IP as “used”. Which means, if you manually create a NIC (for another VM) on the target subnet using the portal and leave the IP address as dynamic, there are big chances it will assign the one already assigned to the protected item. The same way if you test the IP assigned to the protected item using “Test-AzureRmPrivateIPAddressAvailability” it will come up as a none used IP.

For that reason and to prevent conflicts, the previously used command “Set-AzureRmRecoveryServicesAsrReplicationProtectedItem” should have a parameter to assign a dynamic IP address on the target subnet (which is not possible today).

**Comment by rayne-wiselman** [comment]
Can you take a look at this to see if it  helps - https://social.msdn.microsoft.com/Forums/en-US/85e57dd8-ee04-48d6-b54a-4e0d52fd3fb0/set-protected-vms-static-ip-address-using-powershell?forum=hypervrecovmgr

**Comment by diegopietruszka** [comment]
I saw that, but unfortunately does not help.
At one point they mention that you could assign a DHCP address, but there is no example on how to.

**Comment by rayne-wiselman** [comment]
I suggest asking this question over on the Site Recovery forum - https://social.msdn.microsoft.com/forums/azure/en-us/home?forum=hypervrecovmgr

**Comment by sptramer** [comment]
@diegopietruszka Going to close this issue since you've been directed to forums. If you think that there's documentation missing in the cmdlet itself, you can file a reference documentation issue with the engineering team: https://github.com/azure/azure-powershell/issues
