### ISSUE TITLE
Set-AzStorageServiceLoggingProperty failing with No credentials provided

### ISSUE THREAD

**Issue by lagase** [MicrosoftDocs/azure-docs-powershell#1044]
I am running in to an error when attempting to enable logging using Set-AzStorageServiceLoggingProperty for Tables in a Storage V2 Account. I was able to set the same logging for Blob and Queue with no issues.

The command I am using after running New-AzStorageContext is the following: 

Set-AzStorageServiceLoggingProperty -ServiceType Table -Context $storagectx -LoggingOperations "Read,Write,Delete" -RetentionDays 30

Error: Set-AzStorageServiceLoggingProperty : No credentials provided. At line:1 char:1 + Set-AzStorageServiceLoggingProperty -ServiceType Table -Context $stor ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Set-AzStorageServiceLoggingProperty], InvalidOperationException + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.SetAzureStorageServiceLoggingCommand

This seems like a bug to me but wanted to see if this is a known issue or if anyone has a potential workaround.

**Comment by lagase** [comment]
Can anyone take a look at this issue? This is blocking some production work in setting the proper logging operations for Tables in Azure

**Comment by sptramer** [comment]
Please file a bug with engineering: https://github.com/azure/azure-powershell/issues
