### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by LeeCoxMS** [MicrosoftDocs/azure-docs-powershell#1048]
https://aka.ms/azspshmigration170 lands on a 404 page...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149e500e-2dab-63cf-089c-92292073f589
* Version Independent ID: d16476ba-1834-ac38-1142-a36a4864bb29
* Content: [Overview of Azure Stack Admin PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-1.7.1#feedback)
* Content Source: [docs-conceptual/azurestackps-1.7.1/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-1.7.1/overview.md)
* Service: **azure-stack**
* GitHub Login: @sijuman
* Microsoft Alias: **sijuman**

**Comment by LeeCoxMS** [comment]
It should redirect here:
https://github.com/Azure/azure-powershell/blob/AzureRM/documentation/migration-guides/Stack/azurestack.1.7.1.md

**Comment by sptramer** [comment]
@sijuman This is an Azure Stack doc issue, please fix.

**Comment by sijuman** [comment]
@bganapa

**Comment by bganapa** [comment]
This is fixed

**Comment by bganapa** [comment]
I could not close, can some one close this issue as this got fixed
