### ISSUE TITLE
Set-AzureRmApiManagementPolicy Bad Error Message

### ISSUE THREAD

**Issue by backwardsDave1** [MicrosoftDocs/azure-docs-powershell#1050]
If you run Set-AzureRmApiManagementPolicy and your Policy string contains:

```
$policyString = '<policies>
    <inbound>
        <base />
        <rewrite-uri template="/stores/{Location}/slots?StartDate={StartDateTime}&amp;AppointmentType={AppointmentType}" />
        <set-header name="ocp-apim-subscription-key" exists-action="override">
            <value>12d0bdd57ca84fa9ad35f13f22605dbf</value>
        </set-header>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>'
```

If a parameter (in my example, Location) is not part of the template params in APIM, it will output the following:
> Operation returned an invalid status code 'BadRequest'

Please have the error be the same as what the Azure Portal shows you:

> One or more fields contain incorrect values: Error in element 'rewrite-uri' on line 4, column 10: Only parameters specified in the original URL template can be used in the rewrite template

**Comment by sptramer** [comment]
@backwardsDave1 This is a bugfix/feature request, please file a ticket with engineering: https://github.com/azure/azure-powershell/issues
