### ISSUE TITLE
Powershell - Not Responding when invoked "Get-AzDataLakeStoreChildItemSummary"

### ISSUE THREAD

**Issue by madhanan** [MicrosoftDocs/azure-docs-powershell#1056]
**Issue**
Issue with ```Get-AzDataLakeStoreChildItemSummary``` from module *Az.DatalakeStore* whereas *AzureRM* Module ```Get-AzureRMDatalakeStoreChildItemSummary```  is working perfectly 

**What i did to get the error**
Whenever i try from My Laptop PowerShell, Virtual Machine (newly installed/updated Az Modules), Cloud Shell -In all 3 places its failing the below code.

```powershell
Get-AzDataLakeStoreChildItemSummary -Account xyz.azuredatalakestore.net -Path /
```
Also i have tried

```powershell
Get-AzDataLakeStoreChildItemSummary -Account xyz -Path /
```

I get "Powershell Not Responding" error & Cloud Shell gets Terminated

![image](https://user-images.githubusercontent.com/19624958/57355882-af2f8d00-718c-11e9-85ad-56ad905017fa.png)

![image](https://user-images.githubusercontent.com/19624958/57357135-e2275000-718f-11e9-9592-b93cff522a87.png)

**Az.DatalakeStore Version** 1.2.0

![image](https://user-images.githubusercontent.com/19624958/57357706-2c5d0100-7191-11e9-99bf-aaf1732367ec.png)

[Get-AzDatalakeStoreChildItemSummary](https://github.com/Azure/azure-powershell/blob/master/src/DataLakeStore/DataLakeStore/help/Get-AzDataLakeStoreChildItemSummary.md "Link to Doc in GitHub")

Kindly requesting for anybody help, am i missing something ?

**Comment by sptramer** [comment]
@madhanan This looks like a product bug and you should file an issue with engineering: https://github.com/azure/azure-powershell/issues
