### ISSUE TITLE
Why is Az 1.8.0 not still available, since Az 2.0 is a new major release

### ISSUE THREAD

**Issue by markcowl** [MicrosoftDocs/azure-docs-powershell#1066]
The AzureRM docs kept around reference docs for the last major version, why aren't the docs for Az 1.8.0 still available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92305e5b-64e9-aabc-e934-f679d966cb6d
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-2.0.0)
* Content Source: [docs-conceptual/azps-2.0.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.0.0/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@markcowl It looks like this was an issue with the Az 2.0.0 release where the publisher followed the process for doing a minor release. I don't know what settings there are on the OPS side which might affect it, but there is a PR #1064 which should bring back the 1.8.0 version. You can see the changes on staging.
