### ISSUE TITLE
Document how to add additional Pay-As-You-Go subscriptions through PowerShell

### ISSUE THREAD

**Issue by jeking3** [MicrosoftDocs/azure-docs-powershell#1077]
I am setting up some automation to maintain multiple demonstration logins for a product and I want to keep each of the demo login resources isolated from the other ones.  To do this I need multiple subscriptions.  This page did not answer my use case - how can I create and delete subscriptions through PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5ffc28-cb7b-19fc-9f19-70f2e53d3459
* Version Independent ID: 98b7ac0d-e288-bb26-57b8-c173c46821d5
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/manage-subscriptions-azureps?view=azps-2.1.0#feedback)
* Content Source: [docs-conceptual/azps-2.1.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.1.0/manage-subscriptions-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by jeking3** [comment]
I did find this, and it sounds like what I am looking for:

https://docs.microsoft.com/en-us/cli/azure/ext/subscription/account?view=azure-cli-latest

**Comment by sptramer** [comment]
This document only describes how to sign in with existing accounts by design, and does not cover information on billing, subscriptions, or detailed account management. That information can be found in the [Billing and cost management documentation](https://docs.microsoft.com/en-us/azure/billing/).

**Comment by jeking3** [comment]
Okay, so the short answer is that there will be no automation capabilities around adding pay-as-you-go subscriptions.  The only supported subscriptions are two enterprise subscriptions.  This makes setting up an account more difficult if you want to use multiple subscriptions, for example in a demo account vending machine.
