### ISSUE TITLE
Cannot install: 'Install-Module -Name Az' fails with version string not in correct format error

### ISSUE THREAD

**Issue by dumbledad** [MicrosoftDocs/azure-docs-powershell#1078]
When I run 

    Install-Module -Name Az -AllowClobber

in PowerShell I get the error

> PackageManagement\Install-Package : Cannot convert value "2.0.0-preview" to type "System.Version". Error: "Input  
> string was not in a correct format."  
> At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21  
> + ...          $null = PackageManagement\Install-Package @PSBoundParameters  
> +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
>     + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E  
>    xception  
>     + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagemen  
>    t.Cmdlets.InstallPackage  

As a work-around it would be great if the documentation https://docs.microsoft.com/en-us/powershell/azure/install-az-ps highlighted the location of the MSI download (Which I cannot find)

**Comment by sptramer** [comment]
This looks like it would be an issue with `Install-Module`, so please file a bug with the team responsible (I would ask in [PowerShell issues](https://github.com/microsoft/powershell/issues) - this may be managed by the core PowerShell team.)

There is not currently an MSI installer for Azure PowerShell. If you would like one, please file a [feature request with engineering](https://github.com/azure/azure-powershell/issues).
