### ISSUE TITLE
Get-AzureServiceADDomainExtension has a poor/bad example

### ISSUE THREAD

**Issue by TheSoftwareArchitect** [MicrosoftDocs/azure-docs-powershell#1089]
The documentation for Get-AzureServiceADDomainExtension has a terrible example for the
-ServiceName option.

"PS C:\> Get-AzureServiceADDomainExtension -ServiceName $Svc"

running just that one-liner, produces this "predictable" output:

"PS C:\source> Get-AzureServiceADDomainExtension -ServiceName $Svc
Get-AzureServiceADDomainExtension : Cannot find cloud service: .
At line:1 char:1
+ Get-AzureServiceADDomainExtension -ServiceName $Svc
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureServiceADDomainExtension], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.GetAzureServiceADDomainExtensionCommand

PS C:\source>"

These examples should stand on their own.  Either find a "Service Name" that will work on every subscription or set up a dummy service than can be used for this example, please!

**Comment by sptramer** [comment]
Please file bugs and suggestions for reference documentation with the Azure PowerShell engineering team: https://github.com/azure/azure-powershell/issues
