### ISSUE TITLE
Get-AzureAccount

### ISSUE THREAD

**Issue by TheSoftwareArchitect** [MicrosoftDocs/azure-docs-powershell#1090]
I have multiple issues with Get-AzureAccount.

First:  the output.  Your example for base "Get-AzureAccount" displays two columns (Name and ActiveDirectories), but doesn't match my output at all and I see no explanation of why.  I have four columns:  ID, Type, Subscriptions, and Tenants.  I'd love to see Active Directories where they're set up, but I don't see output that even resembles yours.  I can provide more details, but I chose not to post my tenant and subscription information in a public place like this.

Is there some switch to show me EVERYTHING?  All my tenants and subscriptions?  I absolutely hate "...".  That only tells me there's something more, but no details about what it is.  Now -- this might be eliminated if I had the output your example shows.  Right now, I have "…" at the end of both subscriptions and tenants.  It turns out that I can just widen the PowerShell window and it "appears" to list all the tenants.  Or at least, I thought it did until...I used (Get-AzureAccount).Tenants to retrieve what I thought were the only tenants I had access to.  Imagine my surprise when I ran Connect-AzureAD and see a completely different tenant ID.  How can that be?

So something either could be off or is off.  Is it my Tenant, subscription, or PowerShell?  I have no idea, but It does seem like I've entered the twilight zone with my Azure PowerShell experience(s).

As a side note:  (Get-AzureAccount).Subscriptions does show the two subscriptions I should have -- one for Visual Studio Enterprise with MSDN, and the other for Visual Studio Professional.

Thanks.

**Comment by sptramer** [comment]
Please file issues regarding product suggestions and complaints with the engineering team: https://github.com/azure/azure-powershell/issues
