### ISSUE TITLE
Small typo: Because of how the Az module is package, 

### ISSUE THREAD

**Issue by marcdurham** [MicrosoftDocs/azure-docs-powershell#1091]
Should be "packaged" instead of "package"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81ecfbed-d327-751f-4d73-8aef91005e75
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.1.0)
* Content Source: [docs-conceptual/azps-2.1.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.1.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Will be fixed in the next publish.
