### ISSUE TITLE
Get-AzMetric and Get-AzMetricDefinition needs more detail in regards to output

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/azure-docs-powershell#1097]
The Get-AzMetricDefinition returns a variety of outputs, depending on the resource type.  For a VM, the list is:

- Percentage CPU
- Network In
- Network Out
- Disk Read Bytes
- Disk Write Bytes
- Disk Read Operations/Sec
- Disk Write Operations/Sec
- CPU Credits Remaining
- CPU Credits Consumed
- Per Disk Read Bytes/sec
- Per Disk Write Bytes/sec
- Per Disk Read Operations/Sec
- Per Disk Write Operations/Sec
- Per Disk QD
- OS Per Disk Read Bytes/sec
- OS Per Disk Write Bytes/sec
- OS Per Disk Read Operations/Sec
- OS Per Disk Write Operations/Sec
- OS Per Disk QD
- Data Disk Read Bytes/sec
- Data Disk Write Bytes/sec
- Data Disk Read Operations/Sec
- Data Disk Write Operations/Sec
- Data Disk Queue Depth
- OS Disk Read Bytes/sec
- OS Disk Write Bytes/sec
- OS Disk Read Operations/Sec
- OS Disk Write Operations/Sec
- OS Disk Queue Depth
- Inbound Flows
- Outbound Flows
- Inbound Flows Maximum Creation Rate
- Outbound Flows Maximum Creation Rate
- Premium Data Disk Cache Read Hit
- Premium Data Disk Cache Read Miss
- Premium OS Disk Cache Read Hit
- Premium OS Disk Cache Read Miss
- Network In Total
- Network Out Total

Unfortunately, the documentation does not provide any references (links) to documentation regarding the specific metrics for each resource type. The reader is left to _guess_ what the differences are between some of the less obvious metrics, such as 'Disk Read Bytes/Sec' vs. 'Per Disk Read Bytes/Sec' vs. 'Data Disk Read Bytes/Sec' and so on.  A link to a page where all of the various metrics/counters are described would be most helpful.

**Comment by sptramer** [comment]
Reference documentation is handled by the engineering team. Please [file an issue with engineering](https://github.com/azure/azure-powershell/issues).
