### ISSUE TITLE
When will the saved context expire? 

### ISSUE THREAD

**Issue by gadget1999** [MicrosoftDocs/azure-docs-powershell#1107]
It's quite convenient to allow saving the context to allow automated tasks. But I found that after a few days my tasks will fail and ask me to login again. It seems I can not find details about how long will the context last. Also, is it possible to change the expiration length? Frequent logins are not very easy for unattended tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3921cb5-d1cf-bd91-123a-64dd5ce45880
* Version Independent ID: f641b6fa-c346-ad1d-65a6-793a4bedcbdf
* Content: [Persist Azure credentials across PowerShell sessions](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-2.2.0#feedback)
* Content Source: [docs-conceptual/azps-2.2.0/context-persistence.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.2.0/context-persistence.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by artisticcheese** [comment]
+1

**Comment by sptramer** [comment]
@gadget1999 When contexts expire are controlled by your Azure Active Directory manager. The normal expiration period is every 90 days, but administrators can set this value to whatever they choose. You may also not have context autosave correctly configured. The context documentation was recently updated to make some of this information clearer.
