### ISSUE TITLE
Module commands cannot resolve package source

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-docs-powershell#1111]
I am able to access https://www.powershellgallery.com/ and https://www.powershellgallery.com/api/v2 (per #976), but install-module and find-module result in a warning that is blocking me.

&gt; WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8cba4d1-25f1-8a36-1cc0-b24f829d4ff0
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.2.0)
* Content Source: [docs-conceptual/azps-2.2.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.2.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MisinformedDNA** [comment]
> PS C:\WINDOWS\system32> Invoke-WebRequest https://www.powershellgallery.com/api/v2/
> 
> StatusCode        : 200
> StatusDescription : OK
> Content           : <?xml version="1.0" encoding="utf-8"?><service xml:base="https://www.powershellgallery.com/api/v2"
>                     xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom"><workspace><atom:title
>                     ty…
> RawContent        : HTTP/1.1 200 OK
>                     Cache-Control: no-cache
>                     Pragma: no-cache
>                     Server: Microsoft-IIS/10.0
>                     X-CorrelationId: 80000099-0003-c100-b63f-84710c7967bb
>                     DataServiceVersion: 3.0
>                     Content-Security-Policy: frame-a…
> Headers           : {[Cache-Control, System.String[]], [Pragma, System.String[]], [Server, System.String[]],
>                     [X-CorrelationId, System.String[]]…}
> Images            : {}
> InputFields       : {}
> Links             : {}
> RawContentLength  : 338
> RelationLink      : {}
> 
> 
> PS C:\WINDOWS\system32> Get-PSRepository
> 
> Name                      InstallationPolicy   SourceLocation
> ----                      ------------------   --------------
> PSGallery                 Trusted              https://www.powershellgallery.com/api/v2/
> 
> PS C:\WINDOWS\system32> Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls
> 
> StatusCode        : 200
> 
> PS C:\WINDOWS\system32> Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls11
> 
> StatusCode        : 200
> 
> PS C:\WINDOWS\system32> Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls12
> 
> StatusCode        : 200

I tried to install this in via the PS Core terminal (in admin mode), immediately after installing PS Core.

Win v.1803

**Comment by sptramer** [comment]
PowerShell Gallery experienced an outage this morning. I just ran `Install-Module -Name Az -AllowClobber -Force` and can confirm the endpoint is now responding correctly.

**Comment by MisinformedDNA** [comment]
I can confirm that it is still not working for me. Please reopen.

**Comment by sptramer** [comment]
Unfortunately there's not a whole lot I can do about the situation, since it's not related to documentation, and is a "works for me" situation. The issue will remain closed.

**Comment by MisinformedDNA** [comment]
Filed another issue at https://github.com/PowerShell/PowerShellGet/issues/495
