### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by sqlsolver** [MicrosoftDocs/azure-docs-powershell#1114]
The link to the New-AzADSpCredential cmdlet is broken, replace with:
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadspcredential?view=azps-2.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9093187f-5f2e-7377-9342-fd28105c728d
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.2.0#reset-credentials)
* Content Source: [docs-conceptual/azps-2.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.2.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed in #1116 and will go live at the next site publish.
