### ISSUE TITLE
Import-AzureKeyVaultCertificate does not work when attempting to move a pfx cert from one keyvault to another

### ISSUE THREAD

**Issue by thecherrytree** [MicrosoftDocs/azure-docs-powershell#1118]
**CONTEXT:** We are automating our pipeline to enable SSL binding for a webapp using custom hostnames. To do this, we need to import a certificate from an already existing shared vault. Ideally, I would be able to do this in memory as opposed to downloading the file onto the agent.

**PROBLEM:**  When attempting to import this certificate using the documentation provided, I am getting the below errors for the scenarios outlined below. It appears this function does not support importing a certificate from another keyvault, even though the documentation indicates this can be done. Can you please provide an example, as they are not provided in the documentation to clearly articulate the use of a CertificateCollection and a CertificateString. 

**When attempting to import a cert using from another keyvault using a CertificateCollection:**
`Import-AzureKeyVaultCertificate -VaultName $newKeyVaultName -Name $existingKeyVaultCertName -CertificateCollection $certCollection`

`Import-AzureKeyVaultCertificate : Device not configured `
` At /grs-arm/enable-ssl_state_on_webapp/enable-ssl_state_on_webapp.ps1:100 char:9`
`+         Import-AzureKeyVaultCertificate -VaultName $newKeyVaultName - ...`
`+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : CloseError: (:) [Import-AzKeyVaultCertificate], SocketException`
`+ FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.ImportAzureKeyVaultCertificate`

**When attempting to import a cert using a secure string and password:**
`Import-AzureKeyVaultCertificate -VaultName $newKeyVaultName -Name $existingKeyVaultCertName -CertificateString $certCollection -password $password.SecretText`

`Import-AzureKeyVaultCertificate : Device not configured `
` At /grs-arm/enable-ssl_state_on_webapp/enable-ssl_state_on_webapp.ps1:100 char:9`
`+         Import-AzureKeyVaultCertificate -VaultName $newKeyVaultName - ...`
`+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : CloseError: (:) [Import-AzKeyVaultCertificate], SocketException`
`+ FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.ImportAzureKeyVaultCertificate`

Here is my script:

<#
.SYNOPSIS
Enables the SSL state for a webapp that uses custom hostnames. 

.DESCRIPTION
When provided a webapp name (the name of app which SSL is to be enabled), a prexisting keyvault name (where the SSL cert (.pfx) is stored) and a prexisting certificate name, the SSL state will become 'sniEnabled', and the SSL certificate will be bound to the webapp.

.PARAMETER WebappName
Specifies the name of the webapp resource for which SSL is to be enabled.
Default SSL state will be: 'sniEnabled'

.PARAMETER existingKeyvaultName
Specifies the name of the pre-existing shared keyvault containing the .pfx certificate that will be bind to your webapp.

.PARAMETER existingCertificateName
Specifies the name of the pre-existing certificate in the specified keyvault that will be bound to the webapp.

.INPUTS
This function does not support any piped inputs

.OUTPUTS
Returns status of the request to the keyvault, the request for the secret provided, and the status of the binding to the hostname.

.EXAMPLE
PS>

.LINK
http://linktoWiki
#>

    [CmdletBinding()]
    param (
        [Parameter(
            Mandatory = $true,
            HelpMessage = 'A webapp name is required.')]
        [ValidateNotNullOrEmpty()]
        [string] $WebappName,`

       [PARAMETER(
            Mandatory = $true,            
            HelpMessage = 'The FQDN of the custom hostname you want to bind.')]
        [ValidateNotNullOrEmpty()]
        [string] $customWebappHostname,

        [Parameter(
            Mandatory = $true,
            HelpMessage = 'A name for an existing Keyvault is required.')]
        [ValidateNotNullOrEmpty()]
        [string] $existingKeyvaultName,
        
        [PARAMETER(
            Mandatory = $true,            
            HelpMessage = 'A name of the pfx certificate stored in the pre-existing keyvault')]
        [ValidateNotNullOrEmpty()]
        [string] $existingKeyVaultCertName
    )

    #getting webapp resources
    $webapp = Get-AzureRmResource -Name $webappName
    #obtaining resource group resources through the use of resource group name tied to webapp
    $rg = Get-AzureRmResource -ResourceGroupName $webapp.ResourceGroupName 

    #get cert from existing keyvault using provided parameters
    $cert = Get-AzureKeyVaultSecret -VaultName $existingKeyvaultName -Name $existingKeyVaultCertName
    $certFull = Get-AzureKeyVaultCertificate -VaultName $existingKeyvaultName -Name $existingKeyVaultCertName
    if ($cert -eq $null) {
        Throw "Unable to get the certificate: '$($existingKeyVaultCertName)' from the keyvault: '$($existingKeyvaultName)'. Please check that you have provided the correct vault and certificate name and try again."
    }
    #get cert password from existing keyvault using provided parameters
    $password = Get-AzureKeyVaultSecret -VaultName $existingKeyVaultName -Name "$($existingKeyVaultCertName)-password"
    if (-not $password) {
        Throw "Unable to get the secret: '$($existingKeyVaultCertName)-password' from the keyvault: '$($existingKeyvaultName)'. Please check that you have provided the correct vault and password name and try again. Note: a secret stored in a keyvault that contains the password for a PFX certificate must be named in the following pattern '<certificatename>-password'."
    }
    if ($rg) {
        #iterating over the resources and pulling those matching the appropriate resource type
        $kv = $rg | Where-Object { $_.ResourceType -Match 'Microsoft.KeyVault/vaults' }
        #iterating through the keyvaults and their access policies, looking for the keyvault that contains an access policy for the webapp.
        $vaults = $kv | ForEach-Object {Get-AzureRmKeyVault -Name $_.Name}
        $vaults | ForEach-Object {$_.accessPolicies } | ForEach-Object {
            $a = $_
            if($_.ObjectId -eq $webapp.Identity.PrincipalId){
                Write-Host "Found the keyvault $($a.DisplayName)." -Verbose
                $newKeyVaultName = $a.DisplayName.split(" ")[0]
            } 
            
        }

        #import the cert into a collection in memory
        $certBytes = [System.Convert]::FromBase64String($cert.SecretValueText)
        $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
        $certCollection.Import($certBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
        #move the cert to a new keyvault as a certcollection
        Import-AzureKeyVaultCertificate -VaultName $newKeyVaultName -Name $existingKeyVaultCertName -CertificateString $cert.secretValueText -password $password.SecretText
        #add the ssl binding to the webapp using the cert
        New-AzureRmWebAppSSLBinding -ResourceGroupName $webApp.ResourceGroupName -WebAppName $webappName -Thumprint $cert.Thumbprint -Name $customWebappHostname
    }
    else {
        ThrowError "Unable to obtain the resource group for the web application $($webappName). Please check the name any try again."
    }

**Comment by sptramer** [comment]
@thecherrytree It looks like this is either a bug or a reference documentation issue. Please file a ticket with engineering to resolve the problem: https://github.com/azure/azure-powershell/issues

Due to the amount of detail in this ticket, it should probably be linked from the created issue there.

**Comment by thecherrytree** [comment]
Thanks @sptramer. https://github.com/Azure/azure-powershell/issues/9485
