### ISSUE TITLE
New-AzSqlServerFirewallRule Only allows lowercase ServerName

### ISSUE THREAD

**Issue by Magn3s1um** [MicrosoftDocs/azure-docs-powershell#1122]
Trying to use a servername like the following example causes an error: 

`$InstanceName = "ServerName";`

`New-AzSqlServerFirewallRule -ResourceGroupName $ResourceGroup -ServerName $InstanceName -AllowAllAzureIPs`

> Servername "ServerName" cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name.

This doesn't make sense because I'm able to create the same server with that variable. 

`
New-AzSqlServer -ServerName  $InstanceName -ResourceGroupName $ResourceGroup -SqlAdministratorCredentials $mycreds -Location $Location`

A contradiction seems to be displayed on the docs as well, as it seems to contain capital letters: 

`New-AzSqlServerFirewallRule -ResourceGroupName "ResourceGroup01" -ServerName "Server01" -AllowAllAzureIPs
`

[https://docs.microsoft.com/en-us/powershell/module/az.sql/new-azsqlserverfirewallrule?view=azps-2.3.2](url)

The obvious work around: 

New-AzSqlServerFirewallRule -ResourceGroupName $ResourceGroup -ServerName $InstanceName.ToLower() -AllowAllAzureIPs

**Comment by sptramer** [comment]
This sounds like a bug in the implementation. Please file an issue with the engineering team: https://github.com/azure/azure-powershell/issues
