### ISSUE TITLE
Lots of typo in the release notes found since AzureRM to Az transition

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/azure-docs-powershell#1128]
You can search with `-AzureRm` in the brower to find it out. for axamples:

1. In version **2.3.2**, totoally 12 typo were found.
![image](https://user-images.githubusercontent.com/6244148/60073803-fd581a00-9753-11e9-8fd4-3275b2c67424.png)
![image](https://user-images.githubusercontent.com/6244148/60073851-1d87d900-9754-11e9-8cf8-a3026b3b294f.png)
![image](https://user-images.githubusercontent.com/6244148/60073887-36908a00-9754-11e9-8c2f-9d610b48d159.png)
2. In version **2.1.0**, one typo was found
![image](https://user-images.githubusercontent.com/6244148/60074123-c33b4800-9754-11e9-82e3-5b4454ed18db.png)

**In the latest Az module, only three cmdlets contains AzureRm in its name.**
```powershell
PS C:\WINDOWS\system32> Get-InstalledModule Az

Version              Name                                Repository           Description                                                           
-------              ----                                ----------           -----------                                                           
2.3.2                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure.


PS C:\WINDOWS\system32> Get-Command *AzureRm*

CommandType     Name                                               Version    Source                                                                
-----------     ----                                               -------    ------                                                                
Cmdlet          Disable-AzureRmAlias                               1.5.3      Az.Accounts                                                           
Cmdlet          Enable-AzureRmAlias                                1.5.3      Az.Accounts                                                           
Cmdlet          Uninstall-AzureRm                                  1.5.3      Az.Accounts    
```
I am not sure if  it's caused by the the source URL https://github.com/Azure/azure-powershell/releases 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d01c302-204d-a4dd-a940-bc4c31fcff12
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [2.3.2 - June 2019](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-2.3.2)
* Content Source: [docs-conceptual/azps-2.3.2/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.3.2/release-notes-azureps.md)
* GitHub Login: @huypub

**Comment by sptramer** [comment]
Thanks for the feedback, release notes will be fixed in the near future.

**Comment by dcaro** [comment]
@ToMakeSense Thanks for opening the issue, we have reviewed the ChangeLog and Release Notes and fixed the occurrences of AzureRM.
The changes have just been merged minutes ago.

**Comment by ToMakeSense** [comment]
Checked the source URL https://github.com/Azure/azure-powershell/releases, It seems that it has not been fully fixed. see below:

**Az 2.4.0** (it's fix on both AzureRM and Az module)
![image](https://user-images.githubusercontent.com/6244148/61269050-fc089300-a7cf-11e9-9f4b-bad2acb482af.png)

**Az 2.3.2**
![image](https://user-images.githubusercontent.com/6244148/61269131-3a05b700-a7d0-11e9-9fdc-03a595fd57d9.png)

**2.1.0**
![image](https://user-images.githubusercontent.com/6244148/61269181-53a6fe80-a7d0-11e9-8e86-727bb607242f.png)

There's no typo between Az 1.4 to Az.1.8, I will check Az 1.0~Az.1.3 and update it later.

**Comment by sptramer** [comment]
I believe that there were some pull requests submitted which took care of this issue, but I've added a task to clean up and copyedit the existing release notes. Future release notes will be copyedited either before, or shortly after, publish.

**Comment by mikefrobbins** [comment]
Confirmed that the reported typos no longer exist in the specified docs.
