### ISSUE TITLE
Microsoft Virtual Academy Link

### ISSUE THREAD

**Issue by GBPhilip** [MicrosoftDocs/azure-docs-powershell#1129]
This page has a link for a jumpstart to Powershell that goes to Microsoft Virtual Academy - hasn't that been retired?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38edb30c-0846-fe7d-2d89-2da5a5c8aa36
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-2.3.2#feedback)
* Content Source: [docs-conceptual/azps-2.3.2/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.3.2/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This should be fixed in the next site publish. Thanks!
