### ISSUE TITLE
Instructions are broken

### ISSUE THREAD

**Issue by bichuga** [MicrosoftDocs/azure-docs-powershell#1133]
PS C:\Users\lukesch&gt; Uninstall-AllModules -TargetModule Az -Version 2.1.0 -Force
Creating list of dependencies...
WARNING: Could not find uninstall candidate for Az.Accounts:2.1.0 - module may require manual uninstall. Available
versions are: 1.5.2
WARNING: Could not find uninstall candidate for Az.Aks:2.1.0 - module may require manual uninstall. Available versions
are: 1.0.1
WARNING: Could not find uninstall candidate for Az.AnalysisServices:2.1.0 - module may require manual uninstall.
Available versions are: 1.1.0
WARNING: Could not find uninstall candidate for Az.ApiManagement:2.1.0 - module may require manual uninstall. Available
 versions are: 1.1.0
WARNING: Could not find uninstall candidate for Az.ApplicationInsights:2.1.0 - module may require manual uninstall.
Available versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.Automation:2.1.0 - module may require manual uninstall. Available
versions are: 1.2.2
WARNING: Could not find uninstall candidate for Az.Batch:2.1.0 - module may require manual uninstall. Available
versions are: 1.1.0
WARNING: Could not find uninstall candidate for Az.Billing:2.1.0 - module may require manual uninstall. Available
versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.Cdn:2.1.0 - module may require manual uninstall. Available versions
are: 1.2.0
WARNING: Could not find uninstall candidate for Az.CognitiveServices:2.1.0 - module may require manual uninstall.
Available versions are: 1.1.1
WARNING: Could not find uninstall candidate for Az.ContainerInstance:2.1.0 - module may require manual uninstall.
Available versions are: 1.0.1
WARNING: Could not find uninstall candidate for Az.ContainerRegistry:2.1.0 - module may require manual uninstall.
Available versions are: 1.0.1
WARNING: Could not find uninstall candidate for Az.DataFactory:2.1.0 - module may require manual uninstall. Available
versions are: 1.1.1
WARNING: Could not find uninstall candidate for Az.DataLakeAnalytics:2.1.0 - module may require manual uninstall.
Available versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.DataLakeStore:2.1.0 - module may require manual uninstall. Available
 versions are: 1.2.1
WARNING: Could not find uninstall candidate for Az.DeploymentManager:2.1.0 - module may require manual uninstall.
Available versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.DevTestLabs:2.1.0 - module may require manual uninstall. Available
versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.Dns:2.1.0 - module may require manual uninstall. Available versions
are: 1.1.0
WARNING: Could not find uninstall candidate for Az.EventGrid:2.1.0 - module may require manual uninstall. Available
versions are: 1.1.1
WARNING: Could not find uninstall candidate for Az.EventHub:2.1.0 - module may require manual uninstall. Available
versions are: 1.1.0
WARNING: Could not find uninstall candidate for Az.FrontDoor:2.1.0 - module may require manual uninstall. Available
versions are: 1.0.0
WARNING: Could not find uninstall candidate for Az.HDInsight:2.1.0 - module may require manual uninstall. Available
versions are: 2.0.0
WARNING: Could not find uninstall candidate for Az.IotHub:2.1.0 - module may require manual uninstall. Available
versions are: 1.1.0
WARNING: Could not find uninstall candidate for Az.KeyVault:2.1.0 - module may require manual uninstall. Available
versions are: 1.2.0
WARNING: Could not find uninstall candidate for Az.LogicApp:2.1.0 - module may require manual uninstall. Available
versions are: 1.2.1

This works:

workflow Uninstall-AzureModules
{
    $Modules = (Get-Module -ListAvailable Azure*).Name |Get-Unique
    Foreach -parallel ($Module in $Modules)
    { 
        Write-Output ("Uninstalling: $Module")
        Uninstall-Module $Module -Force
    }
}
Uninstall-AzureModules
Uninstall-AzureModules   #second invocation to truly remove everything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37445ffd-7887-959f-b203-1090ccb3fe51
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-2.3.2#feedback)
* Content Source: [docs-conceptual/azps-2.3.2/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.3.2/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by bichuga** [comment]
The line above should read 

$Modules = (Get-Module -ListAvailable Az.*).Name |Get-Unique

**Comment by sptramer** [comment]
You're correct that the current script may not work as expected. This is because uninstalling modules which use a `MinimumVersion` requirement rather than `RequiredVersion` can cause dependency problems when being removed, if only uninstalling a single version. Right now the removal script can only provide guidance on how to handle minimum version removal.

**Comment by bichuga** [comment]
Any thought on updating the docs to use some form of the script I provided?

**Comment by ankushbindlish2** [comment]
Same issue encountered. 

PS H:\onebranch\Storage\XSync\Dev\src\Kailani> $versions | foreach { Uninstall-AllModules -TargetModule AzureRM -Version ($_.Version) -Force }
Creating list of dependencies...
WARNING: Could not find uninstall candidate for AzureRM.Profile:6.13.1 - module may require manual uninstall. Available versions are: 5.8.2, 5.8.3
WARNING: Could not find uninstall candidate for Azure.Storage:6.13.1 - module may require manual uninstall. Available versions are: 4.6.1
WARNING: Could not find uninstall candidate for AzureRM.AnalysisServices:6.13.1 - module may require manual uninstall. Available versions are: 0.6.14
WARNING: Could not find uninstall candidate for Azure.AnalysisServices:6.13.1 - module may require manual uninstall. Available versions are: 0.5.4
WARNING: Could not find uninstall candidate for AzureRM.ApiManagement:6.13.1 - module may require manual uninstall. Available versions are: 6.1.7
WARNING: Could not find uninstall candidate for AzureRM.ApplicationInsights:6.13.1 - module may require manual uninstall. Available versions are: 0.1.8
WARNING: Could not find uninstall candidate for AzureRM.Automation:6.13.1 - module may require manual uninstall. Available versions are: 6.1.1
WARNING: Could not find uninstall candidate for AzureRM.Backup:6.13.1 - module may require manual uninstall. Available versions are: 4.0.11
WARNING: Could not find uninstall candidate for AzureRM.Batch:6.13.1 - module may require manual uninstall. Available versions are: 4.1.5
WARNING: Could not find uninstall candidate for AzureRM.Billing:6.13.1 - module may require manual uninstall. Available versions are: 0.14.6
WARNING: Could not find uninstall candidate for AzureRM.Cdn:6.13.1 - module may require manual uninstall. Available versions are: 5.0.6
WARNING: Could not find uninstall candidate for AzureRM.CognitiveServices:6.13.1 - module may require manual uninstall. Available versions are: 0.9.12
WARNING: Could not find uninstall candidate for AzureRM.Compute:6.13.1 - module may require manual uninstall. Available versions are: 5.9.1
WARNING: Could not find uninstall candidate for AzureRM.Consumption:6.13.1 - module may require manual uninstall. Available versions are: 0.3.7
WARNING: Could not find uninstall candidate for AzureRM.ContainerInstance:6.13.1 - module may require manual uninstall. Available versions are: 0.2.12
WARNING: Could not find uninstall candidate for AzureRM.ContainerRegistry:6.13.1 - module may require manual uninstall. Available versions are: 1.0.10
WARNING: Could not find uninstall candidate for AzureRM.DataFactories:6.13.1 - module may require manual uninstall. Available versions are: 5.0.3
WARNING: Could not find uninstall candidate for AzureRM.DataFactoryV2:6.13.1 - module may require manual uninstall. Available versions are: 0.5.11
WARNING: Could not find uninstall candidate for AzureRM.DataLakeAnalytics:6.13.1 - module may require manual uninstall. Available versions are: 5.1.4
WARNING: Could not find uninstall candidate for AzureRM.DataLakeStore:6.13.1 - module may require manual uninstall. Available versions are: 6.2.1
WARNING: Could not find uninstall candidate for AzureRM.DevTestLabs:6.13.1 - module may require manual uninstall. Available versions are: 4.0.9
WARNING: Could not find uninstall candidate for AzureRM.Dns:6.13.1 - module may require manual uninstall. Available versions are: 5.1.0
WARNING: Could not find uninstall candidate for AzureRM.EventGrid:6.13.1 - module may require manual uninstall. Available versions are: 0.3.7
WARNING: Could not find uninstall candidate for AzureRM.EventHub:6.13.1 - module may require manual uninstall. Available versions are: 0.7.0
WARNING: Could not find uninstall candidate for AzureRM.HDInsight:6.13.1 - module may require manual uninstall. Available versions are: 4.1.8
WARNING: Could not find uninstall candidate for AzureRM.Insights:6.13.1 - module may require manual uninstall. Available versions are: 5.1.5
WARNING: Could not find uninstall candidate for AzureRM.IotHub:6.13.1 - module may require manual uninstall. Available versions are: 3.1.8
WARNING: Could not find uninstall candidate for AzureRM.KeyVault:6.13.1 - module may require manual uninstall. Available versions are: 5.2.1
WARNING: Could not find uninstall candidate for AzureRM.LogicApp:6.13.1 - module may require manual uninstall. Available versions are: 4.1.4
WARNING: Could not find uninstall candidate for AzureRM.MachineLearning:6.13.1 - module may require manual uninstall. Available versions are: 0.18.5
WARNING: Could not find uninstall candidate for AzureRM.MachineLearningCompute:6.13.1 - module may require manual uninstall. Available versions are: 0.4.8
WARNING: Could not find uninstall candidate for AzureRM.MarketplaceOrdering:6.13.1 - module may require manual uninstall. Available versions are: 0.2.7
WARNING: Could not find uninstall candidate for AzureRM.Media:6.13.1 - module may require manual uninstall. Available versions are: 0.10.4
WARNING: Could not find uninstall candidate for AzureRM.Network:6.13.1 - module may require manual uninstall. Available versions are: 6.11.1
WARNING: Could not find uninstall candidate for AzureRM.NotificationHubs:6.13.1 - module may require manual uninstall. Available versions are: 5.0.3
WARNING: Could not find uninstall candidate for AzureRM.OperationalInsights:6.13.1 - module may require manual uninstall. Available versions are: 5.0.6
WARNING: Could not find uninstall candidate for AzureRM.PolicyInsights:6.13.1 - module may require manual uninstall. Available versions are: 1.1.0
WARNING: Could not find uninstall candidate for AzureRM.PowerBIEmbedded:6.13.1 - module may require manual uninstall. Available versions are: 4.1.10
WARNING: Could not find uninstall candidate for AzureRM.RecoveryServices:6.13.1 - module may require manual uninstall. Available versions are: 4.1.9
WARNING: Could not find uninstall candidate for AzureRM.RecoveryServices.Backup:6.13.1 - module may require manual uninstall. Available versions are: 4.5.2
WARNING: Could not find uninstall candidate for AzureRM.RecoveryServices.SiteRecovery:6.13.1 - module may require manual uninstall. Available versions are: 0.2.12
WARNING: Could not find uninstall candidate for AzureRM.RedisCache:6.13.1 - module may require manual uninstall. Available versions are: 5.1.0
WARNING: Could not find uninstall candidate for AzureRM.Relay:6.13.1 - module may require manual uninstall. Available versions are: 0.3.12
WARNING: Could not find uninstall candidate for AzureRM.Resources:6.13.1 - module may require manual uninstall. Available versions are: 6.7.3
WARNING: Could not find uninstall candidate for AzureRM.Scheduler:6.13.1 - module may require manual uninstall. Available versions are: 0.16.10
WARNING: Could not find uninstall candidate for AzureRM.ServiceBus:6.13.1 - module may require manual uninstall. Available versions are: 0.6.13

**Comment by mganeshphani** [comment]
Didn't expect Microsoft to write a script that will be easily broken... lol

**Comment by Brucius** [comment]
Was facing the same issue. The below script worked for me
```$versions = (Get-InstalledModule AzureRM -AllVersions | Select-Object Version)
$versions | foreach { Uninstall-AllModules -TargetModule AzureRM -Version ($_.Version) -Force }
Get-Module -ListAvailable | Where-Object { $_.Name -like 'AzureRM*' } | Uninstall-Module```

**Comment by Suchiman** [comment]
This is utterly useless... but just unleashing your rage on `C:\Program Files\WindowsPowerShell\Modules` will work.

**Comment by cutty201** [comment]
Absolutely --- Microsoft is terrible -- You should not be allowed to be 1trillion software company when you don't understand how to properly remove your own software --- further -- you shouldn't be a 1trillion dollar software company if you do not know how to upgrade your own software. You can afford to hire people that understand how things work. 
`PS C:\WINDOWS\system32> $versions = Get-InstalledModule AzureRM.* | Select-Object -Property Name,Version
PS C:\WINDOWS\system32> $versions | foreach { Uninstall-AllModules -TargetModule $_.Name -Version ($_.Version) -Force }`

**Comment by cutty201** [comment]
Ok let me follow up with what works 

Merry Christmas! 

```
Remove-Module AzureRM.Profile -Force
$versions = Get-InstalledModule Azure* | Select-Object -Property Name,Version
$versions | foreach { Uninstall-AllModules -TargetModule $_.Name -Version ($_.Version) -Force }

**Comment by wt-ho-test** [comment]
is the doc updated?

**Comment by sptramer** [comment]
Hi all -

I've been tracking this issue for a while now, thinking about how to best handle it. The real problem with the script is that we want to keep things flexible for users to allow uninstalling whatever version they want, while preserving dependency relations. That's why the script hasn't just changed to be a highly-efficient nuke of the entire `Az.*` module set (although that works fine, and is what I'd personally recommend for right now, and what @cutty201 has helpfully provided.) PowerShell doesn't have good tools in place for resolving [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell), which is what makes uninstall hard to do with a generic script.

I'm targeting the uninstall instructions to be updated sometime this month to be much simpler and more comprehensive, although they may be stored in an external script. We're also re-introducing MSI installs on the documentation page, which is a more efficient way to manage your installations if you need to frequently remove older versions. You can actually get the MSIs right now, [from the GitHub Releases page](https://github.com/Azure/azure-powershell/releases).

**Comment by pixelicous** [comment]
And the documentation still persists with old non working script.. 🤦‍♂

**Comment by SQLtattoo** [comment]
My penny...

```
$versions = Get-InstalledModule Az.* | Select-Object -Property Name,Version
$countmods = Get-InstalledModule Az.* | Measure-Object

Write-Host "Modules found: " $versions

while($countmods.Count -gt 0)
{
    $versions | foreach { 
        Uninstall-Module -Name $_.Name -MinimumVersion $_.Version  -Force 
        Write-Host "Removed: " $_.Name $_.Version
    }   
}
```

Otherwise, you have to iterate manually to make it work.

Cheers!

**Comment by SQLtattoo** [comment]
My penny...
Warning: no error handling...
```
$versions = Get-InstalledModule Az.* | Select-Object -Property Name,Version
$countmods = Get-InstalledModule Az.* | Measure-Object

Write-Host "Modules found: " $versions

while($countmods.Count -gt 0)
{
    $versions | foreach { 
        Uninstall-Module -Name $_.Name -MinimumVersion $_.Version  -Force 
        Write-Host "Removed: " $_.Name $_.Version
    }

    $versions = Get-InstalledModule Az.* | Select-Object -Property Name,Version
    $countmods = Get-InstalledModule Az.* | Measure-Object
}
```
Cheers!
