### ISSUE TITLE
Need RSS

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/azure-docs-powershell#1135]
It would be great if we had an rss feed for this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d01c302-204d-a4dd-a940-bc4c31fcff12
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [2.3.2 - June 2019](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-2.3.2&viewFallbackFrom=azps-2.1.0#feedback)
* Content Source: [docs-conceptual/azps-2.3.2/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.3.2/release-notes-azureps.md)
* GitHub Login: @huypub

**Comment by sptramer** [comment]
@cconrado I'm looking into whether or not we have support for this on our site publishing, and if we don't, am working to start a discussion about whether or not we could offer it. I will keep this ticket open for a while while we have those discussions so I can let you know if we can, or plan to, offer this support.

Thanks for the idea!

**Comment by sptramer** [comment]
I've checked in with the site engineering team, and there isn't RSS support at this time (and there isn't any planned.) Instead you can follow the [team blog](https://docs.microsoft.com/en-us/teamblog/) on RSS. Additionally, we're working on allowing users to bookmark their most frequently visited content on their docs site profile.

**Comment by dcbrown16** [comment]
Following this page seems like a reasonable equivalent?
https://github.com/Azure/azure-powershell/releases
