### ISSUE TITLE
Fix ToC title

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs-powershell#1142]
Can we just go with "Az release notes" instead of specifying 2.1.0 there, which is several months out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdccb010-56a6-4321-76d8-204c6da79354
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [2.4.0 - July 2019](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-2.4.0)
* Content Source: [docs-conceptual/azps-2.4.0/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.4.0/release-notes-azureps.md)
* GitHub Login: @huypub

**Comment by sptramer** [comment]
This should be fixed at the next site publish. Thanks!
