### ISSUE TITLE
Change Get-AzureRmSubscription to Get-AzSubscription

### ISSUE THREAD

**Issue by olga-microsoft** [MicrosoftDocs/azure-docs-powershell#1144]
Get-AzureRmSubscription : The term 'Get-AzureRmSubscription' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef7143a-d3c7-5240-f7d6-4127f876d620
* Version Independent ID: ca7d09a1-946b-c7fd-d659-0995c6910b20
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/manage-subscriptions-azureps?view=azurermps-6.13.0&viewFallbackFrom=azps-2.4.0#feedback)
* Content Source: [docs-conceptual/azurermps-6.13.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/manage-subscriptions-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You're looking at the documentation for AzureRM, as evidenced by the URL (https://docs.microsoft.com/en-us/powershell/azure/azurerm/manage-subscriptions-azureps?view=azurermps-6.13.0&). You want the documentation for the current release, located at https://docs.microsoft.com/powershell/azure/manage-subscriptions-azureps. Documentation in the `azurerm` path is for archive purposes only while users migrate from AzureRM to Az.
