### ISSUE TITLE
Is it possible to restrict Service Principal access to a specific Resource Group?

### ISSUE THREAD

**Issue by jannikbuschke** [MicrosoftDocs/azure-docs-powershell#1176]
Question in title...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7fe99a2-1334-c424-2e68-942d99ea7c68
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.4.0)
* Content Source: [docs-conceptual/azps-2.4.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.4.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You're most likely to find the answer to this question in the official [Azure Active Directory](https://docs.microsoft.com/azure/active-directory/) documentation.
