### ISSUE TITLE
Please revise "To install Az modules at a global scope...."

### ISSUE THREAD

**Issue by gutzeit1106** [MicrosoftDocs/azure-docs-powershell#1182]
The following section is not executed  as expected. Now Az Module will be installed as current user scope.

”Install-Module -Name Az -AllowClobber”

Install-Module was changed from PowershellGet version 2.0.0 and above. When no Scope is defined, the default is set as "CurrentUser" in the latest version.
Please refer to the following document. I'd like to update this document.

Install-Module
https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-6

"""
-Scope
Specifies the installation scope of the module. The acceptable values for this parameter are AllUsers and CurrentUser.

The AllUsers scope installs modules in a location that is accessible to all users of the computer:

$env:ProgramFiles\PowerShell\Modules

The CurrentUser installs modules in a location that is accessible only to the current user of the computer:

$home\Documents\PowerShell\Modules

When no Scope is defined, the default is set based on the PowerShellGet version.

In PowerShellGet versions 2.0.0 and above, the default is CurrentUser, which does not require elevation for install.
In PowerShellGet 1.x versions, the default is AllUsers, which requires elevation for install.
"""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b463ddac-7dc9-5c79-bba6-c09f52063d76
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.4.0#feedback)
* Content Source: [docs-conceptual/azps-2.4.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.4.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by szb512** [comment]
It probab;y didn't install right. Try running Install-Module -Name Az -AllowClobber -Scope CurrentUser again and see what happens.

**Comment by szb512** [comment]
And I meant to put probably.
