### ISSUE TITLE
More clarity needed AZ vs AzureRm Module Feature comparison

### ISSUE THREAD

**Issue by cdelcambre** [MicrosoftDocs/azure-docs-powershell#1189]
Your last paragraph is very vague.  If I may be so bold as to paraphrase, it says "We're working on it really hard".  We can't make a road map and schedule resources with this type of verbiage.  While MS is not announcing a hard date you will achieve feature parity, you have guessed the earliest date possible to retire AzureRM (December 2020).   It would be nice to know that you will Guarantee us X amount of time between when you achieve full feature parity with sustained stability so that non-beta testers can put on our roadmap when we will begin our re-coding effort.   We have more than 50k lines of code in our scripts repository.   We accept the reasons you are asking us to cut over but please provide firmer answers about where you are in your work so we can know when to start our work.  And...  To clarify, I mean to say...   Start our work once you are feature complete and stabilized so that we are not your beta testers.  We simply don't have the resources to be your testers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16f529bb-64bc-63a6-6674-bc820b9fe534
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-2.5.0#feedback)
* Content Source: [docs-conceptual/azps-2.5.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Feature parity was achieved in the 1.0 GA, in December 2018. This is why onboarding to Az is determined entirely by _your organization_: Feature parity is there, and it is up to you to perform the updates.

Because December 2020 is the earliest possible retirement date for AzureRM, treat it as the reirement date at this time. That is the only date the engineering team has committed to as a possible "end of support."

**Comment by cdelcambre** [comment]
This is good to know, why not be more explicit in your public document?

[Astea]<https://www.astea.com/>
Cody Delcambre
Technical Architect
T: (949)784-5020 | www.astea.com<http://www.astea.com>

**Comment by sptramer** [comment]
The documentation will be updated to make things a little clearer about end of support.
