### ISSUE TITLE
Login-AzureRmAccount command found but can't be loaded

### ISSUE THREAD

**Issue by tomrijntjes** [MicrosoftDocs/azure-docs-powershell#1193]
Generated powershell scripts packaged with the ARM template with the 'Export Template' functionality in the portal relies on the Login-AzureRmAccount command. Running this command separately leads to the following complaint:

```
Login-AzureRmAccount : The 'Login-AzureRmAccount' command was found in the module 'AzureRM.profile', but the module could not be loaded. For more information, run 'Import-Module AzureRM.profile'.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Login-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

Following that instruction, running Import-Module AzureRM.profile causes
```
Import-Module : Assembly with same name is already loaded
At line:1 char:1
+ Import-Module AzureRM.profile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Leading to the conclusion that the module is loaded but the command is not available. Why?

AzureRM 6.13.1, AzureRM.profile is of version 5.8.2
Powershell version 6.2.2 on MacOS 10.14 Mojave

**Comment by tomrijntjes** [comment]
Closing since this is a product issue.

**Comment by michaelbunney** [comment]
May I suggest that when a reported documentation issue turns out to be a product issue, rather than just closing the bug, a bug be submitted to the product team and the bug number noted here when closing.

The bottom line is that a bug is a bug, and while just closing it may help with housekeeping, it doesn't help solve the issue.

**Comment by KrishnaG-MSFT** [comment]
@michaelbunney Thanks for the comment.
@tomrijntjes If possible, please provide product bug number / URL here. Thanks.
