### ISSUE TITLE
Using Azure az commands in a ADO release task

### ISSUE THREAD

**Issue by gobananasgo** [MicrosoftDocs/azure-docs-powershell#1194]
To use a script with the Azure az commands in a release task, the release needs to be using a Hosted Agent, as well as the powershell task on version 4 (currently in preview). The other versions appear to support azure RM only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66146c87-f3b5-68cb-5117-067469946535
* Version Independent ID: 3da6471e-bcaf-2b48-5a52-30ef3afebde3
* Content: [Migrate Azure PowerShell scripts from AzureRM to Az](https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-2.5.0#feedback)
* Content Source: [docs-conceptual/azps-2.5.0/migrate-from-azurerm-to-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/migrate-from-azurerm-to-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please [report this as a bug](https://azure.microsoft.com/en-us/support/devops/) (or feature request) to the Azure DevOps team.
