### ISSUE TITLE
pre-requisites still missing as per application

### ISSUE THREAD

**Issue by kitkatneko** [MicrosoftDocs/azure-docs-powershell#1197]
Have IE ESC is off, POSH 5.1, AZ 2.5.0 and Az File Storage Sync 1.2.0 however application still says prereqs are missing.

AfsVersion 7.2.0.0, OSVersion: 10.0.14393, OS:win10-sha256
PS C:\Windows\system32&gt; Get-InstalledModule -name *storagesync* -Verbose

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.2.0      Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlet...

PS C:\Windows\system32&gt; Get-InstalledModule -name *az* -Verbose

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.5.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage r...

ERROR:
Retry server registration after performing the following actions:

Install either the latest Az or AzureRM PowerShell module:

• Az and StorageSync PowerShell modules (requires .NET 4.7.2):
   Az: https://go.microsoft.com/fwlink/?linkid=2062890
   Az.StorageSync: https://go.microsoft.com/fwlink/?linkid=2080003 

• AzureRM PowerShell module:
   AzureRM: https://go.microsoft.com/fwlink/?linkid=856959

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d4e55-748c-7a4a-d3be-3d6b92c80a26
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-Az-ps?view=azps-2.5.0)
* Content Source: [docs-conceptual/azps-2.5.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Sorry, I'm not quite sure what the error you're encountering here is, because there's no command listed before your 'ERROR' block. Please make sure that you follow _all_ of the [install instructions](https://docs.microsoft.com/en-us/powershell/azure/install-Az-ps?view=azps-2.6.0), including the use of `-AllowClobber` to ensure proper upgrades _and_ uninstalling any existing `AzureRM` modules. For instructions on uninstalling AzureRM, see [Uninstall AzureRM](https://docs.microsoft.com/en-us/powershell/azure/azurerm/uninstall-azurerm-ps?view=azurermps-6.13.0).

If the Az.StorageSync module is installed separately from the `Az` module bundle, then you may need to file a bug report with the Azure PowerShell engineering team: https://github.com/azure/azure-powershell/issues

If you still have problems after that, reply in this thread again, but make sure that you paste the full output of `Get-InstalledModule -Name Az.*` inside of a [markdown code block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

**Comment by kitkatneko** [comment]
@sptramer what I am saying is that all the prerequisites are met are per the install step, however the installer still "thinks" this is missing! The error is from the Azure File Sync utility is:

`**Pre-requisites are missing**
Retry server registration after performing the following actions:

Install either the latest Az or AzureRM PowerShell module:

• Az and StorageSync PowerShell modules (requires .NET 4.7.2):
   Az: https://go.microsoft.com/fwlink/?linkid=2062890
   Az.StorageSync: https://go.microsoft.com/fwlink/?linkid=2080003 

• AzureRM PowerShell module:
   AzureRM: https://go.microsoft.com/fwlink/?linkid=856959`


The Az module have been installed.
`PS C:\Windows\system32> Get-InstalledModule -Name Az.*

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.6.1      Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential...
1.0.0      Az.Advisor                          PSGallery            Microsoft Azure PowerShell - Azure Advisor Cmdle...
1.0.1      Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure managed Kuber...
1.1.0      Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis Services c...
1.2.0      Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Management serv...
1.0.1      Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell - Application Insight...
1.3.1      Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automation service ...
1.1.0      Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch service cmdle...
1.0.0      Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing service cmd...
1.3.0      Az.Cdn                              PSGallery            Microsoft Azure PowerShell - CDN service cmdlets...
1.2.0      Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive Services ...
2.4.1      Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmd...
1.0.1      Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell - Container Instance ...
1.1.0      Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container Registry ...
1.1.3      Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Factory servic...
1.0.0      Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake Analytics...
1.2.1      Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Data Lake Sto...
1.0.0      Az.DeploymentManager                PSGallery            PowerShell .Net Core Microsoft Azure PowerShell ...
1.0.0      Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest Labs servic...
1.1.1      Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS service cmdlets...
1.2.1      Az.EventGrid                        PSGallery            Microsoft Azure PowerShell - Event Grid service ...
1.3.0      Az.EventHub                         PSGallery            Microsoft Azure PowerShell - Event Hubs service ...
1.1.0      Az.FrontDoor                        PSGallery            Microsoft Azure PowerShell - Front Door service ...
2.0.0      Az.HDInsight                        PSGallery            Microsoft Azure PowerShell - HDInsight service c...
1.2.0      Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmd...
1.3.0      Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault service c...
1.3.0      Az.LogicApp                         PSGallery            Microsoft Azure PowerShell - Logic Apps cmdlets ...
1.1.0      Az.MachineLearning                  PSGallery            Microsoft Azure PowerShell - Machine Learning We...
1.0.0      Az.ManagedServices                  PSGallery            Microsoft Azure PowerShell - ManagedServices cmd...
1.0.0      Az.MarketplaceOrdering              PSGallery            Microsoft Azure PowerShell - Marketplace Orderin...
1.1.0      Az.Media                            PSGallery            Microsoft Azure PowerShell - Media service cmdle...
1.2.1      Az.Monitor                          PSGallery            Microsoft Azure PowerShell - Monitor service cmd...
1.12.0     Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service ...
1.1.0      Az.NotificationHubs                 PSGallery            Microsoft Azure PowerShell - Notification Hubs c...
1.3.2      Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insight...
1.1.2      Az.PolicyInsights                   PSGallery            Microsoft Azure PowerShell - Azure Policy Insigh...
1.1.0      Az.PowerBIEmbedded                  PSGallery            Microsoft Azure PowerShell - Power BI Embedded s...
1.4.3      Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services c...
1.1.0      Az.RedisCache                       PSGallery            Microsoft Azure PowerShell - Redis Cache service...
1.0.1      Az.Relay                            PSGallery            Microsoft Azure PowerShell - Relay service cmdle...
1.6.1      Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Mana...
1.3.0      Az.ServiceBus                       PSGallery            Microsoft Azure PowerShell - Service Bus service...
1.1.1      Az.ServiceFabric                    PSGallery            Microsoft Azure PowerShell - Service Fabric cmdl...
1.0.2      Az.SignalR                          PSGallery            Microsoft Azure PowerShell - Azure SignalR servi...
1.13.1     Az.Sql                              PSGallery            Microsoft Azure PowerShell - SQL service cmdlets...
1.5.1      Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service dat...
1.2.0      Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlet...
1.0.0      Az.StreamAnalytics                  PSGallery            Microsoft Azure PowerShell - Stream Analytics se...
1.0.1      Az.TrafficManager                   PSGallery            Microsoft Azure PowerShell - Traffic Manager ser...
1.4.0      Az.Websites                         PSGallery            Microsoft Azure PowerShell - App Service (Web Ap...`

**Comment by sptramer** [comment]
@kitkatneko In that case, this sounds like it's a product bug. Please [file an issue with engineering](https://github.com/Azure/azure-powershell/issues/new/choose).
