### ISSUE TITLE
How to set the default subscription when signing in with Connect-AzAccount

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-docs-powershell#1198]
This document says "To change the default subscription used when logging in with Azure PowerShell, use Set-AzDefault." but Set-AzDefault sets the default resource group from within the current context, what is the way to set the default context used when signing in with Connect-AzAccount.  Is it possible to actually change that default?

And how is the default actually determined, is there some property the cmdlet is keying off of to pick the "first" subscription in a list, or is there some setting from within the Azure Portal that controls this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5913d1-8289-7843-1473-a2f1096d63a9
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-2.5.0#feedback)
* Content Source: [docs-conceptual/azps-2.5.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by asubmani** [comment]
Once you connect using `Connect-AzAccount`, execute the below command to change your subscription.

`Get-AzSubscription -SubscriptionName "<enter your subscription here>"|Select-AzSubscription`

**Comment by FISHMANPET** [comment]
That changes the subscription in my current context but I want to change the _default_ subscription.  When I signin in I have access to 4 subscriptions and it picks subscription A but I want subscription C to be the one I'm connected to when I make a connection.

**Comment by sptramer** [comment]
I believe that once you select a subscription it becomes your new default. The article discussing how contexts work is in the middle of an extensive rewrite right now, and I'll make sure that default subscription selection is covered.

**Comment by FISHMANPET** [comment]
@sptramer that is not the behavior I'm seeing:
```
PS C:\Users\bajurny> Connect-AzAccount

Account         SubscriptionName TenantId   Environment
-------         ---------------- --------   -----------
bajurny@umn.edu SubscriptionA    <tenantid> AzureCloud 


PS C:\Users\bajurny> Get-AzSubscription

Name          Id               TenantId   State   
----          --               --------   -----   
SubscriptionA <subscriptionid> <tenantid> Enabled 
SubscriptionB <subscriptionid> <tenantid> Disabled
SubscriptionC <subscriptionid> <tenantid> Enabled 
SubscriptionD <subscriptionid> <tenantid> Enabled 


PS C:\Users\bajurny> Set-AzContext -Subscription "SubscriptionC"

Name                     Account         SubscriptionName     Environment   TenantId                           
----                     -------         ----------------     -----------   --------                           
SubscriptionC (<subid... bajurny@umn.edu SubscriptionC        AzureCloud    <tenantid...


PS C:\Users\bajurny> Disconnect-AzAccount


PS C:\Users\bajurny> Connect-AzAccount

Account         SubscriptionName TenantId   Environment
-------         ---------------- --------   -----------
bajurny@umn.edu SubscriptionA    <tenantid> AzureCloud 
```

I've changed the names but basically I connect and my Context is SubA.  I use Set-AzContext to set my Context to SubC.  I disconnect.  I reconnect, and my context is SubA again.

If I can specify a specific default subscription to connect to, at least I'd like to understand why SubA is the default that I connect to, if it's some property of the subscription that I have control over I can use that information to define or modify my subscriptions appropriately.

**Comment by ToMakeSense** [comment]
@FISHMANPET  Try to get it via **Get-AzContextAutosaveSetting**
```
PS C:\> Get-AzContextAutosaveSetting


Mode             : CurrentUser
ContextDirectory : C:\Users\XXXX\.Azure
ContextFile      : AzureRmContext.json
CacheDirectory   : C:\Users\XXXX\.Azure
CacheFile        : TokenCache.dat
Settings         : {}
```
Update the **DefaultContextKey** in the **C:\Users\XXXX\.Azure\AzureRmContext.json**

**Comment by FISHMANPET** [comment]
@ToMakeSense That has no impact on the problem I'm seeing, it merely reflects what is the current AzContext.  When I'm connected, the DefaultContextKey is just whichever subscription is my current context, when I disconnect it goes to "Default" and then if I set that key while I'm disconnected (like, to the value it has when SubscriptionC is my current context) and then connect, it is reset to be my SubscriptionA, not SubscriptionC which I'd want to be default.

**Comment by sptramer** [comment]
Thanks for all the information here in this thread, it will be helpful! The contexts article was recently updated, but without any instructions on how to set the default subscription in a session. Hopefully there will be time for some additional updates around this issue in the near future.

**Comment by aganotra** [comment]
To set default subscription use Tenant when logging in.
 Login-AzAccount -Tenant "Teanant ID"

**Comment by FISHMANPET** [comment]
I have multiple subscriptions using the same tenant so I don't think that's true.  Also the whole reason I want to set a default is so I don't need to remember or store a GUID for when I login, so specifying any ID when connecting defeats the purpose of having a "default."

**Comment by DanielFrei64** [comment]
Is there any update to this? Every time I log into Azure it default selects one of my customer subscriptions and I really need to have this default subscription be my dev/test subscription. There has to be a way to save a default subscription and not have to select into the one I want every time I log in.

**Comment by ToMakeSense** [comment]
> Is there any update to this? Every time I log into Azure it default selects one of my customer subscriptions and I really need to have this default subscription be my dev/test subscription. There has to be a way to save a default subscription and not have to select into the one I want every time I log in.

see my comments above, it's fast and working well

**Comment by DanielFrei64** [comment]
@ToMakeSense yes, it does work and work well and I am going to use it. I was just hoping there would be a more official way to do it like they have in the portal

**Comment by SteveColegrove** [comment]
I've access many subscriptions but connect-AzAccount defaults to one I very rarely use.  I am also interested in making this work without any workarounds.

**Comment by j0rt3g4** [comment]
I solved this by just deleting the .azure content within the user's profile and asking it to connect again
connect-azAccount

**Comment by adamkadzban** [comment]
I don't see it explicitly documented anywhere, but it seems like your context is (by default) set to the alphabetically-sorted first subscription it has access to.

**Comment by BrightJames** [comment]
https://build5nines.com/azure-powershell-az-list-set-subscription/

**Comment by mikefrobbins** [comment]
> This document says "To change the default subscription used when logging in with Azure PowerShell, use Set-AzDefault." but Set-AzDefault sets the default resource group from within the current context,

The doc was inaccurate and has been updated.

> what is the way to set the default context used when signing in with Connect-AzAccount. Is it possible to actually change that default?

`Select-AzContext` not only changes your active subscription for the current session, but also persists between sessions for the current user on the same system as long as you log in periodically, otherwise the token cache could be invalidated. This however also depends on context autosave being enabled, which is the default configuration.

> And how is the default actually determined, is there some property the cmdlet is keying off of to pick the "first" subscription in a list, or is there some setting from within the Azure Portal that controls this?

Unless you've previously run `Select-AzContext`, Azure PowerShell defaults to the first subscription Azure returns.

**Comment by KeysAU** [comment]
For anyone in future who comes across this:

 Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000.
 
 Works with connect-azaccount
