### ISSUE TITLE
No coverage of Linux

### ISSUE THREAD

**Issue by jasper-zanjani** [MicrosoftDocs/azure-docs-powershell#1204]
This page does not indicate how users of the PowerShell Core snap package are to install the Az module, since PSGallery is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71ec5ae0-0434-376c-a781-da1ae031017b
* Version Independent ID: 0fed6194-5f6b-b400-7d56-a0f6552c4cff
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/azurerm/install-azurerm-ps?view=azurermps-6.13.0#feedback)
* Content Source: [docs-conceptual/azurermps-6.13.0/install-azurerm-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/install-azurerm-ps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@jasper-zanjani My install of PowerShell came with the NuGet package installed as part of it, which is what provides `Install-Module`. Can you please give some information about how you installed PowerShell on your system and the `uname -a` output, along with `lsb_release -a` if running a Debian- or Ubuntu-derived distribution?

**Comment by sptramer** [comment]
Regardless of how you install PowerShell, it comes with the NuGet package manager as part of it. Once you start a powershell session, all you need to do is follow the [installation instructions](https://docs.microsoft.com/en-us/powershell/azure/azurerm/install-azurerm-ps?view=azurermps-6.13.0#install-the-azure-powershell-module).
