### ISSUE TITLE
'Connect-AzAccount' usage conflicts with documentation

### ISSUE THREAD

**Issue by AlexImray** [MicrosoftDocs/azure-docs-powershell#1205]
The usage of 'Connect-AzAccount' in this page conflicts with its documentation.
1. 'Connect-AzAccount' no longer uses the parameter '-TenantId', it uses '-Tenant'
2. When signing-in using certificate-based authentication, 'Connect-AzAccount' prompts for '-ApplicationId', as it is a mandatory parameter, which is missing in the snippet (https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-2.6.0#certificate-based-authentication)
3. Several of the methods outside the 'Sign in interactively' section require additional user input, which makes them interactive. This is misleading, as a reader will assume methods outside the interactive section do not require user input.

https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-2.6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9b37f7-1951-c0a6-d385-609ee1a38ea0
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-2.6.0#certificate-based-authentication)
* Content Source: [docs-conceptual/azps-2.6.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.6.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Thanks for the report. The incorrect information about the `-Tenant` argument and using service principals has been fixed. The sections on `-Environment` and `-Tenant` are now clearer about how these parameters are meant to be used.
