### ISSUE TITLE
I can't get this working

### ISSUE THREAD

**Issue by Bretanark** [MicrosoftDocs/azure-docs-powershell#1220]
I can't get this working.  Here's what I've understood from above.

PS C:\WINDOWS\system32&gt; $sp = New-AzADServicePrincipal -DisplayName DatabaseEnvironmentsAutomation
PS C:\WINDOWS\system32&gt; $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret)
PS C:\WINDOWS\system32&gt; $BSTR
2043734504568

PS C:\WINDOWS\system32&gt; $UnsecureSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
PS C:\WINDOWS\system32&gt; $UnsecureSecret
b9ca90ce-ada2-4019-a8ad-dd36d33058f8

PS C:\WINDOWS\system32&gt; (Get-AzContext).Tenant.Id
a18c88d8-1ba4-4132-9ef8-b7c9cbf92347

PS C:\WINDOWS\system32&gt;  Get-AzADServicePrincipal -DisplayName DatabaseEnvironmentsAutomation
ServicePrincipalNames : {http://DatabaseEnvironmentsAutomation, a3c6b66d-68ec-4102-bfad-8555b7541c7f}
ApplicationId         : a3c6b66d-68ec-4102-bfad-8555b7541c7f
ObjectType            : ServicePrincipal
DisplayName           : DatabaseEnvironmentsAutomation
Id                    : f77017b6-d1a4-44d2-8014-6253fbee795c
Type                  :

PS C:\WINDOWS\system32&gt; Get-AzRoleAssignment -ServicePrincipalName DatabaseEnvironmentsAutomation
Get-AzRoleAssignment : Cannot find principal using the specified options

PS C:\WINDOWS\system32&gt; $credentials = Get-Credential
PS C:\WINDOWS\system32&gt; Connect-AzAccount -ServicePrincipal -Credential $credentials -Tenant a18c88d8-1ba4-4132-9ef8-b7c9cbf92347
WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile (
C:\Users\Brent.Clark\.Azure ). Please ensure that this directory has appropriate protections.
Connect-AzAccount : AADSTS700016: Application with identifier 'DatabaseEnvironmentsAutomation' was not found in the directory
'a18c88d8-1ba4-4132-9ef8-b7c9cbf92347'. This can happen if the application has not been installed by the administrator of the
tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 6d553e69-a9c1-45b5-be9e-a620b4bb0b00
Correlation ID: d2adac33-18d4-430b-b22c-4fa2f1a784f9

- Brent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd724a1-cf89-45b8-85d6-e9bb815dde0c
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.7.0#feedback)
* Content Source: [docs-conceptual/azps-2.7.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.7.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please make sure that you've correctly configured the application in your AAD tenant and have set everything up correctly. This is indicated by the error:

```
Connect-AzAccount : AADSTS700016: Application with identifier 'DatabaseEnvironmentsAutomation' was not found in the directory
'a18c88d8-1ba4-4132-9ef8-b7c9cbf92347'. This can happen if the application has not been installed by the administrator of the
tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
```

This is a strong indicator that you're using the incorrect tenant value to try and connect. For more help, please see the [active directory documentation](https://docs.microsoft.com/en-us/azure/active-directory/).

**Comment by mikefrobbins** [comment]
Notice that the service principal name includes "**http://**":
 
> PS C:\WINDOWS\system32> Get-AzADServicePrincipal -DisplayName DatabaseEnvironmentsAutomation
> ServicePrincipalNames : {**http://DatabaseEnvironmentsAutomation**, a3c6b66d-68ec-4102-bfad-8555b7541c7f}
> ApplicationId : a3c6b66d-68ec-4102-bfad-8555b7541c7f

The following line should be `Get-AzRoleAssignment -ServicePrincipalName 'http://DatabaseEnvironmentsAutomation'`
Or `Get-AzRoleAssignment -ServicePrincipalName 'a3c6b66d-68ec-4102-bfad-8555b7541c7f'`

> PS C:\WINDOWS\system32> Get-AzRoleAssignment -ServicePrincipalName DatabaseEnvironmentsAutomation
> Get-AzRoleAssignment : Cannot find principal using the specified options

Use the **ApplicationId** for the username and the value from your $UnsecureSecret variable for the password. Either of the service principal names will also work as the user name, but "**http://**" must be included if you're using this one: `http://DatabaseEnvironmentsAutomation` as it's part of the name.
 
> PS C:\WINDOWS\system32> $credentials = Get-Credential

The referenced doc has also been updated since this issue was logged to help clarify this type of issue.
