### ISSUE TITLE
Get-AzDataLakeStoreAccount returning Gen1 lakes only

### ISSUE THREAD

**Issue by Murthy582** [MicrosoftDocs/azure-docs-powershell#1221]
This issue is related to datalakestore module. When I run the following powershell command it is only returning ADLS Gen1 storage accounts, not Gen2 lakes.

```
Get-AzDataLakeStoreAccount
```
And it is no where mentioned in the documentation that it only works with Gen1 lake.
https://docs.microsoft.com/en-us/powershell/module/az.datalakestore/get-azdatalakestoreaccount?view=azps-2.7.0

**Comment by sptramer** [comment]
Sorry, but this repo is for documentation only. This sounds like a product bug, so [please file a report with engineering](https://github.com/Azure/azure-powershell/issues/new/choose).

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Murthy582 For Azure Data Lake Gen2, the [Get-AzStorageAccount](https://docs.microsoft.com/en-us/powershell/module/az.storage/get-azstorageaccount?view=azps-2.7.0) cmdlet gets a specified Storage account or all of the Storage accounts in a resource group or the subscription.

Hope this helps

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Murthy582 **Get-AzStorageAccount** cmdlet returns blob storage accounts and adls gen2 accounts.
**Get-AzDataLakeStoreAccount** cmdlet returns adls gen1 accounts.

Hope this helps.

**Comment by Murthy582** [comment]
Got it, Thank you. I can see ADLS Gen2 accounts with Get-AzStorageAccount command.
I'm trying to setup ACLs using PowerShell cmdlet. **Is there any powershell command to get/set ACLs of a file/folder in ADLS Gen2 storage account?**
