### ISSUE TITLE
Update to include details on offline installation methods

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/azure-docs-powershell#1224]
As this doc is about installing the Azure PowerShell module it should also include details on how to install the module in offline environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fc79a0-d843-1c7c-1612-948e3d912290
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.7.0)
* Content Source: [docs-conceptual/azps-2.7.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.7.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@kilasuit Thanks for raising this question and submitting the PR. Before I can address either of them, what is your use case for installing Azure PowerShell in an offline environment, since it requires network connectivity to perform any actions?

**Comment by kilasuit** [comment]
@sptramer an offline install may just mean not having access to the PowerShell Gallery or GitHub to install from and is a common requirement for organisations that want to ensure enhanced endpoint security, by allowing install from internalised sources, including via SCCM etc

**Comment by sptramer** [comment]
Great, I understand where you're coming from. I'll leave this open while I review your PR.

**Comment by sptramer** [comment]
Resolved by #1239. Should be published no later than Wednesday Oct. 24.
