### ISSUE TITLE
Connect-AzAccount returns error 

### ISSUE THREAD

**Issue by qhdevon43** [MicrosoftDocs/azure-docs-powershell#1227]
Currently getting an error while on new windows 10 1903 build 18362.388 running the Connect-AzAccount in powershell. Version is 2.7.0  ( powershell and .net 4.8 are installed)

`Connect-AzAccount : The 'Connect-AzAccount' command was found in the module 'Az.Accounts', but the module could not be
loaded. For more information, run 'Import-Module Az.Accounts'.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule`

**Comment by sptramer** [comment]
This could be an issue with your PowerShell environment. Try running `Import-Module Az` before running any Azure PowerShell cmdlets (see the note under [Install - Sign In](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.7.0#sign-in)). If you still experience problems, this is likely a product bug and you will need to [file an issue with engineering](https://github.com/Azure/azure-powershell/issues/new/choose).
