### ISSUE TITLE
Set-AzureRmVMDiskEncryptionExtension Linux -VolumeType options

### ISSUE THREAD

**Issue by YuichiTorigoe** [MicrosoftDocs/azure-docs-powershell#1236]
I checked the following entry on this page.

** Set-AzureRmVMDiskEncryptionExtension
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmdiskencryptionextension?view=azurermps-6.13.0
----
-VolumeType
Specifies the type of virtual machine volumes to perform the encryption operation. Allowed values for virtual machines that run the Windows operating system are as follows: All, OS, and Data. 
**The allowed values for Linux virtual machines are as follows: Data only.**
---

But We can use the other options(ALL,OS) for VolumeType on Linux VM

Isn't this an error in the manual?

Best Regards

**Comment by BharathNimmala-MSFT** [comment]
@YuichiTorigoe Thank you again for your question. 

[Azure PowerShell – Cross-platform “Az” module replacing “AzureRM”](https://azure.microsoft.com/en-us/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/)

We would recommend you to start migrating from AzureRM to Az, unless there is a business requirement not allowing you to migrate. Related Az cmdlets ([Set-AzVMDiskEncryptionExtension](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmdiskencryptionextension?view=azps-2.8.0#description)) and [documentation ](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmdiskencryptionextension?view=azps-2.8.0#description) for the same is up to date. Please refer to below details on volumetype for Linux Virtual machines.  

Linux: The VolumeType parameter is required when encrypting Linux virtual machines, and must be set to a value ("Os", "Data", or "All") supported by the Linux distribution.

Hope this information helps. Please revert back if you have any further queries.

**Comment by YuichiTorigoe** [comment]
I checked this document.

But I think should be update this description on Set-AzureRmVMDiskEncryptionExtension page

**Comment by BharathNimmala-MSFT** [comment]
@YuichiTorigoe  Appreciate your feedback. Would recommended to leverage the [Set-AzVMDiskEncryptionExtension](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmdiskencryptionextension?view=azps-2.8.0#description) documentation which is up to date. That being said we have already requested our internal product team to update Set-AzureRmVMDiskEncryptionExtension documentation as well, @dcaro is helping to track this backlog item.
