### ISSUE TITLE
Neither Instruction Works

### ISSUE THREAD

**Issue by dragongeek** [MicrosoftDocs/azure-docs-powershell#1237]
I have tried all three uninstall methods above and none of them work. The Uninstall-AzureRm and Uninstall-AllModules neither exist, and the only Azure product in my Apps is Microsoft Azure Storage Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a9a689-a780-0695-b7c3-911314eb0e7a
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-2.8.0#feedback)
* Content Source: [docs-conceptual/azps-2.8.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@dragongeek Thank you for your question, we will further look into this and get back to you shortly.

**Comment by BharathNimmala-MSFT** [comment]
@dragongeek Thanks for reaching out, can you please help share if you are seeing any errors while running the uninstall commands. And also, it might be good to check what modules you have currently installed on your machine. `Get-Module -ListAvailable` and see what should be uninstalled. You can also verify if its a windows machine. Please navigate to  `C:\Program Files\WindowsPowerShell\Modules`  path to see if there modules installed or not.

**Comment by BharathNimmala-MSFT** [comment]
@dragongeek We will go ahead and close this issue for now, however if above steps are not helping to resolve your issue please feel free to tag us in your reply and will be happy to continue the conversation. Thank you.
