### ISSUE TITLE
SP with default Contributor?!

### ISSUE THREAD

**Issue by Chai-NED** [MicrosoftDocs/azure-docs-powershell#1241]
"The default role for a service principal is Contributor. This role has full permissions to read and write to an Azure account" Does this mean a newly created service principal has the Contributor at the subscription level? How do we then prevent someone with Service Principal from a malicious use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a975e2-e8d1-f0f3-80ec-307b6274ab74
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.8.0#feedback)
* Content Source: [docs-conceptual/azps-2.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by Chai-NED** [comment]
Nevermind. I guess you could take the Contributor right away and assign just Reader. I would expect the default behavior to be the other way around.

**Comment by TravisCragg-MSFT** [comment]
@Chai-NED We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
