### ISSUE TITLE
This is a mess - unable to uninstall AzureRM

### ISSUE THREAD

**Issue by John-Blair** [MicrosoftDocs/azure-docs-powershell#1244]
PS C:\Users\John Blur&gt; Uninstall-AzureRm
WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running Pow
erShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none o
f your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
WARNING: AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment y
ou control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both
 Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide.
WARNING: AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment y
ou control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both
 Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide.
Uninstall-AzureRm : The 'Uninstall-AzureRm' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
At line:1 char:1
+ Uninstall-AzureRm
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Uninstall-AzureRm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f3dff7-65ab-09f2-713e-4e7f11544c9a
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-2.8.0)
* Content Source: [docs-conceptual/azps-2.8.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thank you for your feedback, we will look into this and get back to you at the earliest.

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Apologies for delayed response on this, can you please help confirm if you are not able to consume[ Unistall-AzureRm](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-2.8.0#uninstall-from-powershell) command , however navigate through the next steps listed in the doc to unistall the AzureRM modules.

If you can't successfully run the Uninstall-AzureRM command, use the Uninstall-AllModules script provided in this article with the following invocation:

`$versions = (Get-InstalledModule AzureRM -AllVersions | Select-Object Version)
$versions | foreach { Uninstall-AllModules -TargetModule AzureRM -Version ($_.Version) -Force }`

Please revert back if you have any further queries. Thanks

**Comment by BharathNimmala-MSFT** [comment]
@John-Blair Thanks again for reaching out to us. Hope the above information on this thread helps you to uninstall AzureRM. We will go ahead and close this issue for now, however if you have any further queries please feel free to tag us in your reply and will be happy to continue the conversation forward.  Thank you.

**Comment by Mexicoder** [comment]
I was only able to Uninstall AzureRM by using what i found here [here](https://stackoverflow.com/a/56688847/5919289) 
specifically, I ran this: 
`workflow Uninstall-AzureModules
{
    $Modules = (Get-Module -ListAvailable AzureR*).Name |Get-Unique
    Foreach -parallel ($Module in $Modules)
    { 
        Write-Output ("Uninstalling: $Module")
        Uninstall-Module $Module -Force
    }
}
Uninstall-AzureModules
Uninstall-AzureModules   #second invocation to truly remove everything`

There was no other way I could find to do this. 
Uninstall-AzureRm just didn't work at all even after installing a newer version of AzureRM

**Comment by Durantye** [comment]
@Mexicoder You're a gift sent from heaven with this bit of info
