### ISSUE TITLE
Update the name to check in 'program listing' under 'Uninstall Azure PowerShell MSI' sectoin

### ISSUE THREAD

**Issue by vktibrewal** [MicrosoftDocs/azure-docs-powershell#1247]
The name can be 'Microsoft Azure PowerShell - &lt;month&gt;' as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f51d29-7fe8-3749-1e4e-d7a67c76435a
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.0.0#feedback)
* Content Source: [docs-conceptual/azps-3.0.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.0.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@vktibrewal Thanks for your feedback, will further evaluate and get back to you at the earliest.

**Comment by BharathNimmala-MSFT** [comment]
@vktibrewal Thanks again for your feedback. PR has been raised to update the document , once approved and reviewed it would reflect the document accordingly. 

Will go ahead and close the issue for now, if you have any queries please tag us in your reply and will be happy to continue the conversation. Thanks
