### ISSUE TITLE
Typo or incorrect format in the latest release notes

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/azure-docs-powershell#1249]
## 2.8.0 - October 2019

**Incorrect format and typo**
![image](https://user-images.githubusercontent.com/6244148/68638716-5aa30b00-053d-11ea-87ea-c95c7f750dfd.png)

### I think it should be:
 - New cmdlets added:
      - New-AzIpsecTrafficSelectorPolicy
 - Cmdlets updated with optional parameter -TrafficSelectorPolicies
      - New-AzVirtualNetworkGatewayConnection
      - Set-AzVirtualNetworkGatewayConnection

**Tiny typo, extra space  before the dot**
![image](https://user-images.githubusercontent.com/6244148/68637893-eb2c1c00-053a-11ea-8e8f-77f90181ebc8.png)

**Bad statement organization**
![image](https://user-images.githubusercontent.com/6244148/68639506-bc647480-053f-11ea-8234-5009d0b9f733.png)

### I think it should be like:
Set-AzApiManagementApi - Added support for Updating Api into ApiVersionSet, fix issue https://github.com/Azure/azure-powershell/issues/10068

![image](https://user-images.githubusercontent.com/6244148/68641618-5cbd9780-0546-11ea-8a5f-4782ebb8473a.png)

### I think it should be like:
New action group receivers added for **New-AzActionGroupReceiver**: -ItsmReceiver -VoiceReceiver -ArmRoleReceiver -AzureFunctionReceiver -LogicAppReceiver -AutomationRunbookReceiver -AzureAppPushReceiver

## 2.7.0 - September 2019

**Repeated description**
Fixing issue where webapp Tags were getting deleted when migrating App to new ASP~~where webapp Tags were getting deleted when migrating App to new ASP~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63cb1e5-872b-e793-b6a5-0425447d9f1a
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [Azure PowerShell release notes](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-2.8.0#280---october-2019)
* Content Source: [docs-conceptual/azps-2.8.0/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/release-notes-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by femsulu** [comment]
Thanks for catching these issues. PR #1254  has been created to address the doc bugs.

Once reviewed and approved, these fixes will go live shortly after. 
Thanks again for your continued contribution. 
We will now close this request.

Cheers.

**Comment by ToMakeSense** [comment]
@femsulu  sorry to bother, there still typo in #1254, I left comments in line.

**Comment by femsulu** [comment]
Thanks for the update, looking into this and will resolve as appropriate.
