### ISSUE TITLE
Remove-AzRoleAssignment -ApplicationID ; No Parameter

### ISSUE THREAD

**Issue by LukePWilkins** [MicrosoftDocs/azure-docs-powershell#1253]
Remove-AzRoleAssignment : A parameter cannot be found that matches parameter name 'ApplicationId'.

No applicationID as specified in the section "Manage service principal roles" on this page.
Specify the ObjectID instead of the SPN to target it and remove the particular role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849d66dd-b611-d87f-ffb4-b4ef4baf0d1c
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.0.0)
* Content Source: [docs-conceptual/azps-3.0.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.0.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by AjayKumar-MSFT** [comment]
@LukePWilkins, Thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by BharathNimmala-MSFT** [comment]
@LukePWilkins Thanks again for bringing this to our attention, I am working with our Product team to get more clarity on current supportability and will adjust the documentation accordingly. 

For now, as a work around please check if you can still use below format with the appid you have
`Remove-AzRoleAssignment -ServicePrincipalName xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx -RoleDefinitionName "Reader"`

Hope the above information helps and will keep this thread updated as i hear more from our product team on the current supportability. Thank you.

**Comment by BharathNimmala-MSFT** [comment]
@LukePWilkins Assigning this to our Product PM @dcaro  to further evaluate the command let. Thanks

**Comment by kkazala** [comment]
@BharathNimmala-MSFT 
should be
Remove-AzRoleAssignment -ObjectId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx -RoleDefinitionName "Reader"

rgds

**Comment by salbeck** [comment]
when creating a SP using Powershell, a role is only assigned if -Scope and/or -Role is specified in New-AzADServicePrincipal. If Role and Scope are omitted, no role is assigned. This confused me at first since I expected at least a subscription-wide role-assignment. Compare with available help for New-AzADServicePrincipal that details when and how a role is assigned
