### ISSUE TITLE
Which way is correct?

### ISSUE THREAD

**Issue by juyama** [MicrosoftDocs/azure-docs-powershell#1256]
The Update-Module command is noted that it doesn't work correctly in this page. However, the command is recommended at GitHub page. Which way we should use to update? 
https://github.com/Azure/azure-powershell/releases/tag/v3.0.0-November2019 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f877dd21-bfd3-34e0-7cb1-814ce976caa6
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.0.0#update-the-azure-powershell-module)
* Content Source: [docs-conceptual/azps-3.0.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.0.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by juyama** [comment]
add image
![image](https://user-images.githubusercontent.com/46222416/69553109-ed828180-0fe2-11ea-9a3b-62e17ec7778c.png)

**Comment by mike-urnun-msft** [comment]
@juyama Thank you for your feedback! We will review and update as appropriate.

**Comment by SamaraSoucy-MSFT** [comment]
@juyama I will reach out to the product team to see if I can confirm which solution is correct. In the short term I think reinstalling will be the safer option.

**Comment by jnicklous** [comment]
Which version of the Azure cmdlets contain the Az.Reservations module included?  I've downloaded and installed version 3.2 and the Az.Reservations module isn't included as indicated in the reference section of this page

**Comment by marckassay** [comment]
@jnicklous, Az.Reservations is currently in preview, as it has a SemVer value of 0.8.1. So they're not including it with the super module, Az, until its major version digit becomes 1. I also found this not to be clear as I mentioned [here](https://github.com/Azure/azure-powershell/issues/10656#issuecomment-562170291).
