### ISSUE TITLE
Pages of Az.DataBoxEdge cmdlets are under Az.DataBox

### ISSUE THREAD

**Issue by dingmeng-xue** [MicrosoftDocs/azure-docs-powershell#1257]
Pages of Az.DataBoxEdge cmdlets are incorrectly under Az.DataBox.

In addition, there is no DataBoxEdge element under reference.

![issuepage](https://user-images.githubusercontent.com/56333063/69600207-c65f9a80-104a-11ea-92a3-345a01d8f9bc.PNG)

**Comment by AmanGarg-MSFT** [comment]
@dingmeng-xue Thank you for your feedback! We will review and update as appropriate.

**Comment by dcaro** [comment]
@AmanGarg-MSFT this has been fixed with PR #1262

**Comment by kobulloc-MSFT** [comment]
@dingmeng-xue We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
