### ISSUE TITLE
Link does not point to latest

### ISSUE THREAD

**Issue by bgklein** [MicrosoftDocs/azure-docs-powershell#1260]
`Install with PowerShellGet`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c45e278-3e22-b218-24fa-6652560b305b
* Version Independent ID: eed6d40d-0b69-a61e-fd86-aaea6360392b
* Content: [Install Azure PowerShell with an MSI](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-2.8.0#feedback)
* Content Source: [docs-conceptual/azps-2.8.0/install-az-ps-msi.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/install-az-ps-msi.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by mike-urnun-msft** [comment]
@bgklein Thank you for your feedback! We will review and update as appropriate.

**Comment by SamaraSoucy-MSFT** [comment]
Hi @bgklein,

The version is staying consistent between the two docs.

The version you linked to is the doc for the 2.8.0 version of Azure powershell and it links to the 2.8.0 version of the powershell get doc. If you change to the 3.1.0 version of this doc, it links to the 3.1.0 version of powershell get.

![image](https://user-images.githubusercontent.com/47195189/69989222-2950a600-1511-11ea-9676-59568ace679b.png)

I'm going to go ahead and close this thread. Please tag me if you have a followup question.
