### ISSUE TITLE
Linking for reference

### ISSUE THREAD

**Issue by vinyar** [MicrosoftDocs/azure-docs-powershell#1265]
Select-azContext doesn't seem to work as described/expected.
Linking relevant issue to save people time troubleshooting - https://github.com/Azure/azure-powershell/issues/9448

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5df2cb-ddeb-b667-96bd-ce76709b8601
* Version Independent ID: f641b6fa-c346-ad1d-65a6-793a4bedcbdf
* Content: [Azure contexts and sign-in credentials](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-3.1.0)
* Content Source: [docs-conceptual/azps-3.1.0/context-persistence.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.1.0/context-persistence.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@vinyar Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@vinyar Thank you for bringing this to our attention.  I'm not sure what we can do for this from a documentation standpoint, but I will assign this to the document author so they can review the documentation accordingly.

**Comment by huypub** [comment]
@MarileeTurscak-MSFT  
I am not responsible for this kind of PR merge. Please assign it back.

**Comment by mikefrobbins** [comment]
Thanks for linking the issue. Closing this issue since it definitely appears to be a code issue and not a documentation bug.
