### ISSUE TITLE
Managed identity

### ISSUE THREAD

**Issue by aelij** [MicrosoftDocs/azure-docs-powershell#1266]
Please add the `-Identity` option instead of referencing the Managed Identity API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3883f9-a079-8ecc-45fa-0fed88b50aeb
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.1.0)
* Content Source: [docs-conceptual/azps-3.1.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.1.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@aelij, Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by dcaro** [comment]
@aelij this is a great suggestion. We have the example in our reference docs but it is actually good to have it here.

**Comment by MonikaReddy-MSFT** [comment]
@aelij , Thanks again for bringing this to our attention. We have updated the Doc and We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue..
