### ISSUE TITLE
New-AzureRmADServicePrincipal : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by TestO2015** [MicrosoftDocs/azure-docs-powershell#1270]
I'm trying to create a Service Principal in Azure AD however the Powershell command throws an error:

> New-AzureRmADServicePrincipal : Object reference not set to an instance of an object

Here's the commands I ran:

> Connect-AzureRmAccount  
> New-AzureRmADServicePrincipal -ApplicationId 309ff276-e6b5-4676-aad2-b77f4c9d9e12

**Comment by ManojReddy-MSFT** [comment]
@TestO2015 We are looking into this and will get back to you shortly.

**Comment by souravmishra-msft** [comment]
@TestO2015, I would suggest using the new Az powershell module here. You can find the details about this module [here](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.2.0).

Once you install the Az PS module, try running these commands:
```
Connect-AzAccount 

#Create a secret for the application registration
$SecureStringPassword = ConvertTo-SecureString -String "password" -AsPlainText -Force

#This commands creates an App Registration in AAD with a secret value
$adApp = New-AzADApplication -DisplayName "NewApplication" -HomePage "http://www.microsoft.com" -IdentifierUris "http://NewApplication" -Password $SecureStringPassword

#This command creates a Service Principal for the corresponding App Registration
New-AzADServicePrincipal -ApplicationId $adApp.ApplicationId 

```
Check if this helps you. The AzureRMAD cmdlets are old and contains some bugs. Do check the following section in this [article](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.2.0#upgrade-to-az)  

This would also help you in how you can upgrade to the Az Module and also how you can migrate your existing scripts from AzureRMAD modules to Az module.

Hope this helps. Please feel free to let us know if any more queries around this.

**Comment by shashishailaj** [comment]
@TestO2015 We will close this issue now . In case you have any further queries on this , please feel free to tag us to your reply or you can open a issue on our New forum [Microsoft QnA](https://docs.microsoft.com/answers/index.html)
