### ISSUE TITLE
Azure PS Modules not compatible with Windows Powershell Core

### ISSUE THREAD

**Issue by shogerr** [MicrosoftDocs/azure-docs-powershell#1271]
Using Powershell 7 Core on Windows 10: 

```
PS > Connect-AzAccount
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
Connect-AzAccount: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```
```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Related issue: https://github.com/PowerShell/PowerShell/issues/11070

It seems 0 of the modules for Azure work with the Powershell Core. I don't know why the documentation says it will.

It would be pretty interesting if this worked in Linux, but not Windows.

**Update**
This cmdlet works perfectly fine if you install powershell in WSL (Debian in this case). That was kind of unexpected.
```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I guess I'll install yet another version of PS and try it with 6.

**Double Update**
Seems to work with PS6.

**Comment by shogerr** [comment]
Adjusting title: apparently MS dumps all pages of documents to the same issue tracker...

**Comment by kobulloc-MSFT** [comment]
@shogerr Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
Hi @shogerr!

Can you please provide a link to the document that you are having trouble with?

**Comment by shogerr** [comment]
@kobulloc-MSFT 
You're just as well off in finding it as I am at this point. Finding the same MS Doc twice for the correct version of .NET/Windows/ASP/MSAL is like shooting tardigrades in a barrel. I don't have the browsing history either. Heck, after traversing so many doc pages from the site to find what I needed, I can't even remember what topic the page covered.

I honestly wish I could tell, you. I would have noted it, but the UX flow on the page made it seem like if you used the GitHub box at the bottom of the doc page, I would be reporting issues related to the page I was currently on. Perhaps a new issue needs to be opened for this behavior as well.

So sorry! It should be related to authing and contain a reference to Connect-AzAccount. Doesn't MS own my machine anyway? I can give you the AzureAD so you can whip out the spying, i mean telemetry tools, and go ahead and tell me what I was up to.

**Comment by kobulloc-MSFT** [comment]
@shogerr Usually that information is populated automatically, but there are rare instances where we have to retrieve that information manually.  I completely understand what it's like to lose your place while following a breadcrumb trail.  Thank you for the heads up!  We'll take a look at this.

**Comment by cameronove** [comment]
hmm ... this is very disappointing - I "heard" @SteveL-MSFT when he indicated that PowerShell 7 was meant to get more Windows admins to upgrade to latest PWSH.   I would love to be running PowerShell 7 daily, but I can't use it full time until Exchange and Azure  cmdlets are available.  That's 80% of what I do.  Will this be ready by January?

**Comment by SamaraSoucy-MSFT** [comment]
@shogerr and @cameronove I'm going to close this issue as it isn't a docs problem. However, I am working to find out if there is any information I can share with you on when we will support PS7 for the Azure cmdlets and I will follow up when I have something to share. You can also ask the question yourself on the product repo: https://github.com/Azure/azure-powershell/

The az module does work with PS7 so you may wish to take this as an opportunity to start the migration as that is what we will be supporting in the long term. the `Enable-AzureRmAlias` command will allow you to use your existing scripts with the new module with a few exceptions. You can read more on the migration process here: https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-3.2.0

**Comment by SamaraSoucy-MSFT** [comment]
Heard back from the product team. The `az` module is the correct solution to this issue, using `Enable-AzureRmAlias` to continue using your existing scripts. The AzureRM module is deprecated and will not be updated to be compatible with Powershell 7
