### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by anoobbacker** [MicrosoftDocs/azure-docs-powershell#1274]
Under the section https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0#learn-powershell-basics

Installing PowerShell is pointing to a link which is giving 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 86324274-e59e-d272-0554-f51a63e7ec5c
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0#feedback)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MarileeTurscak-MSFT** [comment]
@anoobbacker 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SamaraSoucy-MSFT** [comment]
I've put in a PR to fix this issue. It will go live once the doc author has approved the PR.
