### ISSUE TITLE
No Powershell Command-let  for AzureBatch to sync Keys for the Attached Storage Account

### ISSUE THREAD

**Issue by dhruvmodi13** [MicrosoftDocs/azure-docs-powershell#1276]
Could not find any PowerShell commandlet for the SyncKeys option which syncs the Azure storage accounts keys in Batch.

https://docs.microsoft.com/en-us/rest/api/batchmanagement/batchaccount/synchronizeautostoragekeys#code-try-0

https://docs.microsoft.com/en-us/cli/azure/batch/account/autostorage-keys?view=azure-cli-latest

Rest API call and CLI commands are present.
Was wondering why PS commands are not added in the AzureRm.Batch module.

Need this for Auto Secret Rotation for storage account.

**Comment by MarileeTurscak-MSFT** [comment]
@dhruvmodi13 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mikefrobbins** [comment]
@SamaraSoucy-MSFT Could you move this issue to the [github.com/Azure/azure-powershell](https://github.com/Azure/azure-powershell) repo since it's a product question and not a documentation issue? Thank You!

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins - I have moved the issue to Azure Powershell Repo. Thanks for providing your inputs.
@dhruvmodi13 - Thanks again for bringing this to our attention. I have opened a new issue in Powershell Repo. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue
