### ISSUE TITLE
DomainNameLabel doesn't exist on new Public IP resources

### ISSUE THREAD

**Issue by fabrizob** [MicrosoftDocs/azure-docs-powershell#1279]
The following commands only work when DomainNameLabel it's already present so you can change it:
$publicIp = Get-AzureRmPublicIpAddress -Name $publicIpName -ResourceGroupName $rgName
$publicIp.DnsSettings.DomainNameLabel = "newdnsprefix"

When the public ip has been created without the DomainNameLabel, it cannot be set.
![Annotation 2019-12-14 073416](https://user-images.githubusercontent.com/41018953/70844617-2f655180-1e44-11ea-843b-111ba0bb9d10.png)

**Comment by MarileeTurscak-MSFT** [comment]
@fabrizob 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
@fabrizob please provide the link to the article that you're referencing.

**Comment by fabrizob** [comment]
> @fabrizob please provide the link to the article that you're referencing.

https://docs.microsoft.com/en-us/powershell/module/azurerm.network/set-azurermpublicipaddress?view=azurermps-6.13.0
![Annotation 2019-12-14 084804](https://user-images.githubusercontent.com/41018953/70845396-79ebcb80-1e4e-11ea-917c-05b8d29e002d.png)

**Comment by MonikaReddy-MSFT** [comment]
@fabrizob , 

Thanks for reaching out to us. 
This command `publicIp.DnsSettingsDomainNameLabel = "newdnsprefix"` should work since this is how it works in the new cmdlet. 

I hope this information helps. 
Please feel free to reach back out if there are any further questions regarding this matter.

**Comment by MonikaReddy-MSFT** [comment]
@fabrizob, 
Since we haven't heard back from you, hoping that the issue is resolved for you. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
