### ISSUE TITLE
What about AzureAD?

### ISSUE THREAD

**Issue by marckassay** [MicrosoftDocs/azure-docs-powershell#1287]
The Az module is published with an owner name of 'azure-sdk', while AzureAD has an owner name of 'AzureADPowerShell'. And both are published with an author name of 'Microsoft Corporation'. With them having an owner name difference, I assume that is why 'AzureAD' is not a "sub" module of Az and continues to keep the 'Azure' noun prefix for its commands. But having them published by the same author, why have this inconsistency?

At any rate, it might be best to mention about AzureAD being excluded from Az module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f3dff7-65ab-09f2-713e-4e7f11544c9a
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-2.8.0)
* Content Source: [docs-conceptual/azps-2.8.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.8.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@marckassay Thank you for the feedback.  We'll look into this and try to get you a better answer as to why that is.

**Comment by marckassay** [comment]
It looks like AzureAD is for *Windows* PowerShell only, correct?

**Comment by ken-hk** [comment]
Some information:

[Az (Azure PowerShell)](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az) is a general management module for Azure resources, like the virtual machines and SQL databases. [AzureAD (Azure Active Directory PowerShell for Graph)](https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview), aka [Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/getting-started-with-office-365-powershell), manages Azure Active Directory (Office 365) users, groups and licenses. AzureAD is listed in the "**Other Azure PowerShell modules**" section in [Azure PowerShell documentation](https://docs.microsoft.com/en-us/powershell/azure/) with Azure Service Fabric and Azure ElasticDB.

According to the official documents, while Az is based on .NET standard which is cross-platform, AzureAD still [requires Windows](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell#what-do-you-need-to-know-before-you-begin).

It is worth mentioning that the previous versions of Az and AzureAD are [AzureRM](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview) and [MSOnline](https://docs.microsoft.com/en-us/powershell/module/msonline/), respectively.

**Comment by marckassay** [comment]
@ken-hk, thanks! That resolved some uncertainties that I had.

I think that info you provided would be beneficial to include in the doc page.

**Comment by PaulBendall** [comment]
Basically Microsoft have created a mess. The Az module is NOT feature comparable with AzureRM as is stated on a number of MS doc pages. If you want to do a number of things with regard to Azure AD then you have to use AzureRM (for example - https://github.com/Azure/azure-powershell/issues/9074) but of course the two can't co-exist in the same version of PowerShell and AzureRM will be out of support by December 2020.

The various product teams need to sort this out

**Comment by rpilot** [comment]
While Az module is cross-platform, Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/manage-users-and-groups-in-aad/5-manage-aad-roles) still uses AzureAD in their scripting examples...
