### ISSUE TITLE
Link in "Note" section redirects to same page

### ISSUE THREAD

**Issue by srs81** [MicrosoftDocs/azure-docs-powershell#1288]
In the "Note" section at the top of the page, there is this paragraph:

> Azure Stack users should continue to use AzureRM for now. The latest version of AzureRM which supports Azure Stack is [AzureRM 2.3.0](https://docs.microsoft.com/en-us/powershell/azure/azurerm?view=azurermps-2.3.0).

However, clicking on the link to [AzureRM 2.3.0](https://docs.microsoft.com/en-us/powershell/azure/azurerm?view=azurermps-2.3.0) doesn't work, it redirects to the same page with this error message showing up at the top:

>  The requested page is not available for Azure RM PowerShell 2.3.0. You have been redirected to the newest product version this page is available for.

![image](https://user-images.githubusercontent.com/1521574/71216207-c2502280-226e-11ea-86b9-141227996f30.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 86324274-e59e-d272-0554-f51a63e7ec5c
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@srs81 Thank you for bringing this to our attention!

**Comment by mikefrobbins** [comment]
The referenced page was previously updated and the section with the link problem no longer exists.
