### ISSUE TITLE
Its not clear how New-AzADSpCredential supports user defined credentials

### ISSUE THREAD

**Issue by unnity** [MicrosoftDocs/azure-docs-powershell#1292]
It says "use New-AzADSpCredential to add a new credential. This cmdlet takes the same credential arguments and types as New-AzADServicePrincipal". But does not actually support using user defined credentials when resetting the password 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 437f522d-bae8-c178-202b-bee86ceb9983
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.2.0#feedback)
* Content Source: [docs-conceptual/azps-3.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.2.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by mike-urnun-msft** [comment]
@unnity Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.
