### ISSUE TITLE
Example of cmdlet Restore-AzsBackup incorrect

### ISSUE THREAD

**Issue by daozha** [MicrosoftDocs/azure-docs-powershell#1299]
On this page, the example is: Restore-AzsBackup -**Backup** xxx

While the correct parameter name should be "**$Name**" instead of "**$Backup**".

From the module content, the example is also with the correct parameter name:
![image](https://user-images.githubusercontent.com/38281880/71946566-2bd7a700-3205-11ea-8220-007bb0b65b45.png)
I thought the doc is generated automatically from those cmdlet files, wonder why we have this content error here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c486efe5-bc9b-aa6c-fcb1-41535855b4d3
* Version Independent ID: 1bb80930-5b8d-3d45-82ea-9fe4690e84b2
* Content: [Restore-AzsBackup (Azs.Backup.Admin)](https://docs.microsoft.com/en-us/powershell/module/azs.backup.admin/restore-azsbackup?view=azurestackps-1.7.2&viewFallbackFrom=azurestackps-1.8.0#feedback)
* Content Source: [azurestackps-1.7.2/Azs.Backup.Admin/Restore-AzsBackup.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azurestackps-1.7.2/Azs.Backup.Admin/Restore-AzsBackup.md)
* Service: **azure-powershell**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by kobulloc-MSFT** [comment]
@daozha Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by mattbriggs** [comment]
@daozha Thanks for your feedback. The content is generated automatically from the cmdlet. However the published docs are not synced. And so it appears that there was an update in the cmdlet that is not reflected in the docs. It would be most expedient at this point to manually update the markdown. If we should ever generate the 1.7.2 ref, the current state where it is correct would be reflected. Thanks, Matt #in-progress

**Comment by mattbriggs** [comment]
https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1395

#sign-off

**Comment by kobulloc-MSFT** [comment]
@daozha We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
