### ISSUE TITLE
Set-AzureRmResource -ResourceId $r.ResourceId  -Tag $r.Tags -Force

### ISSUE THREAD

**Issue by ausafonly** [MicrosoftDocs/azure-docs-powershell#1300]
Set-AzureRmResource -ResourceId $r.ResourceId  -Tag $r.Tags -Force
This command never finish and keep running for hours

is there anything I am doing or missing

**Comment by himanshusinha-msft** [comment]
@ausafonly Thanks for reaching out to us , but at this time it does not look like you are referring to a document but to a specific scenario . If that's the case we request you to please post your question on MSDN and other forums , we have our engineers and others who are monitoring them and will be happy to help .
If you have a document which you are following and if you think it needs  an update , please let us know about that here .

**Comment by himanshusinha-msft** [comment]
We are closing this issue as we have not heard back from you , you can always re-open the issue if you think that appropriate .
