### ISSUE TITLE
Please fix below typos 

### ISSUE THREAD

**Issue by dingmeng-xue** [MicrosoftDocs/azure-docs-powershell#1301]
There are some typos on release notes
* Az.Cdn: “response deatil in New-AzCdnEndpoint”
* Az.DataBoxEdge: Edge Stroage Container (all the lines)
* Az.Network : “Microsoft.Azure.Management.Sql from 1.36-preivew to 1.37-preivew”
* Az.RecoveryServices: “stomer managed leys for Azure”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56f7e0a4-ca59-56aa-b60e-0de45a3d9211
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [Azure PowerShell release notes](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-3.3.0)
* Content Source: [docs-conceptual/azps-3.3.0/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.3.0/release-notes-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by SamaraSoucy-MSFT** [comment]
Hi @dingmeng-xue! Thank you for bringing this to our attention.

**Comment by Minewiskan** [comment]
@dingmeng-xue This was fixed in azure-docs-powershell master, and master has been merged with live.
