### ISSUE TITLE
missing cmdlet

### ISSUE THREAD

**Issue by tameek** [MicrosoftDocs/azure-docs-powershell#1313]
I'm getting an error when I run Connect-AzAccount.

$ pwsh
PowerShell 6.2.4

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

&gt; Connect-AzAccount
Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0a93ea-bbf6-e5ac-1c29-d67c8500ea58
* Version Independent ID: cc8aa9be-2707-4ef6-e4d9-35498b837289
* Content: [Get started with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azps-3.3.0#feedback)
* Content Source: [docs-conceptual/azps-3.3.0/get-started-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.3.0/get-started-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by Mike-Ubezzi-MSFT** [comment]
@tameek Thank you for bringing this to our attention. I cannot find any reference as to whether there is an equivalent for `Connect-AzAccount` for v.6.x., and the documentation does not seem to reflect the latest PowerShell core release.

![Screenshot (642)](https://user-images.githubusercontent.com/37126106/73561794-859b4d80-440e-11ea-8fdd-9f3ac1f0cd70.png)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@tameek Thanks for reaching out! From the logs posted above, it seems like the **Azure Powershell** module isn't installed on your machine. To verify the same, please run this command to check if you see **Az** or **Az.Accounts** in the list of installed modules:

`Get-Module -ListAvailable`

If not, then please install it following the instructions provided [here](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.3.0).

Once that is done, you should be able to use the `Connect-AzAccount` cmdlet. Please give it a try and let me know if you still see issues.

Hope this helps!

**Comment by BhargaviAnnadevara-MSFT** [comment]
@tameek Any luck here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@tameek We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
