### ISSUE TITLE
A help for Invoke-AzResourceAction doesn't have any examples

### ISSUE THREAD

**Issue by alexandair** [MicrosoftDocs/azure-docs-powershell#1321]
A help for [Invoke-AzResourceAction](https://docs.microsoft.com/en-us/powershell/module/az.resources/invoke-azresourceaction?view=azps-3.5.0) doesn't have any examples.

**Comment by SamaraSoucy-MSFT** [comment]
@alexandair thank you for your feedback. I will assign this to the doc author to review.

**Comment by mikefrobbins** [comment]
Three examples have been added since this issue was logged.
