### ISSUE TITLE
Ambiguous use of service principal ID

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/azure-docs-powershell#1323]
"When using a service principal instead of a registered application, add the -ServicePrincipal argument and provide the service principal's ID as the -ApplicationId parameter's value." 

Seems a service principal has both an id and an application id. I'd suggest to explicitely write 'and provide the application ID of the service principal'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9d23ff-b2cc-f974-7f4b-2b217efbe53c
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.5.0#feedback)
* Content Source: [docs-conceptual/azps-3.5.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.5.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by BharathNimmala-MSFT** [comment]
@velden Thank you for sharing your feedback, our team will have a further look into this and get back to you at the earliest.

**Comment by SamaraSoucy-MSFT** [comment]
@velden Just to clarify on what you think is confusing, is the Object ID that you are concerned about mixing up when authenticating?

![image](https://user-images.githubusercontent.com/47195189/75277006-3d850600-57d5-11ea-82ff-b6fdc0ff8a4e.png)

**Comment by velden** [comment]
![2020-02-26 17_23_58-Select Windows PowerShell](https://user-images.githubusercontent.com/4172150/75365274-451fda00-58bd-11ea-95d0-6927d2c7ddba.png)
@SamaraSoucy-MSFT Thank you for your quick response.

Yes, when creating the new Service principal with Powershell, or when getting the service principal object, the returned object has both an 'id' property as well as an 'application id' property. 

I was indeed confused by the fact that the 'application id' was needed while documentation mentions ' id'. That said, the parameter for the 'Connect-AzAccount' cmdlet is named 'ApplicationId' so it shouldn't take to long to find this out.

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for confirming. I've put in a PR to update the verbiage. If it helps at all for you in the future, you will almost always be using the Application Id to refer to a Service Principal.
