### ISSUE TITLE
The problem Uninstall the AzureRM module form PowerShell section

### ISSUE THREAD

**Issue by HMatsumura** [MicrosoftDocs/azure-docs-powershell#1327]
This section has 2 problem.

### 1. below script explanation is not friendly.

```
foreach ($module in (Get-Module -ListAvailable AzureRM*).Name |Get-Unique) {
   write-host "Removing Module $module"
   Uninstall-module $module
}
```
The script only uninstall AzureRM.* dependencies. so, Azure.AnalysisServices and Azure.Storage is remained that installed from "Install-Module -Name AzureRM".
If we try the install of Az module from MSI installer after this script running, the installation is failed because AzureRM module detected. 

**If this script is used, we should add explanation regarding to "Azure.AnalysisServices and Azure.Storage should uninstall manually."**

### 2.  Uninstall-AllModules doesn't work well

```
$versions = (Get-InstalledModule AzureRM -AllVersions | Select-Object Version)
$versions | foreach { Uninstall-AllModules -TargetModule AzureRM -Version ($_.Version) -Force }
```

If we run above script, dependencies is not uninstalled. (The warning is output in almost modules: "Could not find uninstall candidate for {0}:{1} - module may require manual uninstall. Available versions are: {2}")

This cause, the Uninstall-AllModules function is incorrect. Current script doesn't get modules version. The script should modified like below:

before:
```
$candidate = Get-InstalledModule $_.name -RequiredVersion $version -ErrorAction Ignore
      if ($candidate) {
        $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$version}
      }
```

after:
```
$candidate = Get-InstalledModule $_.name -RequiredVersion $_.RequiredVersion -ErrorAction Ignore
      if ($candidate) {
        $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$_.RequiredVersion}
      }

```

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0e86bf-6c1d-6dda-214f-d139112819d5
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.5.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-3.5.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.5.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@HMatsumura , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@HMatsumura , I'm going to assign this to the document author so they can update the document accordingly.

**Comment by satishkmulay** [comment]
I was facing the same issue uninstalling the AzureRM and related modules even when running with elevated credentials..  It seems like for some reason the PowerShell locks the files in the session.  Haven't investigated yet why, however this worked for me.

1. Exit current PS session.
2. Launch a new elevated PS session and run -
   Get-Module -ListAvailable -Name AzureR* | Uninstall-Module -Force

I had the Azure Storage and AnalysisServices module with similar "in-use" issues and followed the above steps to uninstall them successfully.

Hope this helps.

Satish
