### ISSUE TITLE
Upgrade to Az

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/azure-docs-powershell#1335]
In section "Upgrade to Az" it says that "Keep the AzureRM module installed with PowerShell 5.1 for Windows, but install the Az module for PowerShell Core 6.x or later.". Does that mean I can have both running on the same machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95685be3-b179-5ae8-b984-740bcbb007f4
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.5.0)
* Content Source: [docs-conceptual/azps-3.5.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.5.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@ravick4u Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@ravick4u That is my understanding as there are some use cases for the legacy AzureRM, however this has understandably been an area of confusion for a lot of people so I am going to ask the document author to confirm.

@sptramer Would you mind confirming both dual installation scenarios as well as full migration?

https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.6.1#upgrade-to-az

**Dual Installation**
(in scenarios where legacy dependencies on AzureRM exist)

> To keep up with the latest Azure features in PowerShell, you should migrate to the Az module as soon as possible. If you're not ready to install the Az module as a replacement for AzureRM, you have a couple of options available to experiment with Az:
> 
> - Use a PowerShell environment with Azure Cloud Shell. Azure Cloud Shell is a browser-based shell environment which comes with the Az module installed and Enable-AzureRM compatibility aliases enabled.
> 
> - Keep the AzureRM module installed with PowerShell 5.1 for Windows, but install the Az module for PowerShell Core 6.x or later. PowerShell 5.1 for Windows and PowerShell Core use separate collections of modules. Follow the instructions to install PowerShell Core and then install the Az module from a PowerShell Core terminal.


**Upgrade/Migrate to Az**
To upgrade from an existing AzureRM install:

1. Uninstall the Azure PowerShell AzureRM module
2. Install the Azure PowerShell Az module
3. OPTIONAL: Enable compatibility mode to add aliases for AzureRM cmdlets with Enable-AzureRMAlias while you become familiar with the new command set. See the next section or Start migration from AzureRM to Az for more details.

**Comment by kobulloc-MSFT** [comment]
@ravick4u As long as the AzureRM module is installed with PowerShell 5.1 for Windows and the Az module is installed on PowerShell Core 6.x or later, you can have both versions.

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
