### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gc435** [MicrosoftDocs/azure-docs-powershell#1338]
I'll combine lots of feedback into one post.  Sorry for not separating it out.

**First:**

It's not clear what commands need to be run as Administrator and what can be run as a regular user.

**Second:**

>Azure PowerShell works with PowerShell 5.1 or higher on Windows, or PowerShell Core 6.x and later on all platforms. You should install the latest version of PowerShell Core available for your operating system.

The above is not 100% clear to me.  I think it's saying that either PowerShell 5.1 or PowerShell Core 6.x can be used, but if you use PowerShell Core then make sure you have the latest version.  Or, is it saying PowerShell Core should be used instead of PowerShell 5.1?

**Third:** 

> Make sure you have the latest version of PowerShellGet. Run `Update-Module PowerShellGet -Force`.

When I attempt the above, I get this error:

`Update-Module : Module 'PowerShellGet' was not installed by using Install-Module, so it cannot be updated.`

**Fourth:** 

> We do not support having both the AzureRM and Az modules installed for PowerShell 5.1 for Windows at the same time. If you need to keep AzureRM available on your system, install the Az module for PowerShell Core 6.x or later.

The above warning could use more details.  I'm attempting to install the Az modules into the PowerShell which comes with the Windows 10 Development Environment, which comes with Hyper-V on Windows 10 Professional.  It appears this VM has AzureRM already installed in PowerShell, so I got lots of errors about conflicts.  More detailed documentation about this potential conflict would be helpful.  Also, the Dev VM should probably not ship with AzureRM.

**Fifth:**

> First, install PowerShell Core 6.x or later

The above instruction is under "Install the Azure PowerShell Module".  Is PowerShell Core now a requirement?  I thought the introduction said PowerShell 5.1 was supported.  It seems like PowerShell Core is mentioned out of nowhere.

**Comment by MarileeTurscak-MSFT** [comment]
@gc435 thanks for this feedback! Can you please post the document which you are following so that we can better assist?

**Comment by SamaraSoucy-MSFT** [comment]
I think this is the referenced page: https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.6.1. Assigning to the doc author for review.
