### ISSUE TITLE
AzS.Storage.Admin - 1.8.1 -ErrorAction issue

### ISSUE THREAD

**Issue by mattmcspirit** [MicrosoftDocs/azure-docs-powershell#1344]
So it seems that the Get-AzsStorageQuota is not obeying the -ErrorAction parameter, for instance, if i run:

Get-AzsStorageQuota -Name "Blah" -Location $azsLocation -ErrorAction SilentlyContinue -Verbose

It raises an exception, however if i run:

Get-AzsComputeQuota -Name "Blah" -Location $azsLocation -ErrorAction SilentlyContinue -Verbose

it fails silently, as expected, assuming "Blah" does not exist in both cases

Thanks!

**Comment by mattmcspirit** [comment]
Adding @bganapa here too.

**Comment by mattmcspirit** [comment]
Issue raised in wrong place, moving to https://github.com/Azure/azure-powershell/issues

**Comment by SamaraSoucy-MSFT** [comment]
@mattmcspirit I'll close the issue here as you have posted it to the main Powershell repo. Thank you!
