### ISSUE TITLE
Install-Module -Name Az -AllowClobber failed

### ISSUE THREAD

**Issue by williamwyz** [MicrosoftDocs/azure-docs-powershell#1347]
Install-Module -Name Az -AllowClobber
WARNING: Unable to resolve package source 'https://isrmsafetnuget.azurewebsites.net/nuget/'.

**Comment by kobulloc-MSFT** [comment]
@williamwyz Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
It appears that you may be experiencing an issue with your connection.  I would troubleshoot your connection to make sure that you have access to all required resources.  If that's not an option, it is possible to complete installation offline:

https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.6.1#install-offline


For verification, the command does work as I was able to successfully execute this on a fresh machine:

![image](https://user-images.githubusercontent.com/37556655/77984878-b5a88500-72c7-11ea-9b85-8e7f0a9db2b5.png)

**Comment by kobulloc-MSFT** [comment]
@williamwyz We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
