### ISSUE TITLE
Name obtained by Get-AzureNetworkSecurityGroup

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs-powershell#1351]
I realize this is an ASM command but we have an advisory case in CSS asking for clarification.
Get-AzureNetworkSecurityGroup apparently requires that you specify the name of the resource as "Group <RG> <NSG name>", which doesn't seem to line up with anything else.
Is this by design? Azure module 5.3.0.

**Examples**
Fails when using the resource name alone
```
PS C:\WINDOWS\system32> Get-AzureNetworkSecurityGroup -Name "classic_jptest"
Get-AzureNetworkSecurityGroup : ResourceNotFound: The Network Security Group classic_jptest does not exist.
At line:1 char:1
+ Get-AzureNetworkSecurityGroup -Name "classic_jptest"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureNetworkSecurityGroup], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.Network.NetworkSecurityGroup.GetAzureNetworkSecurityGroup
```
 
Succeeds when including the RG name
```
PS C:\WINDOWS\system32> Get-AzureNetworkSecurityGroup -Name "Group jptest classic_jptest"

Name                        Location Label
----                        -------- -----
Group jptest classic_jptest West US    
```

**Comment by ram-msft** [comment]
@dcbrown16 Thanks for your question. Please provide us with the link to the documentation you are referring.

**Comment by dcbrown16** [comment]
https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/get-azurenetworksecuritygroup?view=azuresmps-4.0.0
would be the doc for this command. If there's a repo somewhere for the Azure module itself please let me know.

**Comment by dcbrown16** [comment]
but if this is by design it would be good to update the document, since this is a nonstandard use of "name".

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dcbrown16 Thanks for bringing this to our attention.

I understand the issue and have reached out to our internal Team to get more details. Will keep you posted on my findings.

**Comment by BhargaviAnnadevara-MSFT** [comment]
Looping in @barbkess.

**Comment by mikefrobbins** [comment]
This is an obscure problem that I was only able to reproduce after numerous attempts.

- When a classic network security group is created with PowerShell, it works as designed in both PowerShell and in the portal.
- When a classic network security group is created in the portal using a resource group other than the one named **Default-Networking**, it only shows up in PowerShell using the following syntax `Get-AzureNetworkSecurityGroup -Name 'Group <ResouceGroupName> <NetworkSecurityGroupName>`.
