### ISSUE TITLE
New-AzApiManagementApi -ServiceUrl parameter mandatory 

### ISSUE THREAD

**Issue by gsscoder** [MicrosoftDocs/azure-docs-powershell#1361]
Since this is a repo about docs, I don't know if this is the right place to post. If not, please excuse me.

I'm wondering why `-ServiceUrl` parameter of `New-AzApiManagementApi` is mandatory. From **Portal UI** is not. I configure my APIM Services with policies and it is correctly ignored.

The path to use a more basic **Az APIs** (like `New-AzResource`) to achieve _not setting it_ is quite impervious (if you've to deal with API versions).

See this **stackoverflow** (partially solved) question: https://stackoverflow.com/questions/60882705/azure-create-a-new-api-management-service-without-a-service-url.

Thanks all **Microsoft** teams, for great **Azure** Platform!

Giacomo S. S.

**Comment by kobulloc-MSFT** [comment]
@gsscoder Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
Adding @barbkess for clarification.

**Comment by mikefrobbins** [comment]
@kobulloc-MSFT Could you move this issue to the [github.com/Azure/azure-powershell](https://github.com/Azure/azure-powershell) repo since it's a product question and not a documentation issue? Thank You!

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins - I have moved the issue to Azure Powershell Repo. Thanks for providing your inputs. 
@gsscoder - 
Thanks again for bringing this to our attention.  I have opened a new issue in Powershell Repo. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue

**Comment by gsscoder** [comment]
@mikefrobbins, @MonikaReddy-MSFT, thank you for your time.
