### ISSUE TITLE
Username in "Password-based authentication" must be service principal's application ID

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/azure-docs-powershell#1368]
In the section "Password-based authentication", username is not clear enough.

    Use the service principal ID for the username.

There are many IDs here. And to my experience, only Application ID works. Principal name and ID does not work (The ID provided by `New-AzADServicePrincipal`). Refer to [this section.](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0#password-based-authentication)

Below is a working example. Remember to replace the tenantId and subscriptionId.
```
$sp = New-AzADServicePrincipal -DisplayName ServicePrincipalName
$pscredential = New-Object System.Management.Automation.PSCredential($sp.ApplicationId, $sp.Secret)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $yourTenantId -SubscriptionId $yourSubscriptionId 
```

Still need confirmations of others though. Did I go wrong somewhere or did I just poorly interpret the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217a6e58-c5b2-d99d-6b11-dc57f342f048
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.8.0#sign-in-with-a-service-principal-)
* Content Source: [docs-conceptual/azps-3.8.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@nguyenlamlll Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by AliRazeghi** [comment]
Please work on clarifying this documentation.
