### ISSUE TITLE
Backtick character unnecessary after the pipe character

### ISSUE THREAD

**Issue by MM-MikeM** [MicrosoftDocs/azure-docs-powershell#1371]
The backtick '`' character is unnecessary after the pipe "|" character because the pipe acts as a carriage return.  For the example on this page, Instead of "Get-AzVM -ResourceGroupName TestGroup | ` ", please eliminate the backtick character to make it "Get-AzVM -ResourceGroupName TestGroup |".  The examples will be more helpful and less confusing for people beginning to use PowerShell.  Thank you, MM-MikeM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23262a16-7bc8-646e-8143-2713e8a5afc9
* Version Independent ID: 334ff617-a357-d6de-327e-49bc5ae36bc9
* Content: [Query output of Azure PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/azure/queries-azureps?view=azps-1.8.0)
* Content Source: [docs-conceptual/azps-1.8.0/queries-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/queries-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@MM-MikeM - Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@MM-MikeM , Thanks again for bringing this to our attention. We have updated the Doc. It should merge the changes, Once the PR is approved.

**Comment by MonikaReddy-MSFT** [comment]
@MM-MikeM , Thanks again for bringing this to our attention. We have updated the Doc and We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
