### ISSUE TITLE
NO HELP FOR INSTALLING THIS

### ISSUE THREAD

**Issue by jimddavis** [MicrosoftDocs/azure-docs-powershell#1372]
more useless documentation.  How about starting with a description of how to install that should work in a reasonable way for a majority of people, and THEN do the confusing diatrive of 101 options?  I have NO IDEA WHAT TO DO!!!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842f6a18-0b96-0fae-d8f5-d8ae4c565f0e
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.8.0#code-try-1)
* Content Source: [docs-conceptual/azps-3.8.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/install-az-ps.md)
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jimddavis We're really sorry that the document was not of help to you, and apologize for any inconvenience caused.

In order to help you with the installation, could you please let us know what isn't working for you, and the error you see?

If installing with PowerShellGet seems too troublesome, you can use the [MSI](https://github.com/Azure/azure-powershell/releases/tag/v3.8.0-April2020) as well to install Azure PowerShell on Windows, if that's what you're looking for.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dcaro @barbkess I noticed that the doc does not reference the installation instructions for PowerShellGet, and submitted a PR adding the same. Please review and suggest if there can be any further improvements to the doc that can help make it clearer.

**Comment by malake** [comment]
It would be nice if we didn't have to install PowerShell at all and there were the equivalent standard of documentation for the AzureCLI. The majority of the world runs on linux/unix yet we keep getting PowerShell shoved down our throats.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jimddavis Please help us with the details of the error if you're still blocked so we can troubleshoot further.

@malake The documentation source for the Azure CLI is hosted [here](https://github.com/MicrosoftDocs/azure-docs-cli). Please open an issue or provide your feedback [here](https://github.com/MicrosoftDocs/azure-docs-cli/issues) to let us know about any improvements that can be made to the docs to make them better.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jimddavis We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
