### ISSUE TITLE
Password extraction does not work using PowerShell  Core

### ISSUE THREAD

**Issue by sliebner** [MicrosoftDocs/azure-docs-powershell#1376]
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret)
$UnsecureSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

Does not work using PowerShell Core. 

ConvertFrom-SecureString -SecureString $sp -AsPlainText
should work. And -AsPlainText is not documented clearly with ConvertFrom-SecureString.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8ceec6-fcb5-fe91-52dc-6975a533f61f
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0#feedback)
* Content Source: [docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by YutongTie-MSFT** [comment]
@barbkess 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by jeevaeastpoint** [comment]
I have seen the same behaviour. The $UnsecureSecret is give one character as the password which I am sure it can't be. Are those commands to extract the secret valid? I am using PowerShell core as well.
