### ISSUE TITLE
Docs confusing

### ISSUE THREAD

**Issue by jeevaeastpoint** [MicrosoftDocs/azure-docs-powershell#1378]
The title of the docks in left navigation panel "Create a Service principal" but the section titles in the docs talks about two authentication method. It looks like the details under the section are instructions to create a service principal in different ways. Am I wrong or the docs needed some restructuring?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8ceec6-fcb5-fe91-52dc-6975a533f61f
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0)
* Content Source: [docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint This article aims to walk one through the steps for creating, getting information about, and resetting a service principal with Azure PowerShell.

As mentioned in the section, when creating a service principal using the `New-AzADServicePrincipal` cmdlet, you choose the type of sign-in authentication it uses.

There are two types of authentication available for service principals: Password-based authentication, and certificate-based authentication, which are then detailed as sub-sections.

Therefore, the detail is still relevant to the creation of a Service Principal. Hope this clarifies your query. Please reach out if there are additional questions.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
