### ISSUE TITLE
Unable to remove credentials

### ISSUE THREAD

**Issue by jeevaeastpoint** [MicrosoftDocs/azure-docs-powershell#1380]
I have a Service Principal created and a couple of client secret created under it. I expected that running the command "Remove-AzADSpCredential -DisplayName ServicePrincipalName" would simply remove all client secret under the service principal. But I don't see any effect even though the command ran successfully. Not sure my expectation is correct.  Also, the New-AzADSpCredential command with ServicePrincipalName parameter is unable to find my service principal.  Any clue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8ceec6-fcb5-fe91-52dc-6975a533f61f
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0)
* Content Source: [docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
> I have a Service Principal created and a couple of client secret created under it. I expected that running the command "Remove-AzADSpCredential -DisplayName ServicePrincipalName" would simply remove all client secret under the service principal. But I don't see any effect even though the command ran successfully. Not sure my expectation is correct.

@jeevaeastpoint If you're looking to manage your Application client secrets that you see on the Azure Portal, then Remove-AzAD**App**Credential cmdlet is the one to run.

Here is how you can do it:
```
# Get Service Principal
$creds = Get-AzADServicePrincipal -ServicePrincipalName http://test-serviceprincipal

# Get App credentials
Get-AzADAppCredential -ApplicationId $creds.ApplicationId

# Remove App credentials
Remove-AzADSpCredential -ServicePrincipalName http://test-serviceprincipal
```

> New-AzADSpCredential command with ServicePrincipalName parameter is unable to find my service principal. Any clue?

Please specify the **-ServicePrincipalName** in the following format:
`New-AzADSpCredential -ServicePrincipalName http://test-serviceprincipal`

Please let me know if you still run into issues.

**Comment by jeevaeastpoint** [comment]
@BhargaviAnnadevara-MSFT  Thank you for this. But still trying to understand the use of Remove-AzADSpCredential  commandlet. If it is removing a certain type of credentials then where can I find these credentials in Azure portal so that I can run and go back in to check.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint That's a good question! AFAIK, the credentials created by `New-AzADSpCredential` cmdlet aren't available on the Azure portal for management.

However, if you want to cross-check if the deletion was successful, you can always run the [Get-AzADSpCredential](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azadspcredential?view=azps-3.8.0) cmdlet, as follows:

![image](https://user-images.githubusercontent.com/44050820/81889846-2da1e480-95c2-11ea-9386-e5999fc2da8a.png)

@mikefrobbins Any additional insights on this?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint Hope the above response helps. 

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by jeevaeastpoint** [comment]
@BhargaviAnnadevara-MSFT I am getting a different result. Please refer my attached screenshots.... I am using mac
<img width="1132" alt="Screenshot 2020-05-14 at 19 10 27" src="https://user-images.githubusercontent.com/7567687/81970558-a1221100-9617-11ea-9253-8149b735f1e5.png">

PSVertionTable
<img width="1082" alt="Screenshot 2020-05-14 at 19 16 05" src="https://user-images.githubusercontent.com/7567687/81970573-a67f5b80-9617-11ea-96bc-2a2e4edaa6e2.png">

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint What you see there is the expected result. You just happened to create a new service principal but haven't created any SP credentials yet. Hence, you see empty output for `Get-AzADSpCredential`.
 
Please go ahead and run the `New-AzADSpCredential` to create a new SP credential as shown in my previous screenshot:

`New-AzADSpCredential -ServicePrincipalName http://test-serviceprincipal`

And then see the result of `Get-AzADSpCredential`.

**Comment by jeevaeastpoint** [comment]
@BhargaviAnnadevara-MSFT Thank you for this. It worked. It would be good to mention in the documentation that these credentials are not visible/available from the Azure portal. It did confuse me. If it is already there, I might have missed it. Will go through the docs one more time to make sense of the whole thing with all these clarifications in mind.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jeevaeastpoint Thanks for the response, glad to know it helped.

Sure, will loop in the content author to make the necessary enhancements as applicable to the documentation.

@mikefrobbins @barbkess FYI.
