### ISSUE TITLE
Please explain how to handle managed identity token expiry

### ISSUE THREAD

**Issue by tom-stones** [MicrosoftDocs/azure-docs-powershell#1381]
When I log on with "Connect-AzureRmAccount -MSI" things eventually stop working in my long-running script because there under the hood there is an access token that expires.  Even when I add an hourly "Disconnect-AzureRmAccount" and logon again with  "Connect-AzureRmAccount -MSI", it sometimes continues to give exceptions saying token expired.  Killing the process and starting it again seems to force the token renewal - but surely there is a better way??  Here's an example of the exception:
Login-AzureRmAccount : The access token expiry UTC time '5/5/2020 11:41:43 AM' is earlier than 
current UTC time '5/5/2020 12:25:04 PM'.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217a6e58-c5b2-d99d-6b11-dc57f342f048
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.8.0)
* Content Source: [docs-conceptual/azps-3.8.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MonikaReddy-MSFT** [comment]
@tom-stones , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by mikefrobbins** [comment]
Based on the reported issue, it appears that you're using the AzureRM module, although the doc referenced uses the Az module. Please update to the latest version of whichever of these that you are currently using. There were some timing issues with certain older versions of the modules.

**Comment by tom-stones** [comment]
Hi, I'm using AzureRm.Profile version 5.8.3.
Tom.

**Comment by mikefrobbins** [comment]
Would it be possible to try the latest version of the Az module to determine if this problem also occurs with `Connect-AzAccount -MSI`? If the problem does occur, try running `Resolve-AzError` to see if it provides any additional details for what the source of the issue might be.

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins - Thank you providing your insights. 
@tom-stones - Does the above solution work for you? Please let us know.

**Comment by tom-stones** [comment]
I'll give that a go and get back to you.  It would be useful to know what is supposed to happen. When is the token supposed to be updated. When is the cached value used?

**Comment by mikefrobbins** [comment]
It is suppose to periodically check the access token and refresh it automatically before a time out occurs.

For future reference, reporting an issue via the "This product" button connects you with the developers who write the Azure PowerShell cmdlets for software related problems. Other options on the Azure PowerShell documentation pages, place you in contact with docs writers for documentation related problems.

![image](https://user-images.githubusercontent.com/6719572/82223154-eb411600-98e7-11ea-9d1c-857831fd4aef.png)

**Comment by MonikaReddy-MSFT** [comment]
@tom-stones -  Thanks again for bringing this to our attention. 
As @mikefrobbins  has mentioned, since this is not a doc related issue, I have raised an Issue for you on PowerShell GH Page for the PG to look at, and We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
