### ISSUE TITLE
The Term <command> is not recognized as the name of the cmdlet

### ISSUE THREAD

**Issue by samboustani** [MicrosoftDocs/azure-docs-powershell#1385]
Stuck in an endless loop where no commands work.  Started on a different documentation page that recommended I install AzureRm, but this one recommends Az.  Also, what goes next to the Connect-AzAccount command?  It doesn't say on this page.

The 'Connect-AzAccount' command was found in the module 'Az.Accounts', but the module could not be
loaded.

Import-Module : AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used
in the same script or runbook. If you are running PowerShell in an environment you control you can use the
'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine.

 The 'Uninstall-AzureRm' command was found in the module 'Az.Accounts', but the module could not be
loaded. For more information, run 'Import-Module Az.Accounts'.

Import-Module Az.Accounts
Get-ChildItem : AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used
in the same script or runbook. If you are running PowerShell in an environment you control you can use the
'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842f6a18-0b96-0fae-d8f5-d8ae4c565f0e
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.8.0#feedback)
* Content Source: [docs-conceptual/azps-3.8.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/install-az-ps.md)
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by dcaro** [comment]
@samboustani it looks like you have the AzureRM and Az modules installed on you machine. We are not evolving the AzureRM modules anymore and are recommending to use Az,

You can uninstall the AzureRM modules using the following guidance: https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.8.0#uninstall-from-powershell. 

```powershell 
foreach ($module in (Get-Module -ListAvailable AzureRM*).Name |Get-Unique) {
   write-host "Removing Module $module"
   Uninstall-module $module
}
```
Once AzureRM uinstalled, please install Az again to ensure that you have the latest.
