### ISSUE TITLE
How to remove all Az modules?

### ISSUE THREAD

**Issue by crisansou** [MicrosoftDocs/azure-docs-powershell#1387]
Hello,

I'm facing some problems because of the module version and I would like to uninstall all modules and install again.

I don't know how the modules were installed, I looked in "Start> Settings> Apps" and I didn't find the MSI, so I tried to use the commands from the link: https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.8.0

![image](https://user-images.githubusercontent.com/29444086/81829232-0fc87700-9511-11ea-8df4-16bda34d0845.png)

However, when I ran the command "Get-InstalledModule -Name Az -AllVersions" I received the error message below, I also tried to use the Uninstall-Module and it didn't work.

![image](https://user-images.githubusercontent.com/29444086/81829317-253da100-9511-11ea-8731-c9e39449db7a.png)

I can return the modules using the command "Get-Module -Listavailable Az* | Select-Object Name, Version", but I don't know how to remove them. Can someone help me please?

![image](https://user-images.githubusercontent.com/29444086/81829787-a9902400-9511-11ea-8ef1-1618f48d4ed8.png)

![image](https://user-images.githubusercontent.com/29444086/81830409-671b1700-9512-11ea-8054-c07ff14e0d63.png)

Best regards,
Cristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b73a5b-52d6-85c0-0587-250c732fee4f
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-3.8.0)
* Content Source: [docs-conceptual/azps-3.8.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-3.8.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by crisansou** [comment]
I ran the commands using version 5.1, I didn't understand why it was not possible in version 7.

![image](https://user-images.githubusercontent.com/29444086/81834025-d3981500-9516-11ea-838c-893fae85ea9a.png)

![image](https://user-images.githubusercontent.com/29444086/81834078-e14d9a80-9516-11ea-9d74-d118c54e1493.png)

![image](https://user-images.githubusercontent.com/29444086/81834163-fcb8a580-9516-11ea-954b-2b8de3d4619f.png)

**Comment by TravisCragg-MSFT** [comment]
@TravisCragg-MSFT Thanks for the update!

**Comment by csireesh** [comment]
use this command to remove all AZ modules..............


Get-Module -ListAvailable Az* | foreach {

 Uninstall-Module -Name $_.Name -RequiredVersion $_.Version
}
