### ISSUE TITLE
AzureRM continued support

### ISSUE THREAD

**Issue by ermagana** [MicrosoftDocs/azure-docs-powershell#1410]
Based on this statement:
"AzureRM will no longer receive new cmdlets or features. However, the AzureRM module is still officially maintained and will get bug fixes through December 2020."
I understand that bug fixes and new features will not be introduced into AzureRM. However, could it be explicitly stated when AzureRM's API cease to function? 
Will there be any version of AzureRM that cease to work, and if so, when is that date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd1c416-0417-406d-8195-f82bfdc7c860
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-4.1.0#continued-support-for-azurerm)
* Content Source: [docs-conceptual/azps-4.1.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.1.0/new-azureps-module-az.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@ermagana ,  Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by mikefrobbins** [comment]
The statement in the docs about the AzureRM module is currently accurate. No specific dates have been announced other than "_AzureRM will no longer receive new cmdlets or features. However, the AzureRM module is still officially maintained and will get bug fixes through December 2020._"

We will add additional information and dates to the docs once they're announced.

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins   - Thank you for providing your insights.
@ermagana - I hope @mikefrobbins  has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
