### ISSUE TITLE
-AsPlainText parameter only available in PS6+

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/azure-docs-powershell#1423]
[Enter feedback here]

This document details a command to run after having created the Service Principal in Azure:

`$UnsecureSecret = ConvertFrom-SecureString -SecureString $sp.Secret -AsPlainText`

This command fails in PowerShell 5.1 because the `-AsPlainText` parameter doesn't appear to be present/supported. 

It would be good to note this somewhere at the start of the article to save users having to delete the created Service Principal and start again in 6+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96e72b-f566-6198-d659-18c5d8c58221
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-4.2.0)
* Content Source: [docs-conceptual/azps-4.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.2.0/create-azure-service-principal-azureps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@robinmalik Thank you for the feedback!  We are investigating this and will get back to you shortly.
