### ISSUE TITLE
Get-AzStorageTable returning null even when table exist

### ISSUE THREAD

**Issue by arpitgupta2689** [MicrosoftDocs/azure-docs-powershell#1450]
Hi,

I am using powershell script with azure devops pipeline to create/update azure table during deployment. The script reads the config files and checks if table exist or not, and if table does not exist it creates new table and insert the data otherwise the data is updated in the table. The issue here is while checking the table i am getting null response and then i try to create the table which is giving me a error that table already exist. While checking the table from storage explorer i do see table there. Following is the code snippet from ps script 
function GetOrCreateTable ($storageContext, $tableName) 
{
	Write-Host "Trying to retrieve table $tableName"
	$table = Get-AzStorageTable -Name $tableName -Context $storageContext -ErrorAction Ignore
	if ($table -eq $null) {
		Write-Host "Creating new table $tableName"
	   $table = New-AzStorageTable -Name $tableName -Context $storageContext -ErrorAction Stop
	} 
    return $table    
}

Please let me know whats the issue here.

**Comment by BharathNimmala-MSFT** [comment]
@arpitgupta2689  Thank you for reaching out. Please be noted that this channel is only to drive document improvements with in Azure Power Shell Docs. It would be great if you can share the documentation link you are referring, so that we can assist you accordingly.

**Comment by BharathNimmala-MSFT** [comment]
@arpitgupta2689 Since we have not heard back from you we will now proceed to close this thread. If you can further share the documentation link we will gladly reopen the issue and continue the discussion. Thank you
