### ISSUE TITLE
New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "password" is null.

### ISSUE THREAD

**Issue by yaobaobao2002** [MicrosoftDocs/azure-docs-powershell#1451]
When create a service principal. and try auto login azure account I copy below code

1. $credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password="xxxxxxxxxxxxxxx"}
2. $sp = New-AzAdServicePrincipal -DisplayName ServicePrincipalName -PasswordCredential $credentials
3.$pscredential = New-Object -TypeName System.Management.Automation.PSCredential($sp.ApplicationId, $sp.Secret)

However there is error saying 
New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "password" is null.
I've thought I already give argument of password in the 1st step?

**Comment by BharathNimmala-MSFT** [comment]
@yaobaobao2002 Thank you for reaching out. Please be noted that this channel is only to drive document improvements with in Azure Power Shell Docs. It would be great if you can share the documentation link you are referring, so that we can assist you accordingly.

**Comment by yaobaobao2002** [comment]
Hello
Please refer below link and attachment
https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-4.3.0

[cid:image001.png@01D64D27.260407F0]

LIU Yao Iris
Software Engineer
DNV GL - Digital Solutions

Det Norske Veritas (China) Company Limited
E-mail Yao.liu@dnvgl.com<mailto:Yao.liu@dnvgl.com>
Mobile +86 18149722316

www.dnvgl.com<http://www.dnvgl.com/>  |  LinkedIn<http://www.linkedin.com/company/dnvgl>

[DNV GL]<http://www.dnvgl.com/>

**Comment by mikefrobbins** [comment]
Correct, you've already created a credential object in step 1. If these three steps exist together in one of the docs, please let us know where. It appears step 1 and 2 are taken from the first doc and step 3 is taken from the second doc.

```azurepowershell
Import-Module -Name Az.Resources # Imports the PSADPasswordCredential object

$credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential `
-Property @{StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=<Choose a strong password>}

$sp = New-AzAdServicePrincipal -DisplayName ServicePrincipalName -PasswordCredential $credentials
```

After running the previous code, you can connect using the service principal:

```azurepowershell
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
```

The reason the following line generates an error is because service principals with user defined passwords don't have a `Secret` property.

```azurepowershell
$pscredential = New-Object -TypeName System.Management.Automation.PSCredential($sp.ApplicationId, $sp.Secret)
```

The second doc creates a service principal with an autogenerated password. This code is used in that particular doc since the user wouldn't know the password.

**Comment by yaobaobao2002** [comment]
After run code for define $credentials and $sp,  If I directly run the code “Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId”  without define $pscredential
There is error showing 'Connect-AzAccount : Cannot bind argument to parameter 'Credential' because it is  null'

**Comment by mikefrobbins** [comment]
There was a step missing in the previously posted example.

```azurepowershell
Import-Module -Name Az.Resources # Imports the PSADPasswordCredential object

$credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=<Choose a strong password>}

$sp = New-AzAdServicePrincipal -DisplayName ServicePrincipalName -PasswordCredential $credentials

$pscredential = New-Object -TypeName System.Management.Automation.PSCredential($sp.ApplicationId, ($credentials.Password | ConvertTo-SecureString -AsPlainText -Force))

$tenantId = (Get-AzContext).Tenant.Id

Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
```
