### ISSUE TITLE
Seems the documentation for 2.0.1 is incomplete

### ISSUE THREAD

**Issue by nimeader** [MicrosoftDocs/azure-docs-powershell#1454]
content from page
Example 1: {{ Add title here }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbaabe3-57c9-609f-3db7-e2e43696aac2
* Version Independent ID: 480ef18f-797c-29dd-aae2-e86541b1fa61
* Content: [Stop-AzsScaleUnitNode (Azs.Fabric.Admin)](https://docs.microsoft.com/en-us/powershell/module/azs.fabric.admin/stop-azsscaleunitnode?view=azurestackps-2.0.1)
* Content Source: [azurestackps-2.0.1/Azs.Fabric.Admin/Stop-AzsScaleUnitNode.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azurestackps-2.0.1/Azs.Fabric.Admin/Stop-AzsScaleUnitNode.md)
* Service: **azure-powershell**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by kobulloc-MSFT** [comment]
@nimeader Thank you for bringing this to our attention!  This has been assigned to the document author.

**Comment by mattbriggs** [comment]
@nimeader @mikefrobbins Thanks! submitted the PR and all should be well (for now!)

**Comment by mattbriggs** [comment]
#please-close
