### ISSUE TITLE
Request to Include Warning

### ISSUE THREAD

**Issue by jahobson75** [MicrosoftDocs/azure-docs-powershell#1455]
My customer leveraged this documentation to change the disk caching on the fly of a live SAP HANA database and experienced an outage.  Can we include a warning in the documentation, much like the one included here?

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching

The intent is to make developers aware of the ramifications of using this functionality.

Thanks - Jason

**Comment by kobulloc-MSFT** [comment]
@jahobson75 Thank you for your feedback!  We've assigned this to the document author so they can updated the documentation accordingly.

**Comment by mikefrobbins** [comment]
@kobulloc-MSFT I’m not the author of the referenced doc. It resides in a different repo and does not appear to be PowerShell related. Can you move this issue to the correct repo?

**Comment by mikefrobbins** [comment]
@kobulloc-MSFT Actually, it looks like a link to the doc wasn't provided. The referenced doc is one that has the warning message. Maybe jahobson75 can provide a link to the doc to add a warning to?

**Comment by jahobson75** [comment]
Here's the link to the command **Set-AzureDataDisk**:
https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/set-azuredatadisk?view=azuresmps-4.0.0#related-links

Here's the link to the warning that I should either be linked to or referenced directly in the above link:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching

Specifically this section:
"Warning
Disk Caching is not supported for disks 4 TiB and larger. If multiple disks are attached to your VM, each disk that is smaller than 4 TiB will support caching.

Changing the cache setting of an Azure disk detaches and re-attaches the target disk. If it is the operating system disk, the VM is restarted. Stop all applications/services that might be affected by this disruption before changing the disk cache setting. Not following those recommendations could lead to data corruption."

Hope that helps!
Jason
