### ISSUE TITLE
Example for Sign in using a service principal with certificate is missing the ApplicationAD Parameter

### ISSUE THREAD

**Issue by Kuenni** [MicrosoftDocs/azure-docs-powershell#1456]
When running the command

`Connect-AzAccount  -ServicePrincipal -CertificateThumbprint <CTP> -TenantId <TID>`

from the examples I am prompted for the ApplicationID. The paragraph before the examples mentions the App ID but the examples do not include them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce776b96-0842-7f2c-b4cf-df1c802c9bcc
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-4.3.0)
* Content Source: [docs-conceptual/azps-4.3.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.3.0/create-azure-service-principal-azureps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@Kuenni -  Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@Kuenni -  Thanks again for bringing this to our attention. We have updated the Doc and We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
