### ISSUE TITLE
Great Tutorial

### ISSUE THREAD

**Issue by trboomer** [MicrosoftDocs/azure-docs-powershell#1469]
I have been taking a company paid for course on Azure, and the course is frustrating to me, the instructor sucks, and the course is outdated. Your free course online is sooooo much better. I got it right away because you have step by step instructions, and you explain everything in detail. I don't have to constantly backup a video and play it again. Your course is a huge time saver for me. Just wanted to say thanks. I want to pass the AZ104 exam, but I also have specific things that I want to learn to do Azure. This is the express way to learn Azure. 

Thanks, Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4bda991-acc9-badc-7305-0914b7f0bc9a
* Version Independent ID: adfc40a8-e7d7-9a83-3092-6336b0a591fb
* Content: [Create virtual machines with the Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azureps-vm-tutorial?tutorial-step=5&view=azps-4.3.0)
* Content Source: [docs-conceptual/azps-4.3.0/azureps-vm-tutorial.yml](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/live/docs-conceptual/azps-4.3.0/azureps-vm-tutorial.yml)
* Product: **powershell**
* Technology: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@trboomer Thank you so much for sharing your feedback! We're glad you found the tutorial helpful, and wish you good luck for your exam! :)

**Comment by trboomer** [comment]
Thank you. A quick question. Is there are preferred editor for JSON files?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BhargaviAnnadevara-MSFT** [comment]
@trboomer VS Code offers great JSON editing experience. For more details, check [Editing JSON with Visual Studio Code](https://code.visualstudio.com/docs/languages/json).

**Comment by trboomer** [comment]
Thank you Annadevara

___________________
Thomas R Boomer
Home: 505-672-9027
Cell: 505-412-9022

________________________________
