### ISSUE TITLE
Module name didn't match the file name and directory name

### ISSUE THREAD

**Issue by qinezh** [MicrosoftDocs/azure-docs-powershell#1482]
For the module https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azuresmps-4.0.0/Azure/Azure.md, its module name is `Azure.Service` from the yaml header, which didn't match its file name `Azure` and directory name `Azure`.

**Comment by YutongTie-MSFT** [comment]
@qinezh 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
