### ISSUE TITLE
CMD provided on this page can't uninstall AzureRM

### ISSUE THREAD

**Issue by lululilliancoding** [MicrosoftDocs/azure-docs-powershell#1494]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98eddd89-be3e-6ef1-af8b-c017e374dbc0
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.4.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-4.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.4.0/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@lululilliancoding Thank you for the feedback!  We are investigating this and will get back to you shortly.
