### ISSUE TITLE
Uninstall-AzModule -Name Az -Version 1.8.0 -> it has to be Uninstall-Module -Name Az -Version 1.8.0

### ISSUE THREAD

**Issue by aleti-pavan** [MicrosoftDocs/azure-docs-powershell#1496]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98eddd89-be3e-6ef1-af8b-c017e374dbc0
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.4.0#:~:text=To%20uninstall%20the%20Az%20modules%2C%20use%20the%20Uninstall-Module,more%20than%20one%20version%20of%20Azure%20PowerShell%20installed.)
* Content Source: [docs-conceptual/azps-4.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.4.0/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by aleti-pavan** [comment]
Following page has command wrong to uninstall Az module.

https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.4.0#:~:text=To%20uninstall%20the%20Az%20modules%2C%20use%20the%20Uninstall-Module,more%20than%20one%20version%20of%20Azure%20PowerShell%20installed.

Correction: it has to be **Uninstall-Module -Name Az -Version 1.8.0** instead of **Uninstall-AzModule -Name Az -Version 1.8.0**

**Comment by MonikaReddy-MSFT** [comment]
@aleti-pavan - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@aleti-pavan - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by mikefrobbins** [comment]
The original command is correct. It references running the function in the previous block of code in the article.

Notice the sentence prior to the referenced command says "To use this function, copy and paste the code into your PowerShell session. The following example shows how to run the function to remove an older version of Azure PowerShell."

This function is required as the `Uninstall-Module` command would only uninstall the Az module and not the Az.* modules that are also installed as part of the Az module installation process.
