### ISSUE TITLE
Login in to Azure using a Service Principal Automation Scenario

### ISSUE THREAD

**Issue by Esme-A** [MicrosoftDocs/azure-docs-powershell#1500]
I'm trying to run a PowerShell script that needs to be able to use an existing Service Principal to automatically login/authenticate in Azure and perform some tasks. I'm following this documentation, but it is not clear as to how to use a service principal in automation scenario https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-4.4.0&viewFallbackFrom=azurermps-6.6.0 so I might be missing something, I keep getting an error "Cannot process argument because the value of argument "password" is null. Change the value of argument "password" 
to a non-null value." 

#---------------------------------below is how I have the authentication piece----------------------#
$tenantId = "<my tennant Id is here>"
$sp = Get-AzADServicePrincipal -DisplayName <my sp is here>

#For automation scenarios, you need to create credentials from a service principal's applicationId and secret:
$pscredential = New-Object -TypeName System.Management.Automation.PSCredential($sp.ApplicationId, $sp.Secret)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId

**Comment by NavtejSaini-MSFT** [comment]
@Esme-A We are checking this and we will get back to you.

**Comment by kobulloc-MSFT** [comment]
@Esme-A Looking at the documentation, this is the example:

https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-4.4.0#password-based-authentication

```
$sp = New-AzADServicePrincipal -DisplayName ServicePrincipalName

$pscredential = New-Object -TypeName System.Management.Automation.PSCredential($sp.ApplicationId, $sp.Secret)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
```

Here is my repro:

![image](https://user-images.githubusercontent.com/37556655/89081884-460fd880-d341-11ea-8507-b0bd2fc8b486.png)

The documentation does work however I suspect that you are running into an issue while creating your $sp variable.  I would manually run through the commands like I have done in my example above to make sure that everything is working correctly.  Permissions are often to blame when running into a null value in this kind of scenario.

**Comment by kobulloc-MSFT** [comment]
@Esme-A We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

If you'd like help further troubleshooting your issue, please reach out to us on Microsoft Q&A where we would be happy to work with you:
https://docs.microsoft.com/en-us/answers/topics/azure-active-directory.html
