### ISSUE TITLE
Alpine Docker Image for azure Powershell

### ISSUE THREAD

**Issue by SunnyOswal** [MicrosoftDocs/azure-docs-powershell#1503]
Our organization has approved only alpine based docker images to be used. Can we have alpine image also part of Microsoft official docker image with Azure Powershell Pre-Installed ? Any particular reason it is not already provided ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c312ee-b3c5-bfdd-2a09-84081392c165
* Version Independent ID: 704a0939-3db7-da42-9d28-7772a08aa5c5
* Content: [Using Azure PowerShell in Docker](https://docs.microsoft.com/en-us/powershell/azure/azureps-in-docker?view=azps-4.4.0)
* Content Source: [docs-conceptual/azps-4.4.0/azureps-in-docker.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.4.0/azureps-in-docker.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@SunnyOswal Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by SunnyOswal** [comment]
closing this as got response on the azure-powershell github repo.
https://github.com/Azure/azure-powershell/issues/12555

**Comment by BhargaviAnnadevara-MSFT** [comment]
@SunnyOswal Thank you, we're glad your query was addressed!
