### ISSUE TITLE
dead link report

### ISSUE THREAD

**Issue by scheblein** [MicrosoftDocs/azure-docs-powershell#1522]
On this page:

- Linux Virtual Machines
- Windows Virtual Machines

are dead links (404s).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 86324274-e59e-d272-0554-f51a63e7ec5c
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@scheblein Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@scheblein The new links are below.  I'll get this updated shortly.

**Linux Virtual Machines**
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/powershell-samples

**Windows Virtual Machines**
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/powershell-samples

**Comment by kobulloc-MSFT** [comment]
Adding @mikefrobbins to submit the PR.

**Comment by mikefrobbins** [comment]
Resolved by @kobulloc-MSFT via PR #1526
