### ISSUE TITLE
Incorrect replaced cmdlets for AzApiManagementProperty

### ISSUE THREAD

**Issue by RoelDG** [MicrosoftDocs/azure-docs-powershell#1552]
The document describes that the Get-, New-, Remove-, Set-AzApiManagementProperty cmdlets have been replaced with Get-, New-, Remove-, Set-**AzureApiManagementNamedValue** cmdlets but these are unknown cmdlets

The replaced cmdlets should be Get-, New-, Remove-, Set-**AzApiManagementNamedValue** respectively

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afa781d9-4768-24c5-09b8-b707dc75db8a
* Version Independent ID: eab00b44-ad2a-fffd-7042-e6133009b357
* Content: [Migration guide for Az 4.1.0](https://docs.microsoft.com/en-us/powershell/azure/migrate-az-4.1.0?view=azps-4.6.1)
* Content Source: [docs-conceptual/azps-4.6.1/migrate-az-4.1.0.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.1/migrate-az-4.1.0.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@RoelDG - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@RoelDG - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
