### ISSUE TITLE
Is it possible to retrieve "Registration Name" and "Resource Group" from this command?

### ISSUE THREAD

**Issue by mahoncj** [MicrosoftDocs/azure-docs-powershell#1560]
Hello,

We are looking to leverage this command to retrieve the registration name from multiple scale units. Registration Name is found on the Properties page of the region on the Azure Stack Admin Portal. This command seems to retrieve that information except for Registration Name or the corresponding Resource Group which should be "azurestack" found on the Billing Tenant. 

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6470df55-c1d6-d5d7-86f8-84bdd4fc9091
* Version Independent ID: b0e87e42-5957-2b7f-ecee-56f5998836db
* Content: [Get-AzsInfrastructureLocation (Azs.Fabric.Admin)](https://docs.microsoft.com/en-us/powershell/module/Azs.Fabric.Admin/Get-AzsInfrastructureLocation?view=azurestackps-1.8.0)
* Content Source: [azurestackps-1.8.0/Azs.Fabric.Admin/Get-AzsInfrastructureLocation.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azurestackps-1.8.0/Azs.Fabric.Admin/Get-AzsInfrastructureLocation.md)
* Service: **azure-powershell**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mattbriggs**

**Comment by kobulloc-MSFT** [comment]
@mahoncj Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by mattbriggs** [comment]
@mahoncj Thanks. I have a question to the technical team about the place cmdlet to find the info in your context. Thanks! Matt

**Comment by mattbriggs** [comment]
The customer can get the azureRegistrationResourceIdentifier by logging into Azure Stack:
 
$envName = "AzureStackAdminReg"
Add-AzureRmEnvironment -Name $envName -ARMEndpoint $AdminResourceManager | Out-Null
$loginParams = @{
    Environment     = $envName
    Tenant          = $aadTenantID
    Subscription    = 'Default Provider Subscription'
   Credential      = $AzureStackAdminCredential
}
Login-AzureRMAccount @loginParams
$subscription = (Get-AzureRmContext).Subscription.Id
$regPropertiesAzureStack = (Get-AzureRmResource -ResourceId "/subscriptions/${subscription}/resourceGroups/azurestack-activation/providers/Microsoft.AzureBridge.Admin/activations/default").Properties
$azureRegResIden = $regPropertiesAzureStack.azureRegistrationResourceIdentifier 
$strArr = $azureRegResIden.Split('/')
$azureSubscription = $strArr[$strArr.IndexOf('subscriptions')+1] 
 
 
 @mahoncj 

You can then use azureRegistrationResourceIdentifier to retrieve registration info like RegistrationName and ResourceGroupName by logging into AzureCloud
 
Login-AzureRmAccount -Subscription $azureSubscription -Environment 'AzureCloud' 
$regResourceAzure = Get-AzureRmResource -ResourceId $azureRegResIden
$registrationName = $regResourceAzure.Name
$resourceGroupName = $regResourceAzure.ResourceGroupName
$resourceGroup = Get-AzureRmResourceGroup -Name $resourceGroupName
$resourceGroupLocation = $resourceGroup.Location
$billingModel = $regResourceAzure.Properties.billingModel

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@mahoncj  Thanks again for your comment. I'm going to close this now, but you have additional questions please let me know

**Comment by mattbriggs** [comment]
#please-close

**Comment by mahoncj** [comment]
@mattbriggs Thank you for the above code block! That's exactly what we're after. Very much appreciated.

**Comment by mattbriggs** [comment]
#please-close
