### ISSUE TITLE
The entire doc article is hyperlinked

### ISSUE THREAD

**Issue by JasonFreeberg** [MicrosoftDocs/azure-docs-powershell#1561]
The markdown is formatted incorrectly, and half [the doc](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.6.1) is a broken hyperlink.

![image](https://user-images.githubusercontent.com/18747768/93165357-ad56d180-f6d0-11ea-905f-8f2cc87aa2d4.png)

![image](https://user-images.githubusercontent.com/18747768/93165385-be9fde00-f6d0-11ea-8800-c843ef01516d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873500f9-ae68-2bdd-9956-01a5904c5a06
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.6.1)
* Content Source: [docs-conceptual/azps-4.6.1/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.1/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@JasonFreeberg Thanks for bringing this to our attention. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@JasonFreeberg Thanks for catching that error in the doc! I have submitted a PR to fix the issue that's in review.
