### ISSUE TITLE
Page has a link all over the place

### ISSUE THREAD

**Issue by Jamminroot** [MicrosoftDocs/azure-docs-powershell#1564]
There's a link stuck somewhere in the page, so entire page turned into a link.

![image](https://user-images.githubusercontent.com/6387654/93210970-a2a04900-f771-11ea-96e5-306398a90f29.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873500f9-ae68-2bdd-9956-01a5904c5a06
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.6.1)
* Content Source: [docs-conceptual/azps-4.6.1/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.6.1/uninstall-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Jamminroot Thanks for bringing this to our attention. This was also reported in #1561. I have submitted a PR to fix the issue that's in review.

**Comment by mikefrobbins** [comment]
Resolved by @BhargaviAnnadevara-MSFT via #1562.
