### ISSUE TITLE
Missing ProductName information for Remove-AzsAzureBridgeDownloaddProduct

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-docs-powershell#1566]
This page is missing ProductName information for Remove-AzsAzureBridgeDownloaddProduct:

https://docs.microsoft.com/en-us/powershell/module/azs.azurebridge.admin/Remove-AzsAzureBridgeDownloadedProduct?view=azurestackps-2.0.2

**Comment by BhargaviAnnadevara-MSFT** [comment]
@TheOnlyWei Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mattbriggs Looks like the syntax of the cmdlet is not consistent with the examples provided on this page. Please take a look and update as appropriate.

**Comment by mattbriggs** [comment]
@TheOnlyWei Thanks I'm passing along to the product team who owns the OpenAPI that this content is built from. Thanks! Matt

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@TheOnlyWei The -Name parameter is specified. However, I've sent your feedback about the formatting to the product group. Thanks! Matt

#please-close

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mattbriggs Thanks for following up on this!

@TheOnlyWei Closing the issue here as this is being tracked internally.
