### ISSUE TITLE
Concerns with Official document for Azure PowerShell

### ISSUE THREAD

**Issue by v-mosh21** [MicrosoftDocs/azure-docs-powershell#1586]
Hello Teams,

**Issue:**
Recently, we have some reports having concerns with using the official document:

1. https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0
For this document, it is a document to describe how to install/import the Azure Module. However, it did not mention which platform the module is supported. (One of cases reported that the Azure Module cannot be installed in the Linux Ubuntu system).

2. https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.8.0
This is a very common document when you are searching Azure PowerShell in the google search. However, this document only mentioned Az and AzureRM Module and there is no where to find a link leading to Azure Module which I mentioned in above.
It is not convinced for user (sometimes may cause misunderstanding) to search for a classic module when he/she wants to operation classic service such as cloud service with PowerShell command.

3.There are three modules for the Azure PowerShell: Az, AzureRM, Azure. The Az and AzureRM Module are used to operate ARM (Azure Resource Manager) resources while Azure Module is used to operate classic resource such as cloud service. It is very helpful if you could break them apart somewhere in the document.

**Request:**
We will be very appreciated if these documents could be updated to make the content more clear so there will not be any misunderstanding with the concepts.

Thanks for all your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6c7f7-a61f-5a06-b964-888ee03eb86b
* Version Independent ID: a166875b-49f9-ea6d-d7ad-123189ef7b5c
* Content: [Install and configure the Azure PowerShell Service Management module](https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0)
* Content Source: [docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md)
* Service: **azure-asm**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@v-mosh21 Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mikefrobbins** [comment]
The content of the referenced articles has been updated. The following message about the Azure Service Management module only being supported on Windows has been added to the installation article.

![image](https://user-images.githubusercontent.com/6719572/204382603-0cb06861-0542-4ba5-acc2-a41af4bcb226.png)
