### ISSUE TITLE
Update Set-AzWebApp ref documentation

### ISSUE THREAD

**Issue by dcaro** [MicrosoftDocs/azure-docs-powershell#1587]
The reference documentation and associated samples should give a better guidance how to build the hashtable for the `ConnectionString` parameter.

Here is an example: 
$hashtable = @{$NameVariable = @{Value=ValueVariable;Type=TypeVariable}}
Set-AzWebApp -ResourceGroup $ResourceGroupName -name $AppName -ConnectionString $hashtable

**Comment by MartinJaffer-MSFT** [comment]
Hello @dcaro 
Thank you for bringing this to our attention.  To better assist you, could you please identify which document this is in reference to?

**Comment by dcaro** [comment]
here is the reference documentation page:
https://docs.microsoft.com/en-us/powershell/module/az.websites/set-azwebapp
