### ISSUE TITLE
MSI installer link doesn't point to a place with the MSI

### ISSUE THREAD

**Issue by j1mmyfever** [MicrosoftDocs/azure-docs-powershell#1588]
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-4.7.0 the Github link points to latest release, not an MSI.  Can you make the MSI easier to find?  This seems to be a recurring problem of pointing to either not the latest MSI, or not to an MSI at all.

**Comment by kobulloc-MSFT** [comment]
@j1mmyfever Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@j1mmyfever I agree, finding the correct MSI is not terribly intuitive.  You can find the 4.7.0 release from September 16th, 2020 here (the Az-Cmdlets MSI is under assets at the bottom):
https://github.com/Azure/azure-powershell/releases/tag/v4.7.0-September2020

In general, you can find a chronological list of releases here:
https://github.com/Azure/azure-powershell/releases

I'm going to update the documentation to make finding the MSI easier moving forward.

**Comment by kobulloc-MSFT** [comment]
@j1mmyfever Thank you again for bringing this to our attention!  The documentation has been updated to make finding the MSI easier, and should go live shortly.  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
