### ISSUE TITLE
Cannot Retrieve Full Version Number

### ISSUE THREAD

**Issue by camsilv** [MicrosoftDocs/azure-docs-powershell#1594]
Hi, when looking at an extension in the portal, we can see the full version number i.e. 1.4.1654.1. When using Get-AzureRmVMExtension (or it's AZ equivalent) This is truncated to simply "1.4" as the "typeHandlerVersion" property. Is it possible to get back the full version number?

Thanks

**Comment by kobulloc-MSFT** [comment]
@camsilv Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@camsilv We've got some documentation that covers discovering VM extensions which may be what you are looking for:

https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#discover-vm-extensions

```
Get-AzVmImagePublisher -Location "WestUS" | `
Get-AzVMExtensionImageType | `
Get-AzVMExtensionImage | Select Type, Version
```

![image](https://user-images.githubusercontent.com/37556655/95765768-295c1f00-0c67-11eb-8b76-825cf8980556.png)

**Comment by camsilv** [comment]
Thanks for that, does that show the version of an image that's attached to a VM or just what the latest version of the extension image is? We're looking to see the full version of the extension currently attached to a VM

**Comment by kobulloc-MSFT** [comment]
@camsilv In theory, [az vm extension list](https://docs.microsoft.com/en-us/cli/azure/vm/extension?view=azure-cli-latest#az_vm_extension_list) and [az vm extension show](https://docs.microsoft.com/en-us/cli/azure/vm/extension?view=azure-cli-latest#az_vm_extension_show) should give you what you are looking for.  I'm having a hard time reproducing this for you as the extensions immediately available for me are just x.y.  If that's not working, let me know and I'll see if I can get a better answer for you.

**Comment by kobulloc-MSFT** [comment]
@camsilv Additionally, if the goal is to determine if you need to update the extension there is a good write up on that (again, this gives an x.y TypeHandlerVersion):

https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#how-do-agents-and-extensions-get-updated

**Comment by kobulloc-MSFT** [comment]
@camsilv Adding to this, running az extension list locally does give you a x.y.z version:

![image](https://user-images.githubusercontent.com/37556655/95805172-a1533500-0cb9-11eb-8429-914df5e4a34b.png)

**Comment by camsilv** [comment]
Great, thanks for the replies. I'll look into that further and get back to you.

We are trying to get the version for Network Watcher in particular, which has a number like "1.4.1654.1"

Ta

**Comment by mikefrobbins** [comment]
@BhargaviAnnadevara-MSFT @kobulloc-MSFT Please move this issue to the [azure-powershell](https://github.com/Azure/azure-powershell) repo. We have confirmed that it is not a docs issue and is something that the engineering team is going to need to look at. Thank you!

**Comment by camsilv** [comment]
Sorry, this was the link I was given by MS support, which is why it ended up here.

We ended up finding a way foir what we need:

AZ + AzureRM:

$json = (az vm get-instance-view -g pcsdev-weu-jum-rg10 -n pcsdevweujum02 --output json)
(($json |convertfrom-json).instanceview.vmagent.extensionhandlers | ? {$_.type -eq "Microsoft.Azure.NetworkWatcher.NetworkWatcherAgentWindows"}).TypeHandlerVersion
1.4.1654.1

Just AzureRM

(Get-AzureRmVMExtension -ResourceGroupName "pcsdev-weu-jum-rg10" -VMName "pcsdevweujum01"  -Name AzureDiskEncryption -Status).Statuses.Message -match "version: ([\d\W]+)(\).$)" | out-null ;$Matches[1]
1.4.1654.1

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikefrobbins Thanks for the update. I've opened an issue with the Azure PowerShell repo for the engineering Team to look at: https://github.com/Azure/azure-powershell/issues/13248

@camsilv Thanks for sharing what worked for you with the community! We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@camsilv Just a heads up again that this issue is being investigated here: Azure/azure-powershell#13248
Kindly provide the requested information and take the discussion forward.
