### ISSUE TITLE
Suspend-AzureRMAutomationJob is unable to suspend Job

### ISSUE THREAD

**Issue by SarveshPandey** [MicrosoftDocs/azure-docs-powershell#1607]
I have schedule a job in Azure Automation which runs daily at and start my VM. Now, i want to disable this job for three days for this I used "**Suspend-AzureRMAutomationJob**" but unfortunately it didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 86324274-e59e-d272-0554-f51a63e7ec5c
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/overview?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by Svijay-msft** [comment]
Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@SarveshPandey Could you please provide more details about the exact command you tried to execute and the error you saw?

**Comment by SarveshPandey** [comment]
Sure,

![image](https://user-images.githubusercontent.com/25227161/97083067-72c74980-162b-11eb-9c23-e76ee253c63f.png)

Above command I used to disable the job.
What i tried doing it -
1. Running this command 3 minutes before StartVm job.\
2. Running this command on the same time of startVm job.

But in both the scenario it doesn't work.

**Comment by SarveshPandey** [comment]
any updates?

**Comment by mikefrobbins** [comment]
@BhargaviAnnadevara-MSFT Please move this issue to the [azure-powershell GitHub repo](https://github.com/Azure/azure-powershell) as it appears to be a bug and not a docs issue.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikefrobbins I see that @SarveshPandey has opened one [here](https://github.com/Azure/azure-powershell/issues/13325) with the Azure PowerShell repo already.

@SarveshPandey Thanks for reporting the issue. Our Engineering Team will look into the issue and take the troubleshooting forward [here](https://github.com/Azure/azure-powershell/issues/13325).

At this point, it appears that there are no edits or updates needed to the document in question. Hence closing this issue for now. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
