### ISSUE TITLE
Example Script for Changing the Subscriptions Does not work

### ISSUE THREAD

**Issue by asmithgt** [MicrosoftDocs/azure-docs-powershell#1610]
In attempting to efficiently and effectively switch between subscriptions in a PowerShell Script I tried to use the following example code in the documentation here, but it simply does not work.

`$context = Get-AzSubscription -SubscriptionId "<mysubscriptionGuid>"
Set-AzContext $context`

The resulting Error message is as below:

> Set-AzContext : Cannot bind parameter 'Context'. Cannot convert the "<mysubscriptionGuid>" value of
> type "Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription" to type
> "Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext".
> At line:1 char:24
>  Set-AzContext -Context $context
>                         ~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-AzContext], ParameterBindingException
>     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand

In genreal switching between subscriptions in a PowerShell script is problematic and it would be nice to have this fixed.  Having documentation that is incorrect doesn't help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a37f0fc0-a4fb-c130-26d7-58e6e9a51a0b
* Version Independent ID: 98b7ac0d-e288-bb26-57b8-c173c46821d5
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/manage-subscriptions-azureps?view=azps-4.8.0)
* Content Source: [docs-conceptual/azps-4.8.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-4.8.0/manage-subscriptions-azureps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@asmithgt Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by mikefrobbins** [comment]
@asmithgt As shown in the documentation, the command must be run on 2 separate lines. You can pipe the 2 commands together however if you want to use them in a one-liner.

```powershell
Get-AzSubscription -SubscriptionId "<mysubscriptionGuid>" | Set-AzContext
```

If you're still experience problems, could you provide what operating system, the version of PowerShell, and the version of the Az PowerShell module that you're using?

**Comment by asmithgt** [comment]
@mikefrobbins Piping the command all into one line does work.  And I apologize as realizing that I was trying this that wasn't explicitly as written.  I was using it as a separate line, but it looks like my line break was removed at some point in my post.  The difference here is that on the "Set-AzContext" command I was also using the "-Context" parameter which resulted in the error.  Using the default parameter set, this worked as written.  It is confusing that the example is talking about a context, yet you cannot use the "-Context" parameter option.

Thank you!
