### ISSUE TITLE
Why recommend Powershell 7 if it doens't work?

### ISSUE THREAD

**Issue by lolodi** [MicrosoftDocs/azure-docs-powershell#1617]
In the top of the documentation there is the recommendation to use Powershell 7 for Azure Powershell when this actually doesn't work, as documented here:
https://github.com/Azure/azure-powershell/issues/6981

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed724202-b72d-b1b0-102e-ae7beedf0225
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.0.0)
* Content Source: [docs-conceptual/azps-5.0.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.0.0/install-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lolodi Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lolodi All versions of the `AzureRM` PowerShell module are outdated, although not out of support. The [Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-5.0.0) is now the recommended PowerShell module for interacting with Azure.

Are you running into any issues while running the `Connect-AzAccount` or `Login-AzAccount` on PowerShell 7.x?

**Comment by lolodi** [comment]
Was not aware hat there was a new module. With the new one seems to be working fine. Thanks!

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lolodi Sure, thanks for confirming!

We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
