### ISSUE TITLE
Update AzureRM migration guide

### ISSUE THREAD

**Issue by dcaro** [MicrosoftDocs/azure-docs-powershell#1641]
We need to refresh the AzureRM migration content to include the following:
- Update the overview page
- Upgrade in place vs create new files 
- Add a page on the VSCode extension

**Comment by BharathNimmala-MSFT** [comment]
@dcaro Thanks a lot for sharing your feedback to help improve our documentation. Would greatly appreciate if you share the documentation link as well so that we can add the meta data accordingly and also assign to respective doc owners for this updates. Thanks again

**Comment by kobulloc-MSFT** [comment]
@dcaro Assigning this to the doc author.  Please let me know if we need to alter assignment.

**Comment by mikefrobbins** [comment]
Per @dcaro, the resolution to this issue has been completed.
