### ISSUE TITLE
Should this be February 2021????

### ISSUE THREAD

**Issue by bmcder** [MicrosoftDocs/azure-docs-powershell#1650]
This page has been updated to state that support for AzureRm modules will end in February 2020 - but should this state February 2021 instead??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e69e2f9-8ab3-a444-6413-464bf6b07165
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-5.1.0)
* Content Source: [docs-conceptual/azps-5.1.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.1.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
Already fixed in #1649. The changes will go live once master is merged to live.
