### ISSUE TITLE
New-AzUpgradeModulePlan reports syntax errors 

### ISSUE THREAD

**Issue by nreddipalle** [MicrosoftDocs/azure-docs-powershell#1653]
New-AzUpgradeModulePlan reports Syntax errors on few powershell scripts but not providing more context on what the errors ar e about.. How to get more info about the errors??

```
The PowerShell file provided [C:\Users\Azure-SQL-Stats.ps1] has
16 syntax error(s). Please correct the syntax errors then try again.
At C:\Program
Files\WindowsPowerShell\Modules\Az.Tools.Migration\0.1.0\Functions\Private\Find-CmdletsInFile.ps1:46 char:17
+ ...             throw "The PowerShell file provided [$FilePath] has $($pa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The PowerShell ...then try again.:String) [], RuntimeExcept
   ion
    + FullyQualifiedErrorId : The PowerShell file provided [C:\Users\Azure-SQL-Stats.ps1] has
  16 syntax error(s). Please correct the syntax errors then try again.
```

**Comment by AjayKumar-MSFT** [comment]
@nreddipalle, Thanks for leveraging Azure docs feedback channel to raise this question. Could you please share the Azure documentation for which this feedback is applicable to?

This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.

**Comment by AjayKumar-MSFT** [comment]
@nreddipalle,  Just checking in to see if you have had a chance to see the previous response. Kindly let us know if you need further assistance on this issue or is good to be closed.

**Comment by mikefrobbins** [comment]
@nreddipalle Based on the error, this appears to be a software related issue and not a documentation problem. Please log your issue in the [azure-powershell-migration](https://github.com/Azure/azure-powershell-migration) repo.

**Comment by mikefrobbins** [comment]
Closing this issue as it's not a documentation related problem. The repo ([azure-powershell-migration](https://github.com/Azure/azure-powershell-migration)) for logging software problems related to the Az.Tools.Migration PowerShell module has been provided.
