### ISSUE TITLE
AzBootStrapper install-module doesn't work as documented

### ISSUE THREAD

**Issue by brsteel** [MicrosoftDocs/azure-docs-powershell#1654]
i had to add to the install-module:
Install-Module -Name Az.BootStrapper -Force -AllowPrerelease -SkipPublisherCheck
the PSD1 was failing with:
 The module 'Az.BootStrapper' cannot be installed or updated because the authenticode
     | signature of the file 'Az.BootStrapper.psd1' is not valid.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0300d206-32f9-6651-94bf-78a9cb460e16
* Version Independent ID: d16476ba-1834-ac38-1142-a36a4864bb29
* Content: [Overview of Azure Stack Hub Admin PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-2.0.2&viewFallbackFrom=azs-2008)
* Content Source: [docs-conceptual/azurestackps-2.0.2/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-2.0.2/overview.md)
* Service: **azure-stack**
* GitHub Login: @sijuman
* Microsoft Alias: **sijuman**

**Comment by NavtejSaini-MSFT** [comment]
@brsteel We are checking this and we will get back to you.

**Comment by kobulloc-MSFT** [comment]
@brsteel Thank you for bringing this to our attention.  We're following up on the signature error you've reported.

Command from the documentation:

`Install-Module -Name Az.BootStrapper -Force -AllowPrerelease`


Reported workaround for signature not valid error:

`Install-Module -Name Az.BootStrapper -Force -AllowPrerelease -SkipPublisherCheck`

**Comment by mattbriggs** [comment]
@brsteel Did the work around work for you?

#in-progress

**Comment by bganapa** [comment]
@mattbriggs lets add -SkipPublisherCheck while we investigate the actual issue. I havent got time to look in to it yet

**Comment by kobulloc-MSFT** [comment]
@mattbriggs Created [PR 1664](https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1664).

**Comment by mattbriggs** [comment]
#sign-off

**Comment by kobulloc-MSFT** [comment]
@brsteel Thank you again for bringing this to our attention!  We are following up internally to address the signature issue, and have updated our documentation to unblock other readers (this should go live shortly).  We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
