### ISSUE TITLE
Add-AzureAccount mentioned in article is not part of Module Az - need MSI installer for Module Azure

### ISSUE THREAD

**Issue by MattRalph** [MicrosoftDocs/azure-docs-powershell#1656]
[Enter feedback here]
Hi,
Could a link to the Azure Module MSI installer be put somewhere in this article please?
I cannot find this on GitHub, or anywhere else
This module contains Add-AzureAccount (which is not in the Az module)
This command is one of the troubleshooting steps mentioned in the article
I need to install this on a machine that can't get out to the Internet 
Many thanks in advance
Cheers,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a216181-0864-5435-b27d-75513f4308a2
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.2.0)
* Content Source: [docs-conceptual/azps-5.2.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.2.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@MattRalph One of the neighboring install pages is Install with MSI, which you can find here:
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-5.2.0

You'll find instructions to get to the install link under [Install or update on Windows using the MSI Package](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-5.2.0#install-or-update-on-windows-using-the-msi-package) which will take you here:

5.2.0 MSI:

- [Az-Cmdlets-5.2.0.33762-x64.msi](https://github.com/Azure/azure-powershell/releases/download/v5.2.0-December2020/Az-Cmdlets-5.2.0.33762-x64.msi)

- [Az-Cmdlets-5.2.0.33762-x86.msi](https://github.com/Azure/azure-powershell/releases/download/v5.2.0-December2020/Az-Cmdlets-5.2.0.33762-x86.msi)
 
 
![image](https://user-images.githubusercontent.com/37556655/101828952-1dfe6600-3ae7-11eb-8f39-ce753279c596.png)

**Comment by MattRalph** [comment]
Hi,

That is for the Az module, which does not include the Add-AzureAccount command - screenshot of where this command is used, below, and link to page which gave option to post GitHub feedback

I am after the Azure module

I have this module on my computer, and can see the AddAzureAccount command on that

I'm trying to get an MSI installer for the Azure (not Az) module so I can install it on a server that is not able to access online repositories, I can't update it, install it with PowerShell commmands

Cheers,

Matt


[cid:7d5f6f74-c760-4918-bd88-1b4655f8a3d7]

Troubleshoot Azure Automation runbook issues | Microsoft Docs<https://docs.microsoft.com/en-us/azure/automation/troubleshoot/runbooks>




[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/azure/automation/troubleshoot/runbooks>
Troubleshoot Azure Automation runbook issues | Microsoft Docs<https://docs.microsoft.com/en-us/azure/automation/troubleshoot/runbooks>
In this article. This article describes runbook issues that might occur and how to resolve them. For general information, see Runbook execution in Azure Automation.. Diagnose runbook issues
docs.microsoft.com

________________________________

**Comment by kobulloc-MSFT** [comment]
@MattRalph Ah, perfect.  I'm seeing that under step 2 of [Resolution](https://docs.microsoft.com/en-us/azure/automation/troubleshoot/runbooks#resolution-1).  Let me look into that for you.

**Comment by mikefrobbins** [comment]
@MattRalph The [Azure PowerShell Service Management module](https://docs.microsoft.com/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0) is only for the classic deployment model. This module allows you to work with your classic Azure deployments that have not been converted to Azure Resource Manager. There is no MSI for the module.

You can use [`Save-Module`](https://docs.microsoft.com/powershell/module/powershellget/save-module) to download the Azure PowerShell Service Management module from a system that has access to the Internet. Then copy it to a location in the [`$env:PSModulePath`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath) on the system that does not have Internet access.

Also, notice that the [referenced doc](https://docs.microsoft.com/azure/automation/troubleshoot/runbooks) gives two different options, one for Azure Service Management and another for Azure Resource Manager depending on whether or not you're using the classic deployment model.

```powershell
$Cred = Get-Credential
#Using Azure Service Management (Option 1)
Add-AzureAccount –Credential $Cred
#Using Azure Resource Manager (Option 2)
Connect-AzAccount –Credential $Cred
```

Let us know if this helps and if you need further assistance.

**Comment by kobulloc-MSFT** [comment]
@MattRalph We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
