### ISSUE TITLE
What is the difference between az login and ConnectAz-Account?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-docs-powershell#1663]
I've seen references to az login and ConnectAz-Account.  What's the difference between the two?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef50bb3-4111-38ae-0d8e-984eecf1616c
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-5.2.0)
* Content Source: [docs-conceptual/azps-5.2.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.2.0/authenticate-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by NavtejSaini-MSFT** [comment]
@marklannucci We are checking this and we will get back to you.

**Comment by AjayKumar-MSFT** [comment]
@MarkIannucci,  They're aliases; Connect-AzAccount | az login.  The `Connect-AzAccount` cmdlet connects to Azure with an authenticated account for use with cmdlets from the Az PowerShell modules. 

Connect-AzAccount: Connect to Azure with an authenticated account for use with cmdlets from the Az PowerShell modules.
Az login (CLI) - https://docs.microsoft.com/cli/azure/reference-index?view=azure-cli-latest#az_login

![image](https://user-images.githubusercontent.com/44606227/102004775-ae33e980-3d39-11eb-995d-0e3ed7b00ee8.png)

As mentioned in the document, there are _several ways_ to connect to Azure: 
az login [_--allow-no-subscriptions]
         [--identity]
         [--password]
         [--service-principal]
         [--tenant]
         [--use-cert-sn-issuer]
         [--use-device-code]
         [--username]_

**Comment by MarkIannucci** [comment]
That was what I suspected. Thank you for confirming.
