### ISSUE TITLE
Whats the equivalent in PS for --skd-auth true -- SPN for Terraform needs this.

### ISSUE THREAD

**Issue by g0pinath** [MicrosoftDocs/azure-docs-powershell#1676]
[Enter feedback here]

As per the documentation, the below creates the SPN but cant be used by Terraform.
https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-5.2.0

$sp = New-AzADServicePrincipal -DisplayName $env:DEV_K8S_SPN_NAME -SkipAssignment
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret)
$UnsecureSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

Terraform needs the below to work
az ad sp create-for-rbac -n $env:DEV_K8S_SPN_NAME --role Contributor `
              --scopes /subscriptions/$env:DEV_ARM_SUBSCRIPTION_ID --sdk-auth true
The question is, is there an equivalent for --sdk-auth true in PowerShell.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7880307f-88c6-27bd-3826-76d8e742f194
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-5.2.0)
* Content Source: [docs-conceptual/azps-5.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.2.0/create-azure-service-principal-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@g0pinath Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@g0pinath AFAIK, there isn't an exact parallel matching `--sdk-auth` in PowerShell. Adding @mikefrobbins to help with additional insights.

**Comment by Duffney** [comment]
Hi @g0pinath and @BhargaviAnnadevara-MSFT,

The `New-AzAdServicePrincipal` cmdlet does not provide a parameter that is equivalent to `--sdk-auth`.

However, you can provision the service principal with PowerShell by creating the service principal with a password. Then run the `New-AzRoleAssignment` cmdlet to give the service principal an assignment.

Here is a code snippet for creating the service principal and adding the role assignment.

```
$spName = '<Name>'
$spPassword = '<Password>'


$credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{
StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=$spPassword};

$spSplat = @{
  DisplayName = $spName
  PasswordCredential = $credentials
}

$sp = New-AzAdServicePrincipal @spSplat

$subId = (Get-AzContext).Subscription.Id
$roleAssignmentSplat = @{
  ObjectId = $sp.id;
  RoleDefinitionName = 'Contributor';
  Scope = "/subscriptions/$subId"
}

New-AzRoleAssignment @roleAssignmentSplat
```

Please be sure to scope the role assignment to an appropriate subscription and or resource group.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Duffney Thanks for the information.

@g0pinath Hope the above addresses your query. Please let us know if there are any further queries here. We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
