### ISSUE TITLE
Trouble with Sign in with a service principal

### ISSUE THREAD

**Issue by ChadSpears** [MicrosoftDocs/azure-docs-powershell#1686]
The section *Sign in with a service principal* is difficult to understand and does not seem to match with what is returned in PS7.
I ended up doing the following to get signed in.

![image](https://user-images.githubusercontent.com/50421823/104795348-91953200-577b-11eb-8c5d-50c8a569d417.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af19caa-4a7b-b347-7e45-e9cdc1325973
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-5.3.0)
* Content Source: [docs-conceptual/azps-5.3.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.3.0/authenticate-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ChadSpears Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikefrobbins Do you think we can clarify or improve this section further?

**Comment by ChadSpears** [comment]
Apologies, I was looking for a way to log into an existing service principal using a Key/Secret pair.
After reviewing the document today, I can see that the instructions are to login via Connect-AzAccount
 and then create a new service principal so that programmatic access can be utilized. I didn't run through the steps again with this new understanding, but I believe my misinterpretation of the objective is at fault.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ChadSpears Thank you for the response. Sure, please feel free to pass on any feedback that you think can improve the docs.

At this point, it appears that there are no edits or updates needed to the document in question. Hence closing this issue for now. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
