### ISSUE TITLE
Get a subscription's diagnostic settings categories' list

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-docs-powershell#1687]
How could one query the [`Diagnostic Settings Category - List`](https://docs.microsoft.com/en-us/rest/api/monitor/diagnosticsettingscategory/list#code-try-0) API using [`Invoke-AzRestMethod`](https://docs.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-5.3.0) to get the diagnostic settings categories' list of an Azure subscription?

![image](https://user-images.githubusercontent.com/17693249/104827359-70d3e780-5822-11eb-8898-cbc3146b1ac1.png)

The document doesn't tell how to specify the URL for the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67c32914-ce11-5002-31c2-28e083ed8dd7
* Version Independent ID: 472c79b6-d6c1-207b-ec17-e6f65d1ddbde
* Content: [Manage Azure resources with Invoke-AzRestMethod](https://docs.microsoft.com/en-us/powershell/azure/manage-azure-resources-invoke-azrestmethod?view=azps-5.3.0)
* Content Source: [docs-conceptual/azps-5.3.0/manage-azure-resources-invoke-azrestmethod.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.3.0/manage-azure-resources-invoke-azrestmethod.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by GiftA-MSFT** [comment]
@Ayanmullick we'll review your feedback and get back to you shortly. Thanks.

**Comment by HarshitaSingh-MSFT** [comment]
You are right, @Ayanmullick , after following the instructions and examples, I am not able to run this command. I am getting in touch with the PG and will let you know about the revert.

**Comment by mikefrobbins** [comment]
The URL should be specified as shown in the example of the reference doc for [Invoke-AzRestMethod](https://docs.microsoft.com/powershell/module/az.accounts/invoke-azrestmethod#example-1).

Something similar to the following example:
`Invoke-AzRestMethod -Path "/subscriptions/{subscription}/resourcegroups/{resourcegroup}/providers/microsoft.insights/diagnosticSettingsCategories?api-version=2017-05-01-preview" -Method GET`

**Comment by HarshitaSingh-MSFT** [comment]
@Ayanmullick , does the response from @mikefrobbins help?

**Comment by Ayanmullick** [comment]
No @HarshitaSingh-MSFT , I'm getting the error below. Could you share a screenshot if it's working at your end?
![image](https://user-images.githubusercontent.com/17693249/105080612-ae20bb00-5a56-11eb-9c25-f9609fd6874e.png)


@mikefrobbins , Does one need to specify the resource group for the diagnostics settings categories of a subscription?

**Comment by dcaro** [comment]
@Ayanmullick for diagnostics settings categories at the subscription level, you need to use the event category API.
The event category API is described here https://docs.microsoft.com/en-us/rest/api/monitor/eventcategories/list. If you are interested in the swagger definition (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/eventCategories_API.json) 

To use it with `Invoke-AzRestMethod` here is a sample code:

`Invoke-AzRestMethod -Path "/providers/microsoft.insights/eventcategories?api-version=2015-04-01" -Method GET`

The following code will return an array with all the categories:
`((Invoke-AzRestMethod -Path "/providers/microsoft.insights/eventcategories?api-version=2015-04-01" -Method GET).Content | ConvertFrom-Json).value`

**Comment by Ayanmullick** [comment]
Thanks for the update @dcaro. 
@mikefrobbins,  It is a documentation gap and not a bug after all :relaxed:
@HarshitaSingh-MSFT , I have what I was looking for. This can be closed. However, it could help others if it's documented that the methods listed in the page works for Azure resources except for subscriptions.

**Comment by HarshitaSingh-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by Ayanmullick** [comment]
Quick follow-up, @dcaro, Is there a separate Cmdlet to set the subscription-level diagnostics too? [`Set-AzDiagnosticSetting`](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings#create-using-powershell) works for other Azure resource types but not with subscriptions.

```Set-AzDiagnosticSetting -ResourceId /subscriptions/<SubId> -Categories Administrative,Security,ServiceHealth,Alert,Recommendation,Policy,Autoscale,ResourceHealth -WorkspaceId /subscriptions/<SubId>/resourcegroups/<RGName>/providers/microsoft.operationalinsights/workspaces/<Workspacename> -Enabled $true```  

fails with error below

`Set-AzDiagnosticSetting: Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null`

@mikefrobbins , @HarshitaSingh-MSFT, should one submit a separate issue?

**Comment by dcaro** [comment]
@Ayanmullick we already have an issue open for setting diagnostic settings at the subscription level: https://github.com/Azure/azure-powershell/issues/13066 
Please add your voice to the issue.
