### ISSUE TITLE
cls

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/azure-docs-powershell#1694]
Uninstall not working.  Any ideas?

PS C:\Users\me\adogit\Service-Gold\team-development\srb> Get-Module az -ListAvailable

    Directory: C:\Users\me\myplace\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.3.0                 Az                                  Core,Desk

PS C:\Users\me\adogit\Service-Gold\team-development\srb> Uninstall-Module Az
PS C:\Users\me\adogit\Service-Gold\team-development\srb> Get-Module az -ListAvailable

    Directory: C:\Users\me\myplace\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.3.0                 Az                                  Core,Desk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c3b0d7-748f-8dbd-bd90-4011e2df220e
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.4.0&source=docs)
* Content Source: [docs-conceptual/azps-5.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.4.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@JoeBrunsTR - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@JoeBrunsTR - Have you tried following the instructions on the page you have referenced. "Which method you follow depends on how you installed the Az module. If you're not sure of your original installation method, follow the MSI steps for uninstalling first." 
[https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.4.0&source=docs#uninstall-the-azurerm-module](url)

**Comment by MonikaReddy-MSFT** [comment]
@JoeBrunsTR - Have you tried the above suggested reference ?

**Comment by MonikaReddy-MSFT** [comment]
@JoeBrunsTR - 
Since we have not heard back from you we will now proceed to close this thread. 
If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
