### ISSUE TITLE
$PSVersionTable.PSEdition -eq 'Desktop' -and (Get-Module -Name AzureRM -ListAvailable) always true on windows 10

### ISSUE THREAD

**Issue by mchzh** [MicrosoftDocs/azure-docs-powershell#1698]
[Enter feedback here]
$PSVersionTable.PSEdition -eq 'Desktop' -and (Get-Module -Name AzureRM -ListAvailable) always return true on windows 10. So it cannot execute the installation for az module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb2106f-05d8-2a66-cc12-80652ed13c7c
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.4.0)
* Content Source: [docs-conceptual/azps-5.4.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.4.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@mchzh - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by mikefrobbins** [comment]
`$PSVersionTable.PSEdition -eq 'Desktop' -and (Get-Module -Name AzureRM -ListAvailable)` only returns `true` when run from Windows PowerShell with the AzureRM module installed. It is used to determine if the AzureRM module is installed. As stated in the installation instructions, "[We do not support having both the AzureRM and Az modules installed for PowerShell 5.1 on Windows at the same time.](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.4.0#install-the-azure-powershell-module)"

**Comment by MonikaReddy-MSFT** [comment]
@mikefrobbins  - Thank you for providing your insights.
@mchzh - I hope @mikefrobbins  has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
