### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Gt3pccb** [MicrosoftDocs/azure-docs-powershell#1723]
your scripts did not work on my environments
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.2.5      Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure ...
3.2.1      Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdle...
3.3.0      Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service data plane and management cmdlets...
4.5.0      Azure.Storage                       PSGallery            Microsoft Azure PowerShell - Storage service cmdlets. Manages blobs, queues, t...
2.5.0      AzureRM                             PSGallery            Azure Resource Manager Module
0.6.0      AzureRM.BootStrapper                PSGallery            Manage Modules for an Azure Version Profile. This allows selecting the Azure c...
4.6.1      AzureRM.Compute                     PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manage...
3.5.1      AzureRM.Dns                         PSGallery            Microsoft Azure PowerShell - Dns service cmdlets for Azure Resource Manager
5.1.5      AzureRM.Insights                    PSGallery            Microsoft Azure PowerShell - Insights service cmdlets for Azure Resource Manager
4.2.0      AzureRM.KeyVault                    PSGallery            Microsoft Azure PowerShell - KeyVault service cmdlets for Azure Resource Manager
5.0.1      AzureRM.Network                     PSGallery            Microsoft Azure PowerShell - Network service cmdlets for Azure Resource Manager
5.8.3      AzureRM.profile                     PSGallery            Microsoft Azure PowerShell - Profile credential management cmdlets for Azure R...
6.4.3      AzureRM.Resources                   PSGallery            Microsoft Azure PowerShell - Azure Resource Manager cmdlets.  Manages subscrip...
5.0.4      AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage service management cmdlets for Azure Reso...
4.0.2      AzureRM.Tags                        PSGallery            Microsoft Azure PowerShell - Tags service cmdlets for Azure Resource Manager
4.0.3      AzureRM.UsageAggregates             PSGallery            Microsoft Azure PowerShell - UsageAggregates service cmdlets for Azure Resourc...
5.0.1      AzureRM.Websites                    PSGallery            Microsoft Azure PowerShell - Websites service cmdlets for Azure Resource Manager
$m = Get-InstalledModule -Name az*
PS C:\Users\Administrator> $m | ForEach-Object {Uninstall-AzModule -Name $_.Name -Version $_.Version}
Uninstall-AzModule : Cannot validate argument on parameter 'Name'. The argument "Az.Accounts" does not belong to the set "Az,AzureRM,Azure"
specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:47
+ $m | ForEach-Object {Uninstall-AzModule -Name $_.Name -Version $_.Ver ...
+                                               ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Uninstall-AzModule], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Uninstall-AzModule

Uninstall-AzModule : Cannot validate argument on parameter 'Name'. The argument "Az.Resources" does not belong to the set "Az,AzureRM,Azure"
specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:47
+ $m | ForEach-Object {Uninstall-AzModule -Name $_.Name -Version $_.Ver ...
+                                               ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Uninstall-AzModule], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Uninstall-AzModule

Uninstall-AzModule : Cannot validate argument on parameter 'Name'. The argument "Az.Storage" does not belong to the set "Az,AzureRM,Azure" specified
by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:47
+ $m | ForEach-Object {Uninstall-AzModule -Name $_.Name -Version $_.Ver ...
+                                               ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Uninstall-AzModule], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Uninstall-AzModule

Uninstall-AzModule : Cannot validate argument on parameter 'Name'. The argument "Azure.Storage" does not belong to the set "Az,AzureRM,Azure"
specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:47
+ $m | ForEach-Object {Uninstall-AzModule -Name $_.Name -Version $_.Ver ...
+                                               ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Uninstall-AzModule], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Uninstall-AzModule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd192f26-d3eb-6413-2d1b-7b5d8b7c37f7
* Version Independent ID: e347850e-d4cd-89c2-edd3-2093315447b2
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azurerm/uninstall-azurerm-ps?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/uninstall-azurerm-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/uninstall-azurerm-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Gt3pccb Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Gt3pccb I see you're using `Uninstall-AzModule` as opposed to `Uninstall-AllModules` function defined in the provided script. Is that perhaps causing issues? As `Uninstall-AzModule` is not a supported cmdlet.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Gt3pccb Have you had a chance to check the above?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Gt3pccb We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
