### ISSUE TITLE
Uninstall-AzureRm should be Uninstall-Module AzureRm

### ISSUE THREAD

**Issue by BeMor81** [MicrosoftDocs/azure-docs-powershell#1726]
Uninstall-AzureRm should be Uninstall-Module AzureRm

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d1aafa-f084-6e0b-d743-7eb3aba81014
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.5.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-5.5.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.5.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BeMor81** [comment]
Sorry, this is correct but Uninstall-AzureRm didn't work for me

**Comment by BhargaviAnnadevara-MSFT** [comment]
@BeMor81 Thanks for reaching out.

Just to clarify, the [Uninstall-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/uninstall-module?view=powershell-7.1) cmdlet only uninstalls one module at a time. To remove the `AzureRm` PowerShell module completely, you must uninstall each module individually. Whereas, the [Uninstall-AzureRm](https://docs.microsoft.com/en-us/powershell/module/az.accounts/uninstall-azurerm?view=azps-5.5.0) cmdlet removes all `AzureRm` modules from a machine.

> Sorry, this is correct but Uninstall-AzureRm didn't work for me

Could you please elaborate and let us know the exact error you ran into?

As mentioned in the document in question, if you have the Az module installed on your system and would like to uninstall AzureRM, there are two options. Which method you follow depends on how you installed the AzureRM module.

If you installed AzureRM with PowerShellGet, then you can remove the modules with the Uninstall-AzureRM cmdlet, available as part of the `Az.Accounts` module. If you're not sure of your original installation method, follow the MSI steps for uninstalling first.
