### ISSUE TITLE
Definition of a rollup module not clear.

### ISSUE THREAD

**Issue by sabuncu** [MicrosoftDocs/azure-docs-powershell#1733]
In the section titled Install for All Users, it says:
"The Az module is a rollup module for the Azure PowerShell cmdlets."

The definition of a rollup module is not readily available and the search results point back to this page and an unrelated page for Power BI cmdlets.  It may help to define what it is.  Is it a meta module of many other modules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9df8e19-9322-ee7c-21e3-c9cb115f13c9
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.6.0)
* Content Source: [docs-conceptual/azps-5.6.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.6.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@sabuncu Thank you for your question.  We are looking into this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@sabuncu A rollup refers to the combination of smaller elements into a single, larger element (JavaScript, for example, has a similar concept of rollup).  In this case, the best definition is a little bit further in the documentation:

"Installing [Az module] downloads all of the generally available Az PowerShell modules, and makes their cmdlets available for use."

**Comment by kobulloc-MSFT** [comment]
@sabuncu Thank you for reaching out to us!  We're going to close this issue as resolved but feel free to tag me in your reply and we can continue the conversation.
