### ISSUE TITLE
APIMgmt in-policy token extraction

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-docs-powershell#1734]
Can the [token extraction code](https://docs.microsoft.com/en-us/azure/api-management/api-management-sample-send-request#extracting-the-token) be written in PowerShell? 

The suggestion below is still 'Under Review'.
[API Mgmt. policy management PowerShell module](https://feedback.azure.com/forums/248703-api-management/suggestions/34518523-api-mgmt-policy-management-powershell-module)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70c1f08-ac94-5cd1-f1fd-57548c0124da
* Version Independent ID: 978fef6b-dea0-55b1-85fd-d7d81c754741
* Content: [Using API Management service to generate HTTP requests](https://docs.microsoft.com/en-us/azure/api-management/api-management-sample-send-request#extracting-the-token)
* Content Source: [articles/api-management/api-management-sample-send-request.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/api-management/api-management-sample-send-request.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Ayanmullick Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by mikefrobbins** [comment]
@Ayanmullick Thank you for the input, since this is a docs repo and the issue does not appear to be docs related, I will proceed with closing this issue. Feel free to follow-up with a [discussion item](https://github.com/Azure/azure-powershell/discussions) in the azure-powershell repo for our engineering team.

**Comment by Ayanmullick** [comment]
@mikefrobbins, I submitted https://github.com/Azure/azure-powershell/discussions/14536
