### ISSUE TITLE
what to do for the cases marked as manual uninstall required

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/azure-docs-powershell#1735]
per my knowledge some of the modules are not being actively used on my desktop, why i am seeing manual uninstall required? what should i do? i have closed powershell, vscode, visual studio on my desktop, still see these warnings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ef5b0-5677-5dc0-e9d5-070242170690
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.6.0)
* Content Source: [docs-conceptual/azps-5.6.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-5.6.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mganeshphani Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mganeshphani Could you please provide a screenshot of the warnings you see?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mganeshphani Is there any further information or update that you can provide on the issue?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mganeshphani We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
