### ISSUE TITLE
Non-existing "-Force" parameter in Remove-AzureRMAutomationVariable example

### ISSUE THREAD

**Issue by fallmake** [MicrosoftDocs/azure-docs-powershell#1738]
There's no github linking on docs.microsoft.com for "azure-docs-powershell/azurermps-6.13.0/AzureRM.Automation/Remove-AzureRMAutomationVariable.md", hence the manually created issue.

See: https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/remove-azurermautomationvariable?view=azurermps-6.13.0#example-1--remove-a-variable

**Example 1: Remove a variable** and it's description text make use of a _-Force_ parameter. This parameter is not otherwise documented on the same page and isn't implemented:

Remove-AzureRmAutomationVariable : A parameter cannot be found that matches parameter name 'Force'. At line:155 char:123 + ... tomationAccount -ResourceGroupName $ResourceGroup -name $example -Force + ~~~~~~ + CategoryInfo : InvalidArgument: (:) [Remove-AzureRmAutomationVariable], ParameterBindingException + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Automation.Cmdlet.RemoveAzureAutomationVariable

**Comment by BhargaviAnnadevara-MSFT** [comment]
@fallmake Thanks for the feedback. We're investigating this and will get back to you shortly.
