### ISSUE TITLE
Multi-container Webapp

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-docs-powershell#1748]
Is there PowerShell documentation on how to deploy a multi-container Webapp and how to establish communication between the two containers?

I couldn't find anything related to containers in the [samples](https://docs.microsoft.com/en-us/azure/app-service/samples-powershell).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9d9048-6577-c19b-5989-fef8beffd6f6
* Version Independent ID: b01b315d-2cf8-f1ec-215a-4bf1c220d840
* Content: [Tutorial: Create a multi-container app - Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/tutorial-multi-container-app)
* Content Source: [articles/app-service/tutorial-multi-container-app.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/app-service/tutorial-multi-container-app.md)
* Service: **app-service**
* GitHub Login: @msangapu-msft
* Microsoft Alias: **msangapu**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Ayanmullick Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by mikefrobbins** [comment]
@BhargaviAnnadevara-MSFT Can this issue be moved to the [azure-docs repo](https://github.com/MicrosoftDocs/azure-docs) since that is where the referenced article resides?

The author of that particular article may not respond to the issue in this repo.

@Ayanmullick For future reference, clicking on the "Submit and view feedback for 'This page'" is the best way to make sure your issue is properly triaged. The owner of the article will reach out to the Azure PowerShell team if they need our assistance.
![image](https://user-images.githubusercontent.com/6719572/113717996-d4e3aa80-96b1-11eb-8c03-63499be38647.png)

**Comment by Ayanmullick** [comment]
> @BhargaviAnnadevara-MSFT Please move this issue to the [azure-docs repo](https://github.com/MicrosoftDocs/azure-docs) since that is where the referenced article resides.
> 
> The author of the referenced article may not respond to the issue in this repo.
> 
> @Ayanmullick For future reference, clicking on the "Submit and view feedback for 'This page'" is the best way to provide documentation related feedback. The owner of the article will reach out to the Azure PowerShell team if they need our assistance.
> ![image](https://user-images.githubusercontent.com/6719572/113717996-d4e3aa80-96b1-11eb-8c03-63499be38647.png)

@mikefrobbins , I created the issue in this repository since it's related to a documentation gap with the Az.Websites PowerShell module. I thought this repo was specific to Az modules. I have been asked to contact the PowerShell team directly since that repository is generic to all documentation.

**Comment by mikefrobbins** [comment]
The referenced GitHub issue was for a product related issue, not a docs one. For docs related issues, they should always be logged in the repo where the articles resides. Most service teams have their own content developers who own their specific content. They will reach out to us if they need our assistance.
