### ISSUE TITLE
Set boot diagnostics to managed storage account

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-docs-powershell#1749]
How could one set the the Boot diagnostics to the `recommended` option of `managed storage account`?

![image](https://user-images.githubusercontent.com/17693249/112401719-27e45780-8cd9-11eb-9631-4afc83f22fe8.png)

---
#### Document Details

* ID: 9A6F140C-9F1C-4701-9603-FC6107FCAF92
* Content: [Set-AzVMBootDiagnostic](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbootdiagnostic?view=azps-5.7.0)
* Content Source: [azure-powershell/src/Compute/Compute/help/Set-AzVMBootDiagnostic.md](https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/Set-AzVMBootDiagnostic.md)
* Service: **virtual-machines**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Ayanmullick Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by mikefrobbins** [comment]
It's not currently possible. There is [a feature request](https://github.com/Azure/azure-powershell/issues/13168) already logged for the engineering team in the appropriate repo to add this ability.
