### ISSUE TITLE
Start and end times need to be dd/mm/yyyy or mm/dd/yyyy format

### ISSUE THREAD

**Issue by mattcowen** [MicrosoftDocs/azure-docs-powershell#1770]
Calling Get-AzsSubscriberUsage with the format shown in the examples in this page leads to an error regarding invalid ISO format. The start and end time must be date format only with no time specified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1eeb40-3555-fcba-5b64-02b319302aac
* Version Independent ID: 171e19fa-d3b8-46df-faf7-a0010a2546cd
* Content: [Get-AzsSubscriberUsage (Azs.Commerce.Admin)](https://docs.microsoft.com/en-us/powershell/module/azs.commerce.admin/get-azssubscriberusage?view=azurestackps-2.0.2)
* Content Source: [azurestackps-2.0.2/Azs.Commerce.Admin/Get-AzsSubscriberUsage.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azurestackps-2.0.2/Azs.Commerce.Admin/Get-AzsSubscriberUsage.md)
* Service: **azure-powershell**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @mattcowen , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by mattbriggs** [comment]
@mattcowen Thanks for your comment. I'll review the topic and update.

#in-progress

**Comment by mattcowen** [comment]
@mattbriggs i found the following not to work

`Get-AzsSubscriberUsage -ReportedStartTime "2019-12-30T00:00:00Z" -ReportedEndTime "2019-12-31T00:00:00Z" -AggregationGranularity Daily`

this does work...

`Get-AzsSubscriberUsage -ReportedStartTime "12/30/2019" -ReportedEndTime "12/31/2019" -AggregationGranularity Daily`

And if the AggregationGranularity is Hourly then the following does work

`Get-AzsSubscriberUsage -ReportedStartTime "12/30/2019 15:00" -ReportedEndTime "12/31/2019 16:00" -AggregationGranularity Hourly`

**Comment by mattcowen** [comment]
and we should state somewhere that the format must be mm/dd/yyyy

**Comment by mattbriggs** [comment]
@mattcowen I have a question out. Thanks for your update.

**Comment by mattbriggs** [comment]
Updated

#please-close
