### ISSUE TITLE
Unable to install with given command line

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/azure-docs-powershell#1810]
[Installation instructions](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.0.0#installation) say `scope=currentuser` should (seemingly) avoid the need for an Administrator session of Powershell. However:

```
> Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Administrator rights are required to install or update. Log on to the computer with an account that has Administrator rights, and then try again, or install by adding "-Scope CurrentUser"
     | to your command. You can also try running the Windows PowerShell session with elevated rights (Run as Administrator).
```

I then went on to attempt installation in an Administrator Powershell which also fails both with and without the `Scope` parameter:

![image](https://user-images.githubusercontent.com/20270743/120520907-3742e980-c389-11eb-8bf1-c1edf3453932.png)

![image](https://user-images.githubusercontent.com/20270743/120521131-72ddb380-c389-11eb-9525-ac3ccfe3d56f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4e5ed1-394b-6575-5801-424dc3e5f75d
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install the Azure Az PowerShell module with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.0.0#troubleshooting)
* Content Source: [docs-conceptual/azps-6.0.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.0.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft Thank you for bringing this to our attention.  We are investigating this and will get back to you shortly.

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft I created a new Windows 10 VM and [installed PowerShell 7](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1) on it (Windows / [PowerShell 7.1.3 x64 MSI](https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi)).  The command worked for my repro so I'm curious what the differences might be in our two setups.

![image](https://user-images.githubusercontent.com/37556655/120569962-e56f8300-c3cb-11eb-822b-5f75914f9b75.png)

![image](https://user-images.githubusercontent.com/37556655/120569980-ee605480-c3cb-11eb-887b-a6122d7b9502.png)

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft I get the same results when I run `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber`.  I noticed that you're using PowerShell Core.  What happens if you use a fresh install of PowerShell 7?

**Comment by brandonh-msft** [comment]
Thanks for digging in @kobulloc-MSFT ! What happens if you _don't_ use Administrator Powershell? Docs seem to allude this to not be required (and would potentially lock out some users if it was).

Regarding PSCore vs PSW that I'm not sure of. I honestly thought that PS7 and PSCore were the same thing 😄

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft No worries!  I tried running the same command without administrator privileges (as that is a very good question) and that worked for me as well.

At this point I suspect it has to do with the original installation of PowerShell.  We don't appear to have a brief rundown of the PowerShell history in the docs (which is a shame) but there are 3 noteworthy versions of PowerShell:

- **Windows PowerShell** (up to 5.1):  The "classic" version of PowerShell that you'll find in older installations of Windows 10.
- **PowerShell Core** (up to 6.2):  PowerShell Core is a cross-platform and open source version of PowerShell released in 2018 that could do most of the things Windows PowerShell could do but not quite everything.  This was effectively PowerShell 6.
- **PowerShell** (up to 7.1):  PowerShell 7 is the current version of PowerShell.  It is also cross-platform and is much more in line with Windows PowerShell along with several new features including default support for the Azure Az module.  This is a separate release from PowerShell Core and more than just a version upgrade.

(I don't believe any of this is commonly known and there are a number of blogs dedicated to explaining the confusing history.)

I believe that a fresh install of PowerShell 7 will unblock you and will likely make things run much smoother moving forward.  Let me know if you run into any issues!

![image](https://user-images.githubusercontent.com/37556655/120706237-b1e53500-c46d-11eb-8510-4896c94930f1.png)

![image](https://user-images.githubusercontent.com/37556655/120706274-bc073380-c46d-11eb-9dcb-12af4e391ac4.png)

**Comment by brandonh-msft** [comment]
ok in that case I'm not running PSCore, I'm on PS7 as shown by the first line of my screenshot ... 🤔

I can try reinstalling powershell then.

**Comment by kobulloc-MSFT** [comment]
If that doesn't work, let me know and we can troubleshoot this some more.  My hope is that a fresh install is all you need.

**Comment by brandonh-msft** [comment]
In fact I do have PS7; I downloaded the installer and was met with this:
![image](https://user-images.githubusercontent.com/20270743/120710969-ac8ae900-c473-11eb-8a79-d1cf52578152.png)

I've issued 'Repair' and will see what happens.

**Comment by brandonh-msft** [comment]
Just ran the command in both Windows Terminal PS 7.1.3 and PS 7.1.3 straight up. Same results in both:

![image](https://user-images.githubusercontent.com/20270743/120711873-bf51ed80-c474-11eb-9685-4e5fcca70814.png)

**Comment by kobulloc-MSFT** [comment]
Thank you for the update.  I'll do some more investigation and see what I come up with.

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft It looks like [others have run into this issue](https://github.com/PowerShell/PowerShell/issues/12777) as well.  I would try installing through the MSI:
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-6.0.0#install-or-update-on-windows-using-the-msi-package

**Comment by kobulloc-MSFT** [comment]
@brandonh-msft This appears to be a product issue.  I'm going to close this GitHub issue as there doesn't appear to be anything we can do from a documentation standpoint and follow up with a bug for tracking if that looks like it is appropriate.

**Comment by kobulloc-MSFT** [comment]
It looks like the conversation has moved to https://github.com/PowerShell/PowerShell/issues/12777.

I'll include this there but there are two other scenarios to be aware of:

Az module falsely throws Admin rights required error:
(Trying to install az module when it already exists)
https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2102#error-thrown-when-installing-the-az-modules

- Applicable: This issue applies to 2002 and later
- Cause: When installing the module from an elevated prompt, an error is thrown. The error says, Administrator rights required.
- Remediation: Close your session and start a new elevated PowerShell session. Make sure there isn't an existing Az. Accounts module loaded in the session.
- Occurrence: Common

Someone working with the AZ modules to work against a private cloud may want to run the modules in an isolated environment such as a container.

You can find instructions here:
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-user-docker?view=azs-2102&tabs=az
