### ISSUE TITLE
How about a screenshot or two?

### ISSUE THREAD

**Issue by Axilla-the-HUN** [MicrosoftDocs/azure-docs-powershell#1823]
Once again, i am signing in and complaining about your documentation. It's thin and pretty weak to say the least. My job is to decipher your unexplained processes and cobble together the correct way to do it for customers who don't speak your cryptic Microsoft runes.  After 20 years using Rosetta stones I have gathered in piles of One Note and Notepad Powers-hell garbage collecting I have finally had it. If you need engineers like myself to constantly use online repositories in order to get connected to Azure powershell functionality...please make the sample powershell work and also provide a clearer picture how to do it. This page is filled with mistakes and incorrect code and links to other how to guides that don't work. After the hell of techdocs and the vast improvement in microsoft DOCs I kind of expect better. It's 2021, include some pictures in your guides. Instead of me having to Sherlock your insufferable PowerShell examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567330d4-c5e5-9009-b023-8347f5c20059
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install the Azure Az PowerShell module with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.1.0)
* Content Source: [docs-conceptual/azps-6.1.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.1.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
Please elaborate on the problems with the referenced page as it contains no invalid links, mistakes, or incorrect code that we're aware of.

**Comment by kobulloc-MSFT** [comment]
@Axilla-the-HUN When I was starting out, [PowerShell 101](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.1) (by our own @mikefrobbins ) was very helpful and to your point the screenshots were especially useful in getting through those first couple steps.  @mikefrobbins I'll send some screenshots I think will be helpful for readers.

**Comment by Axilla-the-HUN** [comment]
Why do the repositories show up as untrusted? From my customer network I can't download or install the basic command to Install the Azure AD module. It fails getting the repository. Install-Module -Name AzureAD doesn't work. The list of NuGet providers doesn't work (unable to find the package provider 'NuGet'). Could the linkage to these repositories be trusted and available on the Microsoft download system.  There has to be a better way to do this, some type of wrapped installer or .NET something. I don't want a NuGet server, I just want to connect a single instance of PowerShell to control this customers O365.

Then I switched gears to download the MSI file and install that, well it needed .NET which = a reboot. There is no cohesive end to end documentation to explain all of the steps. You leave out the most important information therefore it's incomplete.
 
This command doesn't work 
(Get-Item C:\Windows\System32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.Online.Administration.Automation.PSModule.dll).VersionInfo.FileVersion

**Comment by mikefrobbins** [comment]
Since PowerShell is text based, screenshots provide little value as shown in the following screenshot.
![image](https://user-images.githubusercontent.com/6719572/123989915-efff4700-d98e-11eb-8ecd-d7734a051a0b.png)

Both input and output can be expressed in a text representation on the webpage without the need for screenshots.
```powershell
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```

The only difference in the two is the commands shown in screenshots can't be copied and pasted by the reader and they aren't indexed by search engines.

**Comment by mikefrobbins** [comment]
> Why do the repositories show up as untrusted?

This isn't something controlled by Azure PowerShell. Looping in @sdwheeler who can speak to this from a PowerShell docs point of view.

> From my customer network I can't download or install the basic command to Install the Azure AD module. It fails getting the repository. Install-Module -Name AzureAD doesn't work. The list of NuGet providers doesn't work (unable to find the package provider 'NuGet'). Could the linkage to these repositories be trusted and available on the Microsoft download system. There has to be a better way to do this, some type of wrapped installer or .NET something. I don't want a NuGet server, I just want to connect a single instance of PowerShell to control this customers O365.

This GitHub repo is for Azure PowerShell inlcuding the Azure, AzureRM, Az, and Azure Stack PowerShell modules. AzureAD and Office 365 PowerShell modules are supported in other repos. @kobulloc-MSFT Can you provide the information on where to report issues for those modules?

**Comment by kobulloc-MSFT** [comment]
@mikefrobbins I'll look into where those issues should be reported.

**Comment by kobulloc-MSFT** [comment]
@Axilla-the-HUN It appears that this intentional not because the PowerShell Gallery is untrusted but because the goal is to prevent users from installing any module or script (even from Microsoft) without first verifying that is really what they want to do:

https://github.com/Azure/azure-powershell/issues/9687#issuecomment-513004901

> Hey there, I'm going to assume that this issue is about the prompt that is popped when installing a module from the PowerShell Gallery -- the PowerShell Gallery is set as an "untrusted repository" by default to prevent users from installing any module or script from this open gallery without first verifying that they are sure they want to install the given module or script; this applies even for Microsoft-developed modules, such as Az. To bypass this prompt in the cases that you're confident the module or script you're installing is safe, you can provide the -Force parameter:
> 
> `Install-Module -Name Az -Repository PSGallery -Force`
> 
> You can also set the PSGallery repository to "trusted" to avoid this prompt altogether, but it's advised to keep the repository as it is.

I created a fresh VM and went through the installation process which you can see below:

![image](https://user-images.githubusercontent.com/37556655/124000009-fccc6c80-d987-11eb-9693-abe8333d5ea0.png)

**Comment by mikefrobbins** [comment]
Docs for both the MSOnline and AzureAD PowerShell modules are supported in the [azure-docs-powershell-azuread](https://github.com/Azure/azure-docs-powershell-azuread) GitHub repo. Please log an issue in that repo for any issues related to docs for either of those modules.
