### ISSUE TITLE
https://github.com/users/Perfumiste777/projects/1

### ISSUE THREAD

**Issue by Perfumiste777** [MicrosoftDocs/azure-docs-powershell#1839]
[Should be a better commitment with the payment method/Pre Prepaid cards are as safe as the Deposit card ,both have a Governmental trust.I do work about it will you.?There is an official acceptance in E.U about the way our personal Details are used.
What is this make your Company violate the rules against E.U Citizens Rights to rule their money or a part of their Right ,is the one my Source focus at.https://github.com/Perfumiste777].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1841e4cc-3b80-03b9-cb4b-b8ba941e545a
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-0.10.0)
* Content Source: [docs-conceptual/azps-0.10.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-0.10.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@Perfumiste777 For billing related issues you'll want to refer to the [Cost Management and Billing documentation](https://docs.microsoft.com/en-us/azure/cost-management-billing/), contact billing support (Portal > Help + support > New support request > Billing, then complete the wizard), or you'll want to [leave feedback](https://feedback.azure.com/forums/170030-signup-and-billing) for the product teams to review.

Pay by invoice may be an option that you would like to learn more about that allows customers to pay by check or wire transfer:
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/pay-by-invoice

There's nothing we can do here in the Azure PowerShell section of our documentation so we are going to close this issue as resolved.  If you have any questions about Azure PowerShell, please open another issue and we'd be happy to help!
