### ISSUE TITLE
Uninstall commands fail due to PowerShell bug

### ISSUE THREAD

**Issue by theonlycoder** [MicrosoftDocs/azure-docs-powershell#1841]
Hi all,

I have just tried using the instructions under the heading _"Option 2: Uninstall the Az PowerShell module from PowerShellGet"_ to uninstall the `Az` PowerShell module. However, The first command (see below) fails to retrieve anything despite the fact the `Az` module is present on the machine. However, if I pass `Az*` as the `-Name` parameter it does return all the `Az.[Something]` sub-modules.

`Get-Module -Name Az -ListAvailable -OutVariable AzVersions`

I did some investigation and it seems this is due to a known issue in Windows PowerShell 5.1 where `Get-Module` fails to enumerate any module with the name `Az` due to the string "Az" also being a region identifier. I have only skimmed the issue and so am not familiar with all the details, but here it is: https://github.com/Azure/azure-powershell/issues/7553. Also see PowerShell bug https://github.com/PowerShell/PowerShell/issues/8125. Also see various linked issues/PRs.

It seems a fix has been developed, but won't be included in PowerShell 5.x as that branch is now frozen other than essential fixes. I did try `Get-Module` in PowerShell 7 and that does enumerate the `Az` module. However, I hit other issues and so did a bit more digging. Eventually I came across the new `Az.Tools.Installer` module, which automates the uninstall process. This worked perfectly and was much more straightforward than the steps in this article. See here: https://techcommunity.microsoft.com/t5/azure-tools/introduction-to-az-tools-installer/ba-p/1697622

Would it make sense to at least put a note on the docs to indicate it may not work in 5.x due to the bug and is unlikely to be fixed? Alternatively, would it make sense to update the documentation to use the `Az.Tools.Installer` module instead as that seems to work well and is much more straightforward?

As a side note, I think the PowerShell bug I mentioned may be the root cause of the issue mentioned here: https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1772

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d5b384-fcac-409c-f1dd-6eda94c2274d
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-6.2.1)
* Content Source: [docs-conceptual/azps-6.2.1/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.2.1/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by kobulloc-MSFT** [comment]
@theonlycoder Thank you very much for bringing this to our attention (and for providing the results of your investigation).  We are assigning this to the document author for review.

**Comment by mikefrobbins** [comment]
@theonlycoder I've confirmed that this is indeed an issue with Windows PowerShell 5.1.

**Comment by mikefrobbins** [comment]
@theonlycoder The uninstallation article has been updated to use `Get-InstallModule` which works in Windows PowerShell instead of `Get-Module`. Once the `Az.Tools.Installer` module becomes GA, the articles will be updated to use it.

**Comment by theonlycoder** [comment]
@mikefrobbins sounds good to me! I appreciate the point about the new module not being GA yet; to be honest I hadn't noticed. Thanks for taking the feedback on board and updating the article so quickly.
