### ISSUE TITLE
Installing the Az module does not include Az.Search

### ISSUE THREAD

**Issue by swettstein** [MicrosoftDocs/azure-docs-powershell#1847]
The Az module contains almost all of the other Az.* modules except Az.Search. Why is it not included? Are there other Az.* modules not included as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3343dd4-11be-72fd-1cc9-e081b4ffbb35
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install the Azure Az PowerShell module with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.2.1)
* Content Source: [docs-conceptual/azps-6.2.1/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.2.1/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @swettstein , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by mikefrobbins** [comment]
@swettstein Only GA (generally available) modules are installed as part of the Az PowerShell module. Non-GA modules (Az modules less than version 1.0) have to be installed separately. We recently announced a new module, [AzPreview](https://www.powershellgallery.com/packages/AzPreview/) that includes both GA and preview modules as a single install. See our [July 2021 - Azure PowerShell updates](https://techcommunity.microsoft.com/t5/azure-tools/july-2021-azure-powershell-updates/ba-p/2539401) article for more information.
