### ISSUE TITLE
AllowClobber not specified for Installation of Azure Az PowerShell module on Windows PowerShell

### ISSUE THREAD

**Issue by Viajaz** [MicrosoftDocs/azure-docs-powershell#1874]
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.3.0#installation-on-windows-powershell
-should specify that `-AllowClobber` needs to be used to prevent error:
```
PackageManagement\Install-Package : The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'Az.Accounts' may override the
existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.
```

This issue is similar to https://github.com/Azure/azure-powershell/issues/2916

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc294cf9-671e-dc74-2f74-90a775cb0187
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install the Azure Az PowerShell module with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.3.0)
* Content Source: [docs-conceptual/azps-6.3.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.3.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Viajaz Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by mikefrobbins** [comment]
@Viajaz Can you provide the output of the following:

```powershell
Get-InstalledModule -Name Az, AzureRm -ErrorAction SilentlyContinue |
Select-Object -Property Name, Version, Repository, @{label='PSVersion';expression={$PSVersionTable.PSVersion}}
```

The similar issue that was linked is for a different older module (Azure) which is for the classic service management deployment model instead of Azure Resource Manager.

**Comment by Viajaz** [comment]
@mikefrobbins I understand it was for a different module, just saying it's a similar issue for context.

```
Name    Version Repository PSVersion
----    ------- ---------- ---------
Az      6.3.0   PSGallery  5.1.19041.1151
AzureRM 6.13.2  PSGallery  5.1.19041.1151
```

**Comment by mikefrobbins** [comment]
@Viajaz Please see the [Az and AzureRM coexistence](https://docs.microsoft.com/powershell/azure/install-az-ps#az-and-azurerm-coexistence) section of the Azure PowerShell installation documentation.

**Comment by Viajaz** [comment]
@mikefrobbins Looks like I should have scrolled down, perhaps it's worth adding a mention to the https://docs.microsoft.com/en-gb/powershell/azure/install-az-ps?view=azps-6.3.0#installation-on-windows-powershell section too?

**Comment by mikefrobbins** [comment]
@Viajaz I've added an important note to the installation section that says see the AzureRM coexistence section of the article if you have the AzureRM PowerShell module installed.
