### ISSUE TITLE
Not at all clear documentation. 

### ISSUE THREAD

**Issue by Raag007** [MicrosoftDocs/azure-docs-powershell#1877]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b963d11-ab7f-b257-2ec2-89e1327f1b0a
* Version Independent ID: dc1846a2-4d0a-fd2b-ecd1-1670435e86b6
* Content: [Set-AzNetworkSecurityRuleConfig (Az.Network)](https://docs.microsoft.com/en-us/powershell/module/az.network/set-aznetworksecurityruleconfig?view=azps-6.3.0)
* Content Source: [src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md](https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md)
* Service: **virtual-network**
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @Raag007 , thanks for the question! We are taking a look into this and will get back to you soon. Can you tell me what is not clear in the documentation?

**Comment by HarshitaSingh-MSFT** [comment]
Hello!
Just checking to see if you have had a chance to see the previous response.

**Comment by dcaro** [comment]
@HarshitaSingh-MSFT can you please transfer this issue to the source repo: https://github.com/Azure/azure-powershell.

**Comment by Raag007** [comment]
Hi @HarshitaSingh-MSFT - 

On your sandbox, when you get a chance please try to run these commands provided in this document. 

```
$nsg = Get-AzNetworkSecurityGroup -Name "NSG-FrontEnd" -ResourceGroupName "TestRG"
$nsg | Get-AzNetworkSecurityRuleConfig -Name "rdp-rule"
Set-AzNetworkSecurityRuleConfig -Name "rdp-rule" -NetworkSecurityGroup $nsg -Access "Deny"

```

**Comment by HarshitaSingh-MSFT** [comment]
We will close this out, but if you feel you need more information please just let us know. We will now close this issue in GitHub but hope to engage with you via our GitHub issue shared above.
