### ISSUE TITLE
Translated Address

### ISSUE THREAD

**Issue by krhill81** [MicrosoftDocs/azure-docs-powershell#1895]
[Enter feedback here]
New-AzFirewallPolicyNatRuleCollection does not actually accept -TranslatedAddress and -TranslatedPort as parameters, which makes sense.  In the Syntax it is a configurable variable, since it is not supported should this show here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc44d048-363a-a389-c7c1-d7d7353e1fd7
* Version Independent ID: 6a28535c-7b0b-f8d7-31a4-5ae698dee8e6
* Content: [New-AzFirewallPolicyNatRuleCollection (Az.Network)](https://docs.microsoft.com/en-us/powershell/module/az.network/new-azfirewallpolicynatrulecollection?view=azps-6.3.0)
* Content Source: [src/Network/Network/help/New-AzFirewallPolicyNatRuleCollection.md](https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzFirewallPolicyNatRuleCollection.md)
* Service: **virtual-network**
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @krhill81 
Thank you for your feedback! We will review and update as appropriate.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @krhill81 
We [have proposed ](https://github.com/Azure/azure-powershell/pull/15894) the suggested changes to the document, which are currently under doc author's review. We will now proceed to close this issue out. Please tag me in your response if there are any additional concerns. Thank you!
