### ISSUE TITLE
Azure Firewall policy variable

### ISSUE THREAD

**Issue by krhill81** [MicrosoftDocs/azure-docs-powershell#1896]
[Enter feedback here]
Set-AzFirewallPolicyRuleCollectionGroup does not take in -AzureFirewallPolicy with AzureFirewallPolicy object and instead expects -FirewallPolicyName with string value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777f3765-ab03-a9ba-fd73-f5987795420e
* Version Independent ID: 1c0657cd-d941-b25a-83a0-e87969e264e1
* Content: [Set-AzFirewallPolicyRuleCollectionGroup (Az.Network)](https://docs.microsoft.com/en-us/powershell/module/az.network/set-azfirewallpolicyrulecollectiongroup?view=azps-6.3.0)
* Content Source: [src/Network/Network/help/Set-AzFirewallPolicyRuleCollectionGroup.md](https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Set-AzFirewallPolicyRuleCollectionGroup.md)
* Service: **virtual-network**
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @krhill81 
Thank you for your feedback! We will review and update as appropriate.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @krhill81
We have [proposed](https://github.com/Azure/azure-powershell/pull/15895) the suggested changes to the document, which are currently under doc author's review. We will now proceed to close this issue out. Please tag me in your response if there are any additional concerns. Thank you!
