### ISSUE TITLE
The uninstallation script is much slower than direct file deletion

### ISSUE THREAD

**Issue by jiasli** [MicrosoftDocs/azure-docs-powershell#1912]
I used the provided script to uninstall Azure PowerShell:

```pwsh
$AzModules |
  ForEach-Object {
    Remove-Module -Name $_ -ErrorAction SilentlyContinue
    Write-Output "Attempting to uninstall module: $_"
    Uninstall-Module -Name $_ -AllVersions
  }
```

But the uninstallation is extremely slow.

Alternatively, I got the location of modules with 

```pwsh
Get-Module -ListAvailable Az*

    Directory: C:\Users\user1\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     6.4.0                 Az                                  Core,Desk
Script     2.5.3                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfigura…
Script     2.4.0                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, Import-AzAksCredential…}

```

Then delete everything with

```pwsh
Remove-Item -Recurse -Force C:\Users\user1\Documents\PowerShell\Modules\Az*
```

This is much faster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a2bfe1-b332-e523-007b-5216111343ca
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-6.4.0#feedback)
* Content Source: [docs-conceptual/azps-6.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.4.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@jiasli - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by mikefrobbins** [comment]
@jiasli While the command you provided is indeed much faster, it would remove any PowerShell module the user has installed in the current user scope that begins with `Az`, not just the ones installed by the Az PowerShell module.

The code provided in the official documentation determines what modules were installed based on the hidden XML file in the module's directory and then iterates through them, performing the uninstallation.

We are open to ideas for improving the uninstallation process, but it must accurately uninstall only the modules that were installed by the Az PowerShell module.
