### ISSUE TITLE
What is the roadmap towards Azure AD Graph API free?

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-docs-powershell#1955]
I guess it is good to add a note to the documentation with regards to becoming fully Azure AD Graph API free.

Is the stable version of Az.Resources already Azure AD Graph API free? 

During Ignite there was an announcement with a call to action to test out the latest prelease which contains a full move to Microsoft Graph API:

https://techcommunity.microsoft.com/t5/azure-tools/azure-powershell-ignite-release/ba-p/2907139

I am confused. Now it seems that there are still Azure AD Graph APIs being called in the stable version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769e99f9-0175-083c-f084-d823233b5ba3
* Version Independent ID: 8f52d00e-14b5-7fce-c982-2d28b66403f7
* Content: [Azure AD to Microsoft Graph migration changes in Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azps-msgraph-migration-changes?view=azps-6.6.0)
* Content Source: [docs-conceptual/azps-6.6.0/azps-msgraph-migration-changes.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.6.0/azps-msgraph-migration-changes.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by GiftA-MSFT** [comment]
@cveld we'll review your feedback and get back to you shortly. Thanks.

**Comment by cveld** [comment]
I am not sure if your pointer is helpful. My question is really asking about clarification: 
* is 5.0.0-preview the only version that is providing a non Azure AD Graph implementation currently?
* 4.4.1; the latest stable therefore is still using Azure AD Graph.

https://www.powershellgallery.com/packages/Az.Resources

**Comment by mikefrobbins** [comment]
> I am not sure if your pointer is helpful. My question is really asking about clarification:
> 
> * is 5.0.0-preview the only version that is providing a non Azure AD Graph implementation currently?
> * 4.4.1; the latest stable therefore is still using Azure AD Graph.
> 
> https://www.powershellgallery.com/packages/Az.Resources

Correct for both questions.

**Comment by mikefrobbins** [comment]
The non Azure AD Graph implementation will become generally available with our next major release of the Az PowerShell module, version 7.x in December of 2021.
