### ISSUE TITLE
on my enviromment i have to use -SkipPublisherCheck to work.

### ISSUE THREAD

**Issue by gilbertto10** [MicrosoftDocs/azure-docs-powershell#1961]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92d4b1f6-1862-e6c9-f102-86daf4298e1f
* Version Independent ID: c6b88fad-dfa9-e0b4-b3ed-7b889c32d813
* Content: [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.6.0)
* Content Source: [docs-conceptual/azps-6.6.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-6.6.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by PramodValavala-MSFT** [comment]
@gilbertto10 Looks like you have closed this issue soon after closing it. I hope whatever issue you had; you were able to resolve.
