### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by michael-vella** [MicrosoftDocs/azure-docs-powershell#2018]
In the **Features** section, under Security and stability, there is a bracket (coming in 2021). This is the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842d35f3-bca4-de44-cd9e-5c81798fdb17
* Version Independent ID: a1a4e76d-f614-b29b-8b74-283aa1315a9e
* Content: [Introducing the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-7.1.0)
* Content Source: [docs-conceptual/azps-7.1.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.1.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@michael-vella - Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
