### ISSUE TITLE
trailing curly bracket on the Start-Job example

### ISSUE THREAD

**Issue by HoLengZai** [MicrosoftDocs/azure-docs-powershell#2041]
The code example show this:
```
$context = Get-AzContext -Name 'mycontext' # Get an Azure context object
$creds = Get-Credential
$job = Start-Job { param($context, $vmadmin) New-AzVM -Name MyVm -AzContext $context -Credential $vmadmin} -ArgumentList $context,$creds }
```
The last curly bracket must be deleted after -ArgumentList

On the last example of that page too, after -ArgumentList:

```
$creds = Get-Credential
$context = Get-AzContext -Name 'mycontext'
$vmName = "MyVm"

$job = Start-Job { param($context, $vmName, $vmadmin) New-AzVM -Name $vmName -AzContext $context -Credential $vmadmin} -ArgumentList $context,$vmName,$creds }

Get-Job $job
Get-AzVM -Name $vmName
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba707551-20a2-322c-0c8f-9dfe772238bf
* Version Independent ID: 66ef4cc6-052f-5fa6-b5a2-ffececc5b6a6
* Content: [Run Azure PowerShell cmdlets in PowerShell Jobs](https://docs.microsoft.com/en-us/powershell/azure/using-psjobs?view=azps-7.2.0)
* Content Source: [docs-conceptual/azps-7.2.0/using-psjobs.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.2.0/using-psjobs.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for bringing this to our attention. We will investigate it further and update you shortly.
