### ISSUE TITLE
tokencache.dat should be replaced by msal.cache for newer PS version in doc

### ISSUE THREAD

**Issue by Riiiiika** [MicrosoftDocs/azure-docs-powershell#2053]
In below introduction, it's said user needs to mount TokenCache.dat file to azure-powershell container to use host authentication:
![image](https://user-images.githubusercontent.com/73595930/155671395-88a1486c-ffc5-4293-9d48-c768c727b27b.png)

However there's no such file under /root/Azure, but only one empty directory called "tokencache.dat" exists (the bak files are backups during test):
![image](https://user-images.githubusercontent.com/73595930/155673102-f5924b86-71d4-41d7-bc89-fc7c36e77f20.png)

So when we run powershell docker with the command listed in the doc, we couldn't get token in container actually. AzConext could be passed into Container successfully if you run Get-AzContext, however when running other basic commands like Get-AzSubscription or Get-AzResource, it will throw an error saying _"SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache"_:
![image](https://user-images.githubusercontent.com/73595930/155672282-8b17c9a7-15de-4f45-9197-f2240192a3de.png)

I took some research and found the token cache file has been changed after Az.Account 2.x, so the actual token cache file should be  **~/.local/share/.IdentityService/msal.cache** in CentOS (not tested in other Linux distros), and **~/.IdentityService/msal.cache** in Windows.

Based on this, if I ran the command like below, I could get Azure resources successfully with host authentication in azure-powershell container(tested with Azure China Cloud in screenshot):
_docker run -it -v ~/.Azure/AzureRmContext.json:/root/.Azure/AzureRmContext.json -v ~/.local/share/.IdentityService/msal.cache:/root/.local/share/.IdentityService/msal.cache mcr.microsoft.com/azure-powershell pwsh_

![image](https://user-images.githubusercontent.com/73595930/155673713-ef6f02f4-f8ef-47d6-9e6e-fdfc418213aa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74fcf9fd-8033-a3a8-51ca-309e1c74e615
* Version Independent ID: bc8743ed-c035-2211-e3c1-a35ffbf7277e
* Content: [Using Azure PowerShell in Docker](https://docs.microsoft.com/en-us/powershell/azure/azureps-in-docker?view=azps-7.2.0#feedback)
* Content Source: [docs-conceptual/azps-7.2.0/azureps-in-docker.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.2.0/azureps-in-docker.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by SaurabhSharma-MSFT** [comment]
@Riiiiika Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mikefrobbins** [comment]
@Riiiiika The host authentication section has been removed from the documentation. This is no longer an option because the cache is now encrypted.
