### ISSUE TITLE
[Microsoft Documents Feedback]

### ISSUE THREAD

**Issue by bakandah** [MicrosoftDocs/azure-docs-powershell#2070]
Hello,
While I was doing troubleshooting for VM Backup Extension, I noticed that there was no example provided in the following document:

* [Set-AzVMBackupExtension](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbackupextension?view=azps-7.3.0)

![image](https://user-images.githubusercontent.com/67425540/157755493-e06156a0-a351-46fb-a8d8-090b3fefd6b5.png)

Can you please update this document by adding an example?

[Basil Kandah feedback]
Thank you very much!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea9c977-831e-6c11-8a36-993c97ac198d
* Version Independent ID: a1a4e76d-f614-b29b-8b74-283aa1315a9e
* Content: [Introducing the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-7.3.0)
* Content Source: [docs-conceptual/azps-7.3.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.3.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MarileeTurscak-MSFT** [comment]
@bakandah 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by bakandah** [comment]
Thank you @MarileeTurscak-MSFT

**Comment by mikefrobbins** [comment]
@bakandah The cmdet reference for Azure PowerShell is autogenerated. I've logged an issue in the source code repo for Azure PowerShell to have the appropriate examples added.

See azure/azure-powershell#17504 for more details.
