### ISSUE TITLE
Power state is missing

### ISSUE THREAD

**Issue by placidseven** [MicrosoftDocs/azure-docs-powershell#2087]
I'm not getting the powerstate for vms i.e. "Deallocated", "Running"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b408d60-f96c-a7ea-3fc5-638fcaf322c0
* Version Independent ID: c186d2b8-ecb0-9d47-bb2a-3a3ede3f0c70
* Content: [Query output of Azure PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/azure/queries-azureps?view=azps-7.3.2)
* Content Source: [docs-conceptual/azps-7.3.2/queries-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.3.2/queries-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@placidseven - It doesn't appear that the cmdlets used in the article return any type of Power state property.
Can you elaborate on what you are trying to accomplish?

**Comment by MonikaReddy-MSFT** [comment]
@placidseven - Can you elaborate on what you are trying to accomplish here in this issue?

**Comment by MonikaReddy-MSFT** [comment]
@placidseven - Since we have not heard back from you we will now proceed to close this thread. 
However if you can share additional information requested and circle back on this thread , we will gladly reopen the issue and continue the discussion. Thank you.
