### ISSUE TITLE
Guide incorrect

### ISSUE THREAD

**Issue by kelvinhandley** [MicrosoftDocs/azure-docs-powershell#2128]
The guide has an example for version 6.13.2 but the command doesn't support beyond 6.13.1. See below:

New-AzUpgradeModulePlan -FromAzureRmVersion 6.13.2 -ToAzVersion 5.7.0 -DirectoryPath "deploy.json" -OutVariable Plan

New-AzUpgradeModulePlan: Cannot validate argument on parameter 'FromAzureRmVersion'. The argument "6.13.2" does not belong to the set "6.13.1" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80877a58-27ed-65c9-f6b8-5eef64b46502
* Version Independent ID: 7699fdfd-ca63-8b88-8ebb-5ded07270e13
* Content: [Automatically migrate PowerShell scripts from AzureRM to the Az PowerShell module](https://docs.microsoft.com/en-gb/powershell/azure/quickstart-migrate-azurerm-to-az-automatically?view=azps-7.5.0)
* Content Source: [docs-conceptual/azps-7.5.0/quickstart-migrate-azurerm-to-az-automatically.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-7.5.0/quickstart-migrate-azurerm-to-az-automatically.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for bringing this to our attention. We will investigate it further and update you shortly.
