### ISSUE TITLE
Upgrading PowerShell causes error / message

### ISSUE THREAD

**Issue by w-azure** [MicrosoftDocs/azure-docs-powershell#2265]
When using this command:

`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`

I get this error / message:

`Install-Package: The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'Az.Accounts' may override the
existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.`

You might want to change that command to:

`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber`

...unless there is a reason people might not want to upgrade. Otherwise make a note alert that mentions this error / message, otherwise people might wonder if they should use `-AllowClobber` or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c2dba0-9ae3-73cb-a719-6778988b7c9b
* Version Independent ID: c6b88fad-dfa9-e0b4-b3ed-7b889c32d813
* Content: [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-8.2.0)
* Content Source: [docs-conceptual/azps-8.2.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-8.2.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
@w-azure It appears that you have the AzureRM PowerShell module installed. The AzureRM PowerShell module will need to be removed prior to installing the Az PowerShell module.

If you need both installed on the same system, install AzureRM in the current user scope of Windows PowerShell and the Az in the current user scope of PowerShell 7.

For more information, see [Az and AzureRM coexistence](https://docs.microsoft.com/powershell/azure/troubleshooting?view=azps-8.2.0#az-and-azurerm-coexistence).

**Comment by mikefrobbins** [comment]
@w-azure Following up to confirm if the AzureRM module was installed and if removing it resolved the issue?

**Comment by stivoberlin** [comment]
> @w-azure Following up to confirm if the AzureRM module was installed and if removing it resolved the issue?

this does not resolve the issue.
