### ISSUE TITLE
PowerShell commands gives error / message

### ISSUE THREAD

**Issue by w-azure** [MicrosoftDocs/azure-docs-powershell#2266]
When using this command:

`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`

I get this error / message:

`Install-Package: The following commands are already available on this
system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This module 'Az.Accounts' may override the
existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.`

You might want to change that command to:

`Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber`

...unless there is a reason people might not want to upgrade. Otherwise make a note alert that mentions this error / message, otherwise people might wonder if they should use `-AllowClobber` or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c2dba0-9ae3-73cb-a719-6778988b7c9b
* Version Independent ID: c6b88fad-dfa9-e0b4-b3ed-7b889c32d813
* Content: [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-8.2.0)
* Content Source: [docs-conceptual/azps-8.2.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-8.2.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
Closing due to duplicate issue. See #2265.
