### ISSUE TITLE
No prerequisites section?

### ISSUE THREAD

**Issue by PatrickFarley** [MicrosoftDocs/azure-docs-powershell#2276]
All I know is, none of the commands in this doc work out of the box. What do I need to install to be able to follow the steps here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6218e372-7c8c-b41d-34b1-4a418896a715
* Version Independent ID: 411fe566-abd8-a884-1cc8-574d192bff37
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-8.2.0)
* Content Source: [docs-conceptual/azps-8.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-8.2.0/create-azure-service-principal-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
@PatrickFarley You'll need to install the [Az PowerShell module](https://docs.microsoft.com/powershell/azure/install-az-ps) or use [Azure Cloud Shell](http://shell.azure.com/).

I'll add a prerequisites section to the referenced article.

Thanks for the feedback!
