### ISSUE TITLE
Permission issues with AzAD cmdlets points to API reference

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-docs-powershell#2301]
Section "Permission issues with AzAD cmdlets" points to [Microsoft Graph permissions reference](https://learn.microsoft.com/en-us/graph/permissions-reference) which is a general reference, not a troubleshooting guide or anything like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e939cb30-b3d1-9549-a856-a46380b9db43
* Version Independent ID: 40fa62a2-2955-ed9d-1624-be797dadc063
* Content: [Troubleshooting the Azure Az PowerShell module](https://learn.microsoft.com/en-us/powershell/azure/troubleshooting?view=azps-8.3.0)
* Content Source: [docs-conceptual/azps-8.3.0/troubleshooting.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-8.3.0/troubleshooting.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by RamanathanChinnappan-MSFT** [comment]
@abatishchev 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@abatishchev

Thanks for your feedback! We have assigned the issue to author and will provide further updates.
