### ISSUE TITLE
WARNING service principal secret is stored in plain text

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/azure-docs-powershell#2308]
Hello,

Please share this warning in the article. I am currently reconsidering this approach after realizing the secret in stored in clear text on the machine. 

```
[PS] C:\> Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user
profile ( C:\Users\ptazadmin\.Azure ). Please ensure that this directory has appropriate protections.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 125441de-3f79-414d-0fc3-37f7c1b71d32
* Version Independent ID: b0214cf8-b8c7-23dc-f3bf-f9bfc39ba98e
* Content: [Sign in with Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-8.3.0)
* Content Source: [docs-conceptual/azps-8.3.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-8.3.0/authenticate-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by SaibabaBalapur-MSFT** [comment]
@jonwbstr 
Thanks for your feedback! We will investigate and update as appropriate.
