### ISSUE TITLE
the second "patch" code sample is invalid

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/azure-docs-powershell#2387]
the hyphen before the `method` parameter needs to be removed when splatting, as is the case with the earlier examples on this page.

```
...
  } }'
  -Method = 'PATCH'
}
...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdb22d96-0efb-7248-c462-97cca48b45a2
* Version Independent ID: e5c2c3f5-e378-24a8-584a-09c147db9819
* Content: [Manage Azure resources with Invoke-AzRestMethod](https://learn.microsoft.com/en-us/powershell/azure/manage-azure-resources-invoke-azrestmethod?view=azps-9.1.0)
* Content Source: [docs-conceptual/azps-9.1.0/manage-azure-resources-invoke-azrestmethod.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.1.0/manage-azure-resources-invoke-azrestmethod.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by YashikaTyagi-MSFT** [comment]
@Mike-Crowley 
Thanks for your feedback! We have assigned the issue to author who will provide further updates.

**Comment by mikefrobbins** [comment]
@Mike-Crowley Thanks for reporting this issue. Update forthcoming.
