### ISSUE TITLE
New Az Design Does not use Subscription in Context

### ISSUE THREAD

**Issue by jreinmilleratmosera** [MicrosoftDocs/azure-docs-powershell#2397]
Was asked to submit a request to have this page updated to reflect the new Az Design paradigm of not taking the Subscription information from the Context and instead specifying it via a separate parameter.

Here's the GitHub issue on this design change and the request to update this page:

https://github.com/Azure/azure-powershell/issues/20109#issuecomment-1336659256

Thanks.

Jeremiah Reinmiller

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b068ba5-8c0b-27af-34f0-f20d5cea00da
* Version Independent ID: 9dd87152-8c95-b9dd-251f-70d1c2c2c718
* Content: [Azure contexts and sign-in credentials](https://learn.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-9.1.0)
* Content Source: [docs-conceptual/azps-9.1.0/context-persistence.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.1.0/context-persistence.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by AjayBathini-MSFT** [comment]
@jreinmilleratmosera 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
