### ISSUE TITLE
Release Notes Versioning

### ISSUE THREAD

**Issue by Mattheww65** [MicrosoftDocs/azure-docs-powershell#2406]
The release notes page is great, but a couple of suggestions:

- We do not install the full az. module, just the component parts we need ie. az.accounts . It would be really useful to list the version of those parts in the release notes, rather than just the version number of the overarching az. module. 
For example, currently we are updating az.Accounts from 2.7.4 to 2.10.4. I'm having to use dates to work out the changes that have been made and tally that up with the az. module version numbers

- Breaking changes are great to list, but some kind of filter that would highlight those would be really useful

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdde8a1b-913d-6123-7cb6-4a7cbac558ad
* Version Independent ID: 13ab3c45-9746-6b1c-66af-bbb1f8f5de60
* Content: [Azure PowerShell release notes](https://learn.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-9.2.0)
* Content Source: [docs-conceptual/azps-9.2.0/release-notes-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.2.0/release-notes-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for bringing this to our attention. We will investigate it further and update you shortly.

**Comment by mikefrobbins** [comment]
@Mattheww65 I've reached out to the team who generates the release notes. I'll follow-up once I hear back from them.

**Comment by vandre** [comment]
On the topic of breaking changes please include a note with the planned date for when a breaking change is scheduled to happen.

**Comment by dcaro** [comment]
@vandre it is difficult for us to announce a release date for breaking changes much ahead of time. For example, major releases usually align with events like Microsoft //Build and we are not allowed to communicate about those dates before it is publicly announced.
However, we will take your suggestion in consideration and will announce the version of Az the breaking change aligns with.

**Comment by wyunchi-ms** [comment]
Hi @Mattheww65 , we have updated our ChangeLog generation tool. It will carry the module version in the next release.
