### ISSUE TITLE
Neither of these options work on SAW

### ISSUE THREAD

**Issue by ejsealms** [MicrosoftDocs/azure-docs-powershell#2419]
Please provide a method that works on SAWs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d943b468-dc3d-9789-9992-45092c51de61
* Version Independent ID: 2615ebe7-955c-bfc5-55ba-7914f6410168
* Content: [Uninstall Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-9.2.0&viewFallbackFrom=azps-2.8.0#uninstall-from-powershell)
* Content Source: [docs-conceptual/azps-9.2.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.2.0/uninstall-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by SaibabaBalapur-MSFT** [comment]
@ejsealms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mikefrobbins** [comment]
@ejsealms How was the Az module installed? Is an error message generated when attempting to perform the uninstallation?

The process to perform the uninstall differs depending on if the installation was performed via `Install-Module` from the PowerShell Gallery or with the MSI. I didn't experience any issues performing the uninstall in PowerShell's constrained language mode.

**Comment by mikefrobbins** [comment]
@ejsealms, we will now proceed with closing this issue. If you are still experiencing problems, let us know.
