### ISSUE TITLE
[Question] how Az Powershell module works behind a proxy for Powershell 5

### ISSUE THREAD

**Issue by yinghsugn** [MicrosoftDocs/azure-docs-powershell#2461]
Is that a solution for Az Powershell module to work with Powershell 5?

What the environment variable should be for Powershell 5?

In the document only saying “Do not suggest setting HTTP_PROXY/HTTPS_PROXY environment variables” for powershell 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c68af2af-f27e-85c3-6ff5-2e24b5f63601
* Version Independent ID: de76ff48-e46c-adb3-b73f-9734438c6348
* Content: [Use the Az PowerShell module behind a proxy](https://learn.microsoft.com/en-us/powershell/azure/az-powershell-proxy?view=azps-9.4.0)
* Content Source: [docs-conceptual/azps-9.4.0/az-powershell-proxy.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.4.0/az-powershell-proxy.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by ManoharLakkoju-MSFT** [comment]
@yinghsugn 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by isra-fel** [comment]
Hi @yinghsugn the recommended way is to use the system proxy settings (internet options).

@mikefrobbins how about we remove the confusing note? "Do not suggest setting HTTP_PROXY/HTTPS_PROXY environment variables."
