### ISSUE TITLE
`Get-AzSubscriptionDiagnosticSettingCategory` is not recognized as a name of a cmdlet in Azure Cloud Shell

### ISSUE THREAD

**Issue by vegazbabz** [MicrosoftDocs/azure-docs-powershell#2537]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://github.com/MicrosoftDocs/azure-docs-powershell/blob/42fa0f29c91be9c3f2150772ce07d01150d6e85a/azps-8.3.0/Az.Monitor/Get-AzSubscriptionDiagnosticSettingCategory.md
- https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azsubscriptiondiagnosticsettingcategory?view=azps-8.3.0

### Summary

`Get-AzSubscriptionDiagnosticSettingCategory` is not recognized as a name of a cmdlet in Azure Cloud Shell.

### Suggested Fix

Add it to Cloud Shell PowerShell.

**Comment by Naveenommi-MSFT** [comment]
@dingmeng-xue 
Could you please review add comments on this, update as appropriate.

**Comment by dingmeng-xue** [comment]
@isra-fel , please look into it and assign team member.

**Comment by Naveenommi-MSFT** [comment]
@vegazbabz 
I have recreated the same issue in one of our github link as per our content author request.
You can follow the update as below thread. Now we are going close this thread in this repo. Thanks!!!

https://github.com/Azure/azure-powershell/issues/21660

**Comment by isra-fel** [comment]
@vegazbabz we are tracking the issue here: https://github.com/Azure/azure-powershell/issues/21660
Please let us know if the issue has been fixed for you 😀 
BTW may I ask where did you find this deprecated cmdlet? If there are outdated documents/examples we may need to update them as well.
