### ISSUE TITLE
Introducing the Azure Az PowerShell module 404s

### ISSUE THREAD

**Issue by aditijms** [MicrosoftDocs/azure-docs-powershell#2538]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-9.7.0

### Summary

404s:

- https://learn.microsoft.com/en-us/powershell/azure/install-az-ps.md?view=azps-9.7.0
- https://learn.microsoft.com/en-us/powershell/azure/install-az-ps-msi.md?view=azps-9.7.0

It should be https://learn.microsoft.com/en-us/powershell/azure/install-azure-powershell?view=azps-9.6.0 instead?

### Suggested Fix

Update URLs.

**Comment by Naveenommi-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55ebfa9b-fbf9-abfe-4337-975765b52504
* Version Independent ID: a1a4e76d-f614-b29b-8b74-283aa1315a9e
* Content: [Introducing the Azure Az PowerShell module](https://learn.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-9.7.0)
* Content Source: [docs-conceptual/azps-9.7.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-9.7.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by Naveenommi-MSFT** [comment]
@aditijms 
Thank you for bringing this to our attention.
I've delegated this to content author @mikefrobbins, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@mikefrobbins
Could you please review add comments on this, update as appropriate.

**Comment by mikefrobbins** [comment]
Added redirects for the install docs.
