### ISSUE TITLE
Instructions on how to install Azure PowerShell module (ASM) are outdated and misleading

### ISSUE THREAD

**Issue by omunoz666** [MicrosoftDocs/azure-docs-powershell#2593]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6c7f7-a61f-5a06-b964-888ee03eb86b
* Version Independent ID: a166875b-49f9-ea6d-d7ad-123189ef7b5c
* Content: [Install and configure the Azure PowerShell Service Management module](https://learn.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0)
* Content Source: [docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md)
* Service: **azure-asm**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by RamanathanChinnappan-MSFT** [comment]
@omunoz666 

I've delegated this to @mikefrobbins, a content author, to review and share their valuable insights.

**Comment by mikefrobbins** [comment]
Switching to tracking this issue via #2594 at @omunoz666's request.
