### ISSUE TITLE
The documentation regarding Azure PowerShell installation is outdated 

### ISSUE THREAD

**Issue by OrlandoAMunoz** [MicrosoftDocs/azure-docs-powershell#2594]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0

### Summary

The steps required to install and login to Azure using the Azure Powershell module are outdated, and do not take into account dependencies and the current need to enable TLS 1.2.

### Details

TLS 1.2 must be enabled for the commands to interact correcty with the repositories and with the Azure infrastructure.

Repository NuGet must be installed on PowerShell 5.1 for the Azure module to be found and installed.

### Suggested Fix

Correct steps, as validated during a case resolution:

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-PackageProvider -Name NuGet
Install-Module -Name Azure -AllowClobber
Add-AzureAccount

**Comment by RamanathanChinnappan-MSFT** [comment]
@OrlandoAMunoz 

Thanks for your feedback! We will investigate and update as appropriate.

I've delegated this to @mikefrobbins, a content author, to review and share their valuable insights.

**Comment by mikefrobbins** [comment]
@OrlandoAMunoz Closing due to this being a duplicate issue. See #2593 for tracking of this problem.

**Comment by OrlandoAMunoz** [comment]
Hi Mike,

The #2593 was posted by mistake with my personal account.
Please consider this one #2593 posted with my work ***@***.***) account.

Otherwise it will not count for my performance review.

Kind regards,

Orlando Alvarez Muñoz
Support Engineer
Microsoft Azure Technical Support
Customer Service and Support
Office: +351 (21) 0491844
***@***.******@***.***>
Working hours: 8:30-17:30 UTC+1
If you need to work with another Support Engineer outside of my working hours, please send email to ***@***.******@***.***> with your case number, and availability.
We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at ***@***.******@***.***> .
[Microsoft Azure logo horizontal]

**Comment by mikefrobbins** [comment]
@OrlandoAMunoz, The issue with enabling TLS 1.2 and installing NuGet on Windows PowerShell 5.1 is due to the PowerShellGet module requiring an update. I've added a link to [Update PowerShellGet for Windows PowerShell 5.1](https://learn.microsoft.com/powershell/gallery/powershellget/update-powershell-51) in the prerequisites section to resolve this issue (see PR #2593).

> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser <<- Already part of the prerequisites section
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12  <<- Covered by updating PowerShellGet
> Install-PackageProvider -Name NuGet <<- Covered by updating PowerShellGet
> Install-Module -Name Azure -AllowClobber <<- Already part of the installation section
> Add-AzureAccount <<- Already part of the sign in section

**Comment by OrlandoAMunoz** [comment]
Hi Mike,

Thank you for the feedback 😊

Kind regards,

Orlando Alvarez Muñoz
Support Engineer
Microsoft Azure Technical Support
Customer Service and Support
Office: +351 (21) 0491844
***@***.******@***.***>
Working hours: 8:30-17:30 UTC+1
If you need to work with another Support Engineer outside of my working hours, please send email to ***@***.******@***.***> with your case number, and availability.
We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at ***@***.******@***.***> .
[Microsoft Azure logo horizontal]
