### ISSUE TITLE
I still can't execute command AZ

### ISSUE THREAD

**Issue by TimoRiikonenIF** [MicrosoftDocs/azure-docs-powershell#2613]
I executed these commands successfully, but next I should make commands "Az ..." and Powershell doesn't find Az.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0b6a3c-3318-f13c-476f-f539e56c918e
* Version Independent ID: bbeb082e-d78d-a78b-00f6-5069cc0a5ce3
* Content: [Install Azure PowerShell on Windows](https://learn.microsoft.com/en-us/powershell/azure/install-azps-windows?view=azps-10.0.0&tabs=powershell&pivots=windows-psgallery)
* Content Source: [docs-conceptual/azps-10.0.0/install-azps-windows.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.0.0/install-azps-windows.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by mikefrobbins** [comment]
@TimoRiikonenIF The installation document you referenced installs the Az PowerShell module for using Azure PowerShell to manage your Azure resources. To install the Azure CLI, see [How to install the Azure CLI](https://learn.microsoft.com/cli/azure/install-azure-cli).

To learn the differences in Azure PowerShell and the Azure CLI, see [Choose the best Azure command line tools for managing and provisioning your cloud infrastructure](https://learn.microsoft.com/en-us/training/modules/azure-command-line-tools-intro/).
