### ISSUE TITLE
Can't select Migrate Azure PowerShell script on VS Code

### ISSUE THREAD

**Issue by bonartg** [MicrosoftDocs/azure-docs-powershell#2693]
Hi,

In section Convert your scripts manually, step number 2, I can't find Migrate Azure PowerShell script on command palette Ctrl+Shift+P. What could I missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: edfe2e86-b94c-0c88-a59c-b0fd30ff5ce1
* Version Independent ID: 7b9796d9-dc5d-0df2-be08-52f843578018
* Content: [Migrate Azure PowerShell scripts from AzureRM to Az](https://learn.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-10.2.0&viewFallbackFrom=azps-9.4.0&preserve-view=true)
* Content Source: [docs-conceptual/azps-10.2.0/migrate-from-azurerm-to-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.2.0/migrate-from-azurerm-to-az.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by Naveenommi-MSFT** [comment]
@bonartg 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mikefrobbins** [comment]
@bonartg I'm able to replicate the issue. I've reached out to the engineering team as this seems to be a bug with the VS Code extension.

**Comment by isra-fel** [comment]
We are tracking the issue here in the azure-powershell-migration repo https://github.com/Azure/azure-powershell-migration/issues/116
