### ISSUE TITLE
Offline installation steps of Azure PowerShell for Linux

### ISSUE THREAD

**Issue by thiruma0203** [MicrosoftDocs/azure-docs-powershell#2752]
Currently this documentation only has online install steps for Linux with Install-Module cmdlet.
As GitHub releases have .tar.gz package with Installmodule.PS1 in it, it seems to better to have offline installation steps as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a17d7e-7bb3-bc99-d53e-279ed00ce825
* Version Independent ID: 201a4e7b-e592-dc29-aec5-9e39c4809e87
* Content: [Install Azure PowerShell on Linux](https://learn.microsoft.com/en-us/powershell/azure/install-azps-linux?view=azps-10.3.0)
* Content Source: [docs-conceptual/azps-10.3.0/install-azps-linux.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.3.0/install-azps-linux.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by RamanathanChinnappan-MSFT** [comment]
@thiruma0203 
I've delegated this to @mikefrobbins, a content author, to review and share their valuable insights.

**Comment by mikefrobbins** [comment]
@thiruma0203 I've added this suggestion as an idea for a future enhancement to our documentation.

**Comment by vivuu1989** [comment]
Any solution on this? loking for a way to install azurepowerhell in Redhat 7.9 version offline where internet is not enabled.

**Comment by mikefrobbins** [comment]
@thiruma0203 and @vivuu1989, the steps to install the Az PowerShell module offline via the tar archive are:

These instructions work cross-platform on Windows, Linux, and macOS:
1. [Install PowerShell version 7.2 or higher](https://learn.microsoft.com/powershell/scripting/install/installing-powershell)
1. Download the tar archive of the Az module from [the Azure PowerShell source repo releases page](https://github.com/Azure/azure-powershell/releases/).
1. Copy the file to the offline system.
1. Unblock the file if on Windows: `Unblock-File -Path <file-path>`
1. Unarchive the tar file: `tar zxf <tar-file-location> -C <destination-path>`
1. Run `.<destination-path>/InstallModule.ps1` to install the Az module from the extracted files.

**Comment by vivuu1989** [comment]
> 6\. InstallModule.ps1

Didnt Work. (Redhat version 7.9, pwsh installed version 7.2.18)

getting the below error 

./InstallModule.ps1: line 1: syntax error near unexpected token `newline'
'/InstallModule.ps1: line 1: `<#


removed the comment session as well, but again throwing the error 

./InstallModule.ps1: line 3: $'.\r': command not found
./InstallModule.ps1: line 17: $'\r': command not found
./InstallModule.ps1: line 18: syntax error near unexpected token `$']\r''
'/InstallModule.ps1: line 18: `[cmdletbinding()]

**Comment by mikefrobbins** [comment]
> > 6. InstallModule.ps1
> 
> Didnt Work. (Redhat version 7.9, pwsh installed version 7.2.18)
> 
> getting the below error
> 
> ./InstallModule.ps1: line 1: syntax error near unexpected token `newline' '/InstallModule.ps1: line 1: `<#
> 
> removed the comment session as well, but again throwing the error
> 
> ./InstallModule.ps1: line 3: $'.\r': command not found ./InstallModule.ps1: line 17: $'\r': command not found ./InstallModule.ps1: line 18: syntax error near unexpected token `$']\r'' '/InstallModule.ps1: line 18: `[cmdletbinding()]

You've launched PowerShell via `pwsh`, correct? I receive the same error when running `./InstallModule.ps1` from Bash.

**Comment by vivuu1989** [comment]
> > > 6. InstallModule.ps1
> > 
> > 
> > Didnt Work. (Redhat version 7.9, pwsh installed version 7.2.18)
> > getting the below error
> > ./InstallModule.ps1: line 1: syntax error near unexpected token `newline' '/InstallModule.ps1: line 1: `<#
> > removed the comment session as well, but again throwing the error
> > ./InstallModule.ps1: line 3: ′.\r′:commandnotfound./InstallModule.ps1:line17:'\r': command not found ./InstallModule.ps1: line 18: syntax error near unexpected token `$']\r'' '/InstallModule.ps1: line 18: `[cmdletbinding()]
> 
> You've launched PowerShell via `pwsh`, correct? I receive the same error when running `./InstallModule.ps1` from Bash.

So the offline installation is not possible in Linux ?

**Comment by mikefrobbins** [comment]
Offline installation is definitely available on Linux. Example of offline installation on RHEL 8.9 using the previously provided instructions:

![image](https://github.com/MicrosoftDocs/azure-docs-powershell/assets/6719572/ab50aaae-7c17-40e9-8322-4a38d9a086b1)
