### ISSUE TITLE
Add information on how to authenticate using DefaultAzureCredential

### ISSUE THREAD

**Issue by danieltharris** [MicrosoftDocs/azure-docs-powershell#2756]
DefaultAzureCredential works both locally and in Azure and information on how to use DefaultAzureCredential should be included nearby to where Managed Identity is discussed.

If DefaultAzureCredential is not supported, then a note should be added to indicate this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc9cb57-ce0c-5399-91eb-3b9a9b902ff9
* Version Independent ID: b0214cf8-b8c7-23dc-f3bf-f9bfc39ba98e
* Content: [Sign in with Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-10.4.1)
* Content Source: [docs-conceptual/azps-10.4.1/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.4.1/authenticate-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by MonikaReddy-MSFT** [comment]
@danieltharris - Thanks for bringing this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@danieltharris - Thanks again for bringing this to our attention. We have updated the doc and it will be live once it's merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by mikefrobbins** [comment]
@danieltharris I'm revisiting this issue. Could you provide more context?

**Comment by MonikaReddy-MSFT** [comment]
@danieltharris - Since we have not heard back from you, we will now proceed to close this thread. 
However, if you can share additional information regarding the documentation you are referring to and the question asked by @mikefrobbins and circle back on this thread, we will gladly reopen the issue and continue the discussion. Thank you.
