### ISSUE TITLE
NO_PROXY environment variables for PowerShell 7 on Windows and PowerShell 7 on macOS.

### ISSUE THREAD

**Issue by thiruma0203** [MicrosoftDocs/azure-docs-powershell#2962]
### Type of issue

Missing information

### Feedback

Currently usage of NO_PROXY environment variables is mentioned only for PowerShell 7 on Linux in the table.

PowerShell 7 on Windows:  Proxy could be configured by setting both HTTP_PROXY and HTTPS_PROXY environment variables.
PowerShell 7 on macOS:  Proxy could be configured by setting both HTTP_PROXY and HTTPS_PROXY environment variables.
PowerShell 7 on Linux: Set both HTTP_PROXY and HTTPS_PROXY environment variables, plus optional NO_PROXY

However, if Az PowerShell relies on environment variables defined in HttpClient.DefaultProxy, NO_PROXY should work for PowerShell 7 on Windows and PowerShell 7 on macOS as well.

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1

If NO_PROXY works for Az PowerShell on Windows and macOS, it is better to have information in the article.

### Page URL

https://learn.microsoft.com/en-us/powershell/azure/az-powershell-proxy?view=azps-11.5.0

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-11.5.0/az-powershell-proxy.md

### Author

@mikefrobbins

### Document Id

de76ff48-e46c-adb3-b73f-9734438c6348

**Comment by PesalaPavan** [comment]
@thiruma0203 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by mikefrobbins** [comment]
@thiruma0203 Thank you for reporting this issue. The documentation update is forthcoming.
