### ISSUE TITLE
CAFÉ 

### ISSUE THREAD

**Issue by CasP0** [MicrosoftDocs/azure-docs-powershell#3030]
### Type of issue

Missing information

### Feedback

AT THE CAFÉ 

### Page URL

https://learn.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-12.0.0

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-12.0.0/authenticate-azureps.md

### Author

@mikefrobbins

### Document Id

b0214cf8-b8c7-23dc-f3bf-f9bfc39ba98e

**Comment by TPavanBalaji** [comment]
@CasP0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@CasP0 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by CasP0** [comment]
God LOVES America guys
