### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ThoThiDuong** [MicrosoftDocs/azure-docs-powershell#3096]
### Type of issue

Other (describe below)

### Feedback

502 bad gateway Microsoft Azure.  California Department Of Education 

### Page URL

https://learn.microsoft.com/en-us/powershell/azure/install-azure-powershell?view=azps-12.1.0

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-12.1.0/install-azure-powershell.md

### Author

@mikefrobbins

### Document Id

677f0521-b6fa-a07b-65f5-7e5c6cc74b84

**Comment by TPavanBalaji** [comment]
@ThoThiDuong 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ThoThiDuong** [comment]
Nevermind I'll fix it

**Comment by mikefrobbins** [comment]
@ThoThiDuong We're closing this issue based on your previous response. Please respond to this issue if you still require assistance, and we'll reopen it.
