### ISSUE TITLE
Azure powershell

### ISSUE THREAD

**Issue by Hc2Life** [MicrosoftDocs/azure-docs-powershell#3150]
プラウザでの作業にAzurepowershellをダウンロードしたい

**Comment by mikefrobbins** [comment]
@Hc2Life, visit [shell.azure.com](https://shell.azure.com/) to use Azure PowerShell in a web browser via [Azure Cloud Shell](https://learn.microsoft.com/azure/cloud-shell/overview).

**Comment by Hc2Life** [comment]
> @Hc2Life, visit [shell.azure.com](https://shell.azure.com/) to use Azure PowerShell in a web browser via [Azure Cloud Shell](https://learn.microsoft.com/azure/cloud-shell/overview).

Sorry for my ignorance. Thank you for your opinion. It scares me to think that young people will have to go through the same thing in the future.
