### ISSUE TITLE
Clearer documentation of Set-AzPolicy* to Update-AzPolicy* transition

### ISSUE THREAD

**Issue by marielleriveros** [MicrosoftDocs/azure-docs-powershell#3197]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

As a user of `Set-AzPolicy*` commands, I need clearer documentation of the transition to Update-AzPolicy* so that I can more efficiently maintain and update a code base.

### Details

In the `Set-AzPolicy*` sections of the Az 12.0.0 Migration Guide, it would be helpful to include a listing in the description of changes that specifies that the name of the command is being updated to `Update-AzPolicy*`. Currently that is shown in the examples, but it would be more clear if it were included in the description of changes. This would also allow for specification stating whether `Set-AzPolicy*` aliases will be deprecated in the future.
It would also be helpful to have the transition listed in the descriptions of the `Update-AzPolicy*` documentation. Currently it is only at the end (under "Notes: Aliases") and in the [Backcompat] example for each "update" command, making it easy to miss.

### Proposed Content Type

Other / Unknown

### Related Articles

- [Az 12.0.0 Migration Guide - Set-AzPolicyAssignment](https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.3.0#set-azpolicyassignment)
- [Az 12.0.0 Migration Guide - Set-AzPolicyDefinition](https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.3.0#set-azpolicydefinition)
- [Az 12.0.0 Migration Guide - Set-AzPolicyExemption](https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.3.0#set-azpolicyexemption)
- [Az 12.0.0 Migration Guide - Set-AzPolicySetDefinition](https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.3.0#set-azpolicysetdefinition)
- [Update-AzPolicyAssignment](https://learn.microsoft.com/en-us/powershell/module/az.resources/update-azpolicyassignment?view=azps-12.3.0#description)
- [Update-AzPolicyDefinition](https://learn.microsoft.com/en-us/powershell/module/az.resources/update-azpolicydefinition?view=azps-12.3.0#description)
- [Update-AzPolicyExemption](https://learn.microsoft.com/en-us/powershell/module/az.resources/update-azpolicyexemption?view=azps-12.3.0#description)
- [Update-AzPolicySetDefinition](https://learn.microsoft.com/en-us/powershell/module/az.resources/update-azpolicysetdefinition?view=azps-12.3.0#description)

**Comment by mikefrobbins** [comment]
@marielleriveros Thank you for bringing this to our attention. We appreciate your suggestions for improving the Migration Guide, and we'll review them closely.

Please note that the cmdlet documentation is autogenerated from reference content in the [Azure PowerShell source code repository](https://github.com/Azure/azure-powershell). Any changes made directly to this autogenerated content will not persist in future documentation updates. Use the link at the bottom of the cmdlet reference pages to address issues or suggest improvements. It will automatically populate the relevant information and log the issue in the correct repository, ensuring it gets triaged and directed to the appropriate team for review.

![image](https://github.com/user-attachments/assets/0715a24f-cb2a-492b-9397-ce0f79028b0c)

**Comment by mikefrobbins** [comment]
@marielleriveros, Clarification about the `Set-AzPolicy*` cmdlets being renamed to `Update-AzPolicy*` has been added to the migration guide. The changes should be live later today.

**Comment by marielleriveros** [comment]
@mikefrobbins thank you!
