### ISSUE TITLE
Found it Security Thread unless user know how to handle it.

### ISSUE THREAD

**Issue by Pulakesh25** [MicrosoftDocs/azure-docs-powershell#706]
I know auto saving AzureRM context help us to automate and run background job, but at the same I found this is a security thread unless we know how to handle it. In my experience I disable AzureRmContextAutosave, I tried Disconnect-AzureRmAccount, Logout-AzureRmAccount but none of this help me even after reboot; its allow me to sign in without giving password, it just ask for User Name. 

If you have a solution to this please share.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b42615-0064-d58f-0060-f432c9a15d78
* Version Independent ID: f641b6fa-c346-ad1d-65a6-793a4bedcbdf
* Content: [Persist user credentials across PowerShell sessions](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-6.7.0)
* Content Source: [docs-conceptual/azurermps-6.7.0/context-persistence.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.7.0/context-persistence.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@Pulakesh25 - Contexts are tied to user logins, however based on the fact that you are still seeing yourself logged in or able to connect after disconnecting or logging out makes me think that there may be an issue with contexts. Our documentation will be updated to make contexts clearer, but can you also please file a product bug? https://github.com/azure/azure-powershell

**Comment by sptramer** [comment]
@Pulakesh25 This issue has finally been resolved, long after you reported it - thank you for doing so. In the meantime I helped do some security review of basic information stored by the module, and updated the information on Azure Contexts to make it clear how to delete the stored data and what information is stored.

If you have security concerns, I strongly recommend disabling context autosave and regularly clearing the log data stored by Azure PowerShell. As always, if you find that there is information being leaked by the module, [report a bug to engineering](https://github.com/azure/azure-powershell/issues).
