### ISSUE TITLE
Current version Az Powershell RM

### ISSUE THREAD

**Issue by v-samiya** [MicrosoftDocs/azure-docs-powershell#858]
How much longer will the current Az Powershell RM be supported in production environment?   When will it be completely stopped the service?  Some of our customers are planning to keep using their current version and concerning if/when it is completely stopped using or any fee will be charged to switch to the NEW PowerShell Az module...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65abff75-73f1-3033-d816-e03e0d7fe4ff
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/new-azureps-module-az.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@markcowl Please respond with some detailed information about AzureRM lifecycle support.

**Comment by Yliche** [comment]
The biggest complaint I have is that the login method is the same as the CLI which is just horrendous having to copy a login URL and then an access code every time you want to start a session. PowerShell AzureRM had a much better login method because you can just easily type your credentials.

**Comment by artisticcheese** [comment]
Login shall be fixed on 1/15/2019 per article https://docs.microsoft.com/en-us/powershell/azure/migrate-az-1.0.0?view=azps-1.0.0#temporary-default-device-code-login-instead-of-web-browser-prompt

**Comment by sptramer** [comment]
The new module does not incur any additional fees. The new module was released only to offer better support, more consistent names, and work with PowerShell 6. AzureRM will continue to be supported with bug fixes, but receive no new features. @markcowl can provide information on the support window, and that information will be added to the migration docs.

**Comment by cpdohert** [comment]
Keeping the login UX the same as the AzureRm module should have been a required feature for a 1.0.0 release.
