### ISSUE TITLE
Unable to use the Azure PowerShell commands

### ISSUE THREAD

**Issue by ShashiKiranGowda** [MicrosoftDocs/azure-docs-powershell#860]
I'm trying to use the Get-AzureRmDataFactory and the similar commands but get the error "The term 'xyz' is not recognized as the name of a cmdlet, function, script file, or operable program."
I even tried Get-AzDataFactory as the AzureRM module is no more being used.
How do you log the Data factory Pipeline using PowerShell, is the cmdlet updated or is the work still in progress?? Could you please verify

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab81ac50-5213-1282-d66c-e0c70794d2eb
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/overview.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/overview.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@markcowl Can you please provide some information on the state of Az.DataFactory in the currently available release?

**Comment by markcowl** [comment]
@ShashiKiranGowda Have you installed the latest Az module?  Please run ```Get-Module -ListAvailable``` so we cna see the module layout on your machine.

**Comment by ShashiKiranGowda** [comment]
![azerror](https://user-images.githubusercontent.com/15978139/50266044-0c2ddf00-0448-11e9-930c-c9db65bed2d9.JPG)


Is 1.26 the latest version ??
I have attached the version of my PowerShell and AzModule. Kindly suggest on the error attached.

**Comment by sptramer** [comment]
@ShashiKiranGowda Please include the output of the following commands (as copy-paste, not a screenshot):

```
Get-InstalledModule -Name Az -AllVersions
Get-InstalledModule -Name AzureRM -AllVersions
```

**Comment by sptramer** [comment]
This issue has gone for 4 months without a response when requesting more info; closing.
