### ISSUE TITLE
Azure Portal still generates AzureRM cmdlets in the PowerShell tab

### ISSUE THREAD

**Issue by cmenzi** [MicrosoftDocs/azure-docs-powershell#914]
When generating an ARM template via the Portal, AzureRM is the presented way. So, Enable-AzureRmAlias -Scope CurrentUser is somehow a must.

When does this change to the new Az cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b348d594-8abc-99ae-d74d-bf372a52d7ad
* Version Independent ID: 3da6471e-bcaf-2b48-5a52-30ef3afebde3
* Content: [Migrate Azure PowerShell scripts from AzureRM to Az](https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/migrate-from-azurerm-to-az.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/migrate-from-azurerm-to-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by spaelling** [comment]
Would be a good way to push users to the _Az_ module

**Comment by PinakiIT** [comment]
I am having issues running any of the AZ module commands on the Azure DevOps pipeline. Either of the Azure PowerShell agent seems to load both the AzureRM and AZ modules. Any help here?

**Comment by sptramer** [comment]
@PinakiIT Sorry, this is not an appropriate location for asking for help with Azure DevOps. Please go to [Azure DevOps support](https://azure.microsoft.com/en-us/support/devops/).

**Comment by tfitzmac** [comment]
@PinakiIT - did you get your issue resolved related to using the Az module in a pipeline? We have a new article that shows how to do that - [Integrate Resource Manager templates with Azure Pipelines](https://docs.microsoft.com/en-us/azure/azure-resource-manager/vs-resource-groups-project-devops-pipelines). Specifically, you need to use version 4 of the Azure PowerShell task.

**Comment by mganeshphani** [comment]
Didn't expect Microsoft to not think about the underlying modules and create such stupid script

**Comment by cmenzi** [comment]
@sptramer What should I do? What do you expect? I cannot solve this.

**Comment by tfitzmac** [comment]
@cmenzi - does this script work for you?
[https://github.com/Azure/azure-quickstart-templates/blob/master/Deploy-AzTemplate.ps1](https://github.com/Azure/azure-quickstart-templates/blob/master/Deploy-AzTemplate.ps1)

**Comment by sptramer** [comment]
@cmenzi This is a request for Portal engineering. Unfortunately I do not have a contact for them or information on a timeline. I'll see what I can find.

**Comment by mgblythe** [comment]
#please-close
