### ISSUE TITLE
Whitelist requirements for PowerShell

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs-powershell#921]
Is it possible to make public the endpoints/URLs that would be needed to install and update PowerShell modules when operating behind a proxy/firewall?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f5724-189f-9900-4c54-5a8c5b34a449
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/install-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This is a more general question about an allow-list for installation of Powershell modules in general. The Az module is installed through PSGallery (https://www.powershellgallery.com/). You can get the API endpoint used by a PowerShell repository with the [Get-PSRepository](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-psrepository?view=powershell-6) command.

**Comment by dcbrown16** [comment]
Thanks Stephen
