### ISSUE TITLE
Az Module  and Azure Stack

### ISSUE THREAD

**Issue by ivanignatiev** [MicrosoftDocs/azure-docs-powershell#923]
Hello, 

Are we able to use Az module with Azure Stack ? If yes, if there any recommendations and instructions ? 

Thank you ! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8caeb4-6165-b2fe-a82d-b132d7cbe053
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/new-azureps-module-az.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@ivanignatiev Currently the Az module does not support Azure Stack. Users of Azure Stack should continue to use the AzureRM 2.x module series. Once the Az module has stack support, there should be a communication (as a blog post or email) from the Stack team letting users know.
