### ISSUE TITLE
The Recommendation is not accurate

### ISSUE THREAD

**Issue by DMoonesinghe** [MicrosoftDocs/azure-docs-powershell#925]
It's recommended that before installing the Az module, you uninstall AzureRM. 
I don't think it is any longer a recommendation but a must.  See below for the resason:
PS C:\WINDOWS\system32&gt; Connect-AzAccount
WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the
 same session or used in the same script or runbook. If you are running PowerShell in an environment you control you
 can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure
 Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found 
here: https://aka.ms/azps-migration-guide
Connect-AzAccount : Method 'get_SerializationSettings' in type 
'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 
'Microsoft.Azure.PowerShell.Clients.ResourceManager, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At line:1 char:1
+ Connect-AzAccount

Perhaps it would help readers if the warning is at the top of the page. To avoid erorr's like the above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f5724-189f-9900-4c54-5a8c5b34a449
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@DMoonesinghe There was some miscommunication from the engineering team about this; the documentation is now clear that AzureRM must be uninstalled before installing Az, and there is documentation for how to have both installed on a system at once.
