### ISSUE TITLE
List of subscription statuses?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/azure-docs-powershell#926]
Hi,
I would be very helpful with a list of subscription statuses and their meanings.
I have not been able to find the information elsewhere and this looks like an appropriate place.
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d8f5a0-6c13-0016-e3b5-415efcd8da3a
* Version Independent ID: 98b7ac0d-e288-bb26-57b8-c173c46821d5
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/manage-subscriptions-azureps?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/manage-subscriptions-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by theheatDK** [comment]
Any news? :-)

**Comment by sptramer** [comment]
Unfortunately I haven't been able to get an answer from the subscription team in this time, I will see if I can get that information.

**Comment by ToMakeSense** [comment]
@theheatDK @sptramer try the script below
> Get-AzSubscription | select Id, Name, State, TenantId | ft

**Comment by theheatDK** [comment]
Thanks @ToMakeSense,

But I am looking for a description of the values the State property can take.
Regards Peter

**Comment by ToMakeSense** [comment]
@theheatDK Through the powershell, I believe you can't make it, the state property's type is just string, see below:
1. [Subscription/Models/PSAzureSubscription.cs](https://github.com/Azure/azure-powershell/blob/master/src/Subscription/Subscription/Models/PSAzureSubscription.cs)
2. [Authentication.ResourceManager/Models/PSAzureSubscription.cs](https://github.com/Azure/azure-powershell/blob/master/src/Accounts/Authentication.ResourceManager/Models/PSAzureSubscription.cs) 

However, you can find it via Azure rest API [Subscriptions - Get](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/get#subscriptionstate)

**Comment by theheatDK** [comment]
Thanks @ToMakeSense,
I was actually looking for documentation of those states. I am a bit surprised that there is no page where you can get a explanation about what the mean and what the lifecycle etc. is.
Regards Peter

**Comment by ToMakeSense** [comment]
@theheatDK Not sure if these is what you want?
[Azure fundamental concepts](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/considerations/fundamental-concepts)
[Azure billing and cost management documentation](https://docs.microsoft.com/en-us/azure/billing/)

**Comment by theheatDK** [comment]
Not really. Nowhere is it mentioned that a subscription has a state and what the states mean. What can you do or not do with a subscription in the different states. Best practices etc. We for example have a lot of problems with custom roles where the assignable scope contains a subscription that has been canceled. We cannot change the scope ourselves and every time we have to create a service request to get it cleaned up.
A canceled subscription is first deleted after 90 days, which is documented, but what should you think about before canceling it? Remove the subscription from all custom roles,...?
I do not know what the PasteDue or Warned states means. What can you do or not do in these states?
When you have hundreds of subscriptions it would be nice with to have this documented.
Regards Peter

**Comment by ToMakeSense** [comment]
I believe it is in second link I give above, https://docs.microsoft.com/en-us/azure/billing under "manage subscription " yes, the states of the subcription are not listed clearly. but you can got it through the docs. maybe a specific article will be better.

**Comment by sptramer** [comment]
@ToMakeSense Thank you for digging up that information. I've taken a work item to run through it and get this information either on (or linked from) the subscription management page.

**Comment by theheatDK** [comment]
Hi @MarileeTurscak-MSFT,
Looks like @sptramer have moved one to other adventures.
I still think this would great with an article for this. What should I do? :-)
Regards Peter

**Comment by mikefrobbins** [comment]
The "[Azure subscription states](https://docs.microsoft.com/azure/cost-management-billing/manage/subscription-states)" doc contains a list of subscription statuses and their meanings.
