### ISSUE TITLE
Why are aliases provided only for some AzureRm commands?

### ISSUE THREAD

**Issue by Phydeauxman** [MicrosoftDocs/azure-docs-powershell#927]
Things like Get-AzureRmContext are not aliased with the new Az module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8caeb4-6165-b2fe-a82d-b132d7cbe053
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@Phydeauxman This seems like a bug with the Az module. Please file a request with engineering to fix the problem: https://github.com/azure/azure-powershell/issues
