### ISSUE TITLE
No explanation for ExpandResource parameter

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/azure-docs-powershell#931]
In some commands, for example [Get-AzVirtualNetwork](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azps-1.1.0/Az.Network/Get-AzVirtualNetwork.md#-expandresource) there is no explanation for parameter **-ExpandResource**. Neither there are examples what this parameter is doing. [Sometimes ](https://github.com/Azure/azure-powershell/issues/7196) this missing information it is causing problems on which it is hard to identify the real issue.

It would be helpful to explain also what not using this parameter is doing (i.e. it is returning only Id of referenced objects and **all** other properties are returned as null).

**Comment by sptramer** [comment]
Please file this request with the engineering team, who are in charge of cmdlet documentation: https://github.com/azure/azure-powershell/issues
