### ISSUE TITLE
It's not clear what tenantId is on this page

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/azure-docs-powershell#932]
It's not clear what tenantId is on this page or how to get the value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2594a15-a213-bdef-273e-57ff9de04588
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-1.1.0)
* Content Source: [docs-conceptual/azps-1.1.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.1.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by briantbriggs** [comment]
The following page explains in more detail with regards to TenantID:
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#get-values-for-signing-in

**Comment by sqlsolver** [comment]
It's listed along with the Object ID and Application ID in the overview section for the Service Principal in Azure AD.

**Comment by Daemach** [comment]
Still should be explained on this page!

**Comment by adamfowlerit** [comment]
Agree, you can't just have a PowerShell script line to run, when the variables aren't set as part of that script.

**Comment by AlexImray** [comment]
Furthermore, when using the newest Connect-AzAccount module, '-TenantId' isn't a parameter anymore. It's just '-Tenant' now.
https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-2.6.0

**Comment by aganotra** [comment]
tenants that are authorized for the current user. Once you are connected, you can get information about tenants. For more information
 https://docs.microsoft.com/en-us/powershell/module/az.accounts

**Comment by AlexImray** [comment]
> tenants that are authorized for the current user. Once you are connected, you can get information about tenants. For more information
> https://docs.microsoft.com/en-us/powershell/module/az.accounts

_We_ all know what TenantId is, but we're saying an anonymous user reading the page won't necessarily know and the page itself does absolutely nothing to tell the user what that variable is or how/where to retrieve it. We'd like the page to explain that or lead to that information somehow.

> It's listed along with the Object ID and Application ID in the overview section for the Service Principal in Azure AD.

If someone searches 'azure sign in with powershell' in a web browser, this is the first result, so they might not find the service principal page first. Additionally, following the Azure Powershell documentation, this page shows up well before Service Principal in Azure AD. So we can't assume they know what it is.

**Comment by Daemach** [comment]
What he said.
