### ISSUE TITLE
Mention the needed permissions

### ISSUE THREAD

**Issue by mosharafMS** [MicrosoftDocs/azure-docs-powershell#935]
The article doesn't mention the needed permissions, in my testing by using a service principal (service principal is creating an application) I found that it requires permissions for the API Application.ReadWrite.All . If it's a user that create the application, they should have Application administrator or Application Developer. Or allow all the users to register applications in the user settings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b877a4c-5a97-c923-424a-516b22f34684
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Create an Azure service principal with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.2.0)
* Content Source: [docs-conceptual/azps-1.2.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Required permissions depend on what the service principal will be used for, and change from user to user. Users who need to look up role information can do so by reading the linked RBAC documentation.

This section will be edited to remove guidance suggesting that `Reader` is the ideal default role to assign a service principal, and make it clearer that role guidance depends on what the service principal is intended to be used for.

**Comment by samsmithnz** [comment]
I agree with this original comment. I understand that some roles need certain applications, but what permissions are needed to call something generic like Get-AzADServicePrincipal?
