### ISSUE TITLE
Connect-AzAccount with Application Id

### ISSUE THREAD

**Issue by pemo11** [MicrosoftDocs/azure-docs-powershell#938]
The sample 

Connect-AzAccount -ServicePrincipal -ApplicationId  "http://my-app" -Credential $pscredential -TenantId $tenantid

doesn't work because of the ApplicationId parameter. I am using version 1.21 of Az.Accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9001c96-2efa-6196-7e52-1e7c61d880b3
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-1.2.0)
* Content Source: [docs-conceptual/azps-1.2.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by asubmani** [comment]
The sample command to use SPN is incorrect and doesn't work. The correct format is:
`Connect-AzAccount -ServicePrincipal -Credential $pscredential -TenantId  {tenantid/DirectoryId} -SubscriptionId {subscriptionId}`

**Comment by asubmani** [comment]
There is no need to specify `-Applicationid` as it is the username in `$pscreadential`.  The docs should make it clear as to what to enter when the `get-credential` command pops up a window. something like:
 
### SPN information: 

(Please use Application id as username and Password as password for `get-credential` prompt.
  - **Tenant Id** (Azure Active Directory -> Properties -> Directory ID)
    - **Subscription Id** (Subscriptions -> Choose subscription -> Overview -> Subscription ID)
    - **Application Id** (Azure Active Directory -> App Registrations -> Choose your app -> Application ID)
    - **Password** ( Azure Active Directory -> App Registrations -> Settings -> Choose your app -> Keys)
   `

**Comment by sptramer** [comment]
Fixed, docs should be clearer now.
