### ISSUE TITLE
Microsoft has made substantial improvements to removing knowledge barriers

### ISSUE THREAD

**Issue by MeanAverageJoe** [MicrosoftDocs/azure-docs-powershell#939]
The documentation and knowledge resources keep getting substantially better.  Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3426a777-4377-a1ec-73ea-31094e4713ee
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.2.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-1.2.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You're welcome!
