### ISSUE TITLE
Set-AzureRmSqlDatabaseGeoBackupPolicy returns an error

### ISSUE THREAD

**Issue by piroinno** [MicrosoftDocs/azure-docs-powershell#940]
Have not been able to use this function to configure geobackups for my Azure sql datawarehouse.
![image](https://user-images.githubusercontent.com/27731545/52204947-7cb08400-286d-11e9-8304-23bf188352b8.png)

Funny enough the Get function (Get-AzureRmSqlDatabaseGeoBackupPolicy) works.

**Comment by sptramer** [comment]
@piroinno - Please file this as an issue with the product team. https://github.com/Azure/azure-powershell/issues
