### ISSUE TITLE
Link to "Azure Information Protection" is broken.

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/azure-docs-powershell#947]
The following link towards the end of the article is broken: "Azure Information Protection"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3caaadd1-e77b-b4c8-4a32-aa3f051915bc
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-1.2.0)
* Content Source: [docs-conceptual/azps-1.2.0/overview.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/overview.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed.
