### ISSUE TITLE
What is MSI?

### ISSUE THREAD

**Issue by mumoryan** [MicrosoftDocs/azure-docs-powershell#949]
Nowhere in this document has mentioned the full name of MSI. During Uninstall MSI part, I couldn't find MSI in search. Should I search for a different term, or MSI is not installed at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3426a777-4377-a1ec-73ea-31094e4713ee
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.2.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-1.2.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ConcreteGannet** [comment]
MSI refers to a Windows Installer (https://docs.microsoft.com/en-us/windows/desktop/msi/windows-installer-portal) package. The description in Add/Remove Programs should be similar to "Azure Powershell". There are different MSI packages for different versions of Azure Powershell, for example this one: https://github.com/Azure/azure-powershell/releases/tag/v6.13.1-November2018

**Comment by ConcreteGannet** [comment]
The exact MSI package name should be "Microsoft Azure Powershell" followed by a date, for example "Microsoft Azure Powershell - November 2018"

**Comment by mumoryan** [comment]
Thanks ConcreteGannet for a clear explanation. Please go ahead and make a judgement call on whether a link that explains what MSI is should be added on this page. Other than that feel free to resolve and close this issue. 👍
