### ISSUE TITLE
Removing AzureRM is not easy to read

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/azure-docs-powershell#951]
I have now been trying to remove AzureRM for 30 minutes.
I couldn't find the MSI, so I tried to follow the guide. "use the Uninstall-AllModules script provided in this article instead".
So what do I do, I scroll up and see the "script":
"$versions = (Get-InstalledModule Az -AllVersions | Select-Object Version)
$versions[1..($versions.Length-1)]  | foreach { Uninstall-AllModules -TargetModule Az -Version ($_.Version) -Force }"

Okay, lets just change Az to AzureRM. 
Run it and it gives no error but it is still there. Since I only have one version in comparison to the example that has several I instead try. Uninstall-AllModules -TargetModule Az -Version $Versions.Version -Force

THEN i get that it can't find the command uninstall-allmodules. I took me 15 minutes to find out that this wasn't a cmdlet but a function specified higher up.

Please make this page more readable and make scripts so it works if you have both one previous version or multiple earlier versoins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3426a777-4377-a1ec-73ea-31094e4713ee
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.2.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-1.2.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by JameZJ** [comment]
NavFreak, This will remove AZ not AzureRM. You need to uninstall AzureRM using Uninstall-AzureRM if you had previously installed using AzureRM from PowerShellGet.

**Comment by JameZJ** [comment]
# TRY THIS

function Uninstall-AllModules {
  param(
    [Parameter(Mandatory=$true)]
    [string]$TargetModule,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [switch]$Force,

    [switch]$WhatIf
  )
  
  $AllModules = @()
  
  'Creating list of dependencies...'
  $target = Find-Module $TargetModule -RequiredVersion $version
  $target.Dependencies | ForEach-Object {
    if ($_.requiredVersion) {
      $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$_.requiredVersion}
    }
    else { # Assume minimum version
      # Minimum version actually reports the installed dependency
      # which is used, not the actual "minimum dependency." Check to
      # see if the requested version was installed as a dependency earlier.
      $candidate = Get-InstalledModule $_.name -RequiredVersion $version
      if ($candidate) {
        $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$version}
      }
      else {
        Write-Warning ("Could not find uninstall candidate for {0}:{1} - module may require manual uninstall" -f $_.name,$version)
      }
    }
  }
  $AllModules += New-Object -TypeName psobject -Property @{name=$TargetModule; version=$Version}

  foreach ($module in $AllModules) {
    Write-Host ('Uninstalling {0} version {1}...' -f $module.name,$module.version)
    try {
      Uninstall-Module -Name $module.name -RequiredVersion $module.version -Force:$Force -ErrorAction Stop -WhatIf:$WhatIf
    } catch {
      Write-Host ("`t" + $_.Exception.Message)
    }
  }
}

Write-Host " This will remove all Azure Modules, but AzureRM will need to be uninstalled from Programs."
Read-Host "Are you ready to uninstall all Azure Components?"
$versions = (Get-InstalledModule -name *azure*| Select-Object Name,Version)
$versions[1..($versions.Length-1)]  | foreach { Uninstall-AllModules -TargetModule ($_.Name) -Version ($_.Version) -Force }


$a = Get-InstalledModule -name *profile*
If ($a) { 
        Remove-AzureRmAccount
        Uninstall-Module -Name $a.name
        }

**Comment by JameZJ** [comment]
`function Uninstall-AllModules {
  param(
    [Parameter(Mandatory=$true)]
    [string]$TargetModule,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [switch]$Force,

    [switch]$WhatIf
  )
  
  $AllModules = @()
  
  'Creating list of dependencies...'
  $target = Find-Module $TargetModule -RequiredVersion $version
  $target.Dependencies | ForEach-Object {
    if ($_.requiredVersion) {
      $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$_.requiredVersion}
    }
    else { # Assume minimum version
      # Minimum version actually reports the installed dependency
      # which is used, not the actual "minimum dependency." Check to
      # see if the requested version was installed as a dependency earlier.
      $candidate = Get-InstalledModule $_.name -RequiredVersion $version
      if ($candidate) {
        $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$version}
      }
      else {
        Write-Warning ("Could not find uninstall candidate for {0}:{1} - module may require manual uninstall" -f $_.name,$version)
      }
    }
  }
  $AllModules += New-Object -TypeName psobject -Property @{name=$TargetModule; version=$Version}

  foreach ($module in $AllModules) {
    Write-Host ('Uninstalling {0} version {1}...' -f $module.name,$module.version)
    try {
      Uninstall-Module -Name $module.name -RequiredVersion $module.version -Force:$Force -ErrorAction Stop -WhatIf:$WhatIf
    } catch {
      Write-Host ("`t" + $_.Exception.Message)
    }
  }
}

Write-Host " This will remove all Azure Modules, but AzureRM will need to be uninstalled from Programs."
Read-Host "Are you ready to uninstall all Azure Components?"
$versions = (Get-InstalledModule -name *azure*| Select-Object Name,Version)
$versions[1..($versions.Length-1)]  | foreach { Uninstall-AllModules -TargetModule ($_.Name) -Version ($_.Version) -Force }


$a = Get-InstalledModule -name *profile*
If ($a) { 
        Remove-AzureRmAccount
        Uninstall-Module -Name $a.name
        }`

**Comment by JameZJ** [comment]
I modified this one slightly to remove the azure modules and the profile module if you happen to be logged in. I'll post the code on my git hub too.

[Uninstall-AllModules.zip](https://github.com/MicrosoftDocs/azure-docs-powershell/files/2856847/Uninstall-AllModules.zip)

**Comment by JameZJ** [comment]
I wrote my own code that I will post in github soon, but for now I recommend looking at this link. There are useful scripts in there. I ended up deleting a lingering AzureRM profile at C:\Program Files\WindowsPowerShell\Modules.

https://stackoverflow.com/questions/34204373/how-to-clean-up-bad-azure-powershell-uninstall

**Comment by AANunes** [comment]
Excellent JameZJ. Thank you for sharing. The foreach in that url did the job

**Comment by mhatreabhay** [comment]
most azureRM uninstall are throwing below warning 

Get-InstalledModule | %{ Uninstall-AllModules -TargetModule $_.Name -Version $_.Version -Force }

WARNING: Could not find uninstall candidate for AzureRM.Profile:4.3.2 - module may require manual uninstall
Uninstalling AzureRM.OperationalInsights version 4.3.2...

what should be manual steps ?

**Comment by skalpin** [comment]
I didn't have the cmdlet `Uninstall-AzureRM`. `Get-InstalledModules -Name AzureRM` did return a module version 5.7.0.

I used `Uninstall-Module -Name AzureRM` to remove it from powershell.

**Comment by sptramer** [comment]
The uninstall scripts have been updated to be clearer and have better handling for failure states. Closing this issue.
