### ISSUE TITLE
Command incorrect

### ISSUE THREAD

**Issue by devan10** [MicrosoftDocs/azure-docs-powershell#952]
In the example above I believe it should be "Set-AzContext $context" not "Az-SetContext $context"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c639e9-7a6a-aa3a-3f74-9a2753cb8947
* Version Independent ID: 98b7ac0d-e288-bb26-57b8-c173c46821d5
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/manage-subscriptions-azureps?view=azps-1.2.0)
* Content Source: [docs-conceptual/azps-1.2.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.2.0/manage-subscriptions-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This has been fixed in #950 and #961 thanks to community contributions.
