### ISSUE TITLE
Requires PowerShell 5.1, doesn't work with 5.0

### ISSUE THREAD

**Issue by batetech** [MicrosoftDocs/azure-docs-powershell#957]
The documentation states "Azure PowerShell works with PowerShell 5.x on Windows 7 or higher".  This is incorrect, and should say "Azure PowerShell works with PowerShell 5.1 or higher on Windows 7 or higher".

When installing using PowerShell 5.0, you get this error when trying to load the module: 
Import-Module : The version of Windows PowerShell on this computer is '5.0.10586.117'. The module 'C:\Program Files\WindowsPowerShell\Modules\Az\1.3.0\Az.psd1' requires a minimum Windows PowerShell version of '5.1' to run. Verify that you have the minimum required version of Windows PowerShell installed, and then try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7fc9d34-44cd-835e-ea61-179911a67ec4
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed.
