### ISSUE TITLE
Erro Sintaxe

### ISSUE THREAD

**Issue by unascimento** [MicrosoftDocs/azure-docs-powershell#963]
Boa Noite, não seria no local do:
Az-SetContext $context e sim: Set-AzContext $context ?
Pois se não apresenta o erro: Az-SetContext : O termo 'Az-SetContext' não é reconhecido como nome de cmdlet
Obrigado ! 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a13e8eda-7614-b68d-3746-bfaca5b70fde
* Version Independent ID: 98b7ac0d-e288-bb26-57b8-c173c46821d5
* Content: [Manage Azure subscriptions with Azure PowerShell](https://docs.microsoft.com/pt-br/powershell/azure/manage-subscriptions-azureps?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/manage-subscriptions-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/manage-subscriptions-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This issue has been fixed.
