### ISSUE TITLE
Persistence of users credentials across PowerShell sessions - information is inconsistent

### ISSUE THREAD

**Issue by brent-robinson** [MicrosoftDocs/azure-docs-powershell#968]
This document states:

> You'll need to repeat these steps for every new PowerShell session you start. To learn how to persist your Azure sign-in across PowerShell sessions, see Persist user credentials across PowerShell sessions.

The link in that paragraph links to documentation which states the opposite

> Azure PowerShell retains your context information automatically between sessions. 

Having just installed the module, signed in, and restarted PowerShell, I can confirm it automatically persists the context across PowerShell sessions (at least on Windows 10/PowerShell 5.1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7fc9d34-44cd-835e-ea61-179911a67ec4
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ArtemProc** [comment]
Agree context is saved even after session restart

**Comment by sptramer** [comment]
@brent-robinson The content for context persistence is tagged for an update starting sometime in April, so these issues will be addressed.

**Comment by sptramer** [comment]
The context documentation has finally been updated - thank you for your patience. Hopefully the new instructions are much clearer about what information is saved, how to control that information, and how the management of Azure context objects works.
