### ISSUE TITLE
Enabling aliases does not persist across PowerShell sesions

### ISSUE THREAD

**Issue by brent-robinson** [MicrosoftDocs/azure-docs-powershell#969]
`Enable-AzureRmAlias` only loads the aliases into the current PowerShell session. It does not enable them user/machine wide.

Can this document be updated to clarify this, and possibly suggest steps of adding it to the users PowerShell profile, and to the start of scripts which still leverage the AzureRm cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee44614-5f56-f5c3-b729-ed2fcbafcc35
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sdcscripts** [comment]
Hi, 

There is a scope parameter you can use to enable other scopes other than current user. 
[-Scope {Local | Process | CurrentUser | LocalMachine}]. 

Regards
Shaun

**Comment by brent-robinson** [comment]
Brilliant - thank you, that's much easier.

Looks like that inserts it into a PowerShell profile.  `Enable-AzureRmAlias -Scope CurrentUser` results in this being added to the users all hosts profile

```
#Begin Azure PowerShell alias import
Import-Module Az.Accounts -ErrorAction SilentlyContinue -ErrorVariable importError
if ($importerror.Count -eq 0) { 
    Enable-AzureRmAlias -Module Az.Accounts, Az.Aks, Az.AnalysisServices, Az.ApiManagement, Az.ApplicationInsights, Az.Automation, Az.Backup, Az.Batch, Az.Billing, Az.Cdn, Az.CognitiveServices, Az.Compute, Az.Compute.ManagedService, Az.ContainerInstance, Az.ContainerRegistry, Az.DataFactory, Az.DataLakeAnalytics, Az.DataLakeStore, Az.DataMigration, Az.DeviceProvisioningServices, Az.DevSpaces, Az.Dns, Az.EventGrid, Az.EventHub, Az.FrontDoor, Az.HDInsight, Az.IotCentral, Az.IotHub, Az.KeyVault, Az.LogicApp, Az.MachineLearning, Az.ManagedServiceIdentity, Az.ManagementPartner, Az.Maps, Az.MarketplaceOrdering, Az.Media, Az.Monitor, Az.Network, Az.NotificationHubs, Az.OperationalInsights, Az.PolicyInsights, Az.PowerBIEmbedded, Az.RecoveryServices, Az.RedisCache, Az.Relay, Az.Reservations, Az.ResourceGraph, Az.Resources, Az.Scheduler, Az.Search, Az.Security, Az.ServiceBus, Az.ServiceFabric, Az.SignalR, Az.Sql, Az.Storage, Az.StorageSync, Az.StreamAnalytics, Az.Subscription, Az.TrafficManager, Az.Websites -ErrorAction SilentlyContinue; 
}
#End Azure PowerShell alias import
```

Docs team, can the document suggest using the scope parameter for persisting this alias preference?

**Comment by sptramer** [comment]
@brent-robinson This must be a recent behavior change, since the last time I tested aliases, it defaulted to `-Scope CurrentUser` rather than `-Scope Process`. @markcowl please provide some information on the default scope used by this command, and if it has recently changed between versions.

**Comment by sptramer** [comment]
@markcowl Ping - please respond to this issue with information about the default scope for `Enable-AzureRmAlias`.

**Comment by sptramer** [comment]
@dcaro No response from engineering on this issue - do you have a contact for me right now, or can you provide some information on the behavior?
