### ISSUE TITLE
Get-Credentials

### ISSUE THREAD

**Issue by agallimore-gravity** [MicrosoftDocs/azure-docs-powershell#970]
How are we supposed to automate around a pop-up for credentials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e77e169-f3fa-2302-5081-ae742f4ba130
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/authenticate-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/authenticate-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@markcowl @sdwheeler Can you provide some advice on this? It seems like any correctly-formed `PSCredential` object will work, but I'm not sure if there's a canonical way to create one other than `Get-Credential`.

It would also be possible to create a service principal using certificate authentication, but this is a much more complicated process than user/pass authentication.

**Comment by sdwheeler** [comment]
There has been a lot written about how to use credentials securely in PowerShell scripts. Here are a couple of examples:
- https://devblogs.microsoft.com/powershell/want-to-secure-credentials-in-windows-powershell-desired-state-configuration/
- https://blog.kloud.com.au/2016/04/21/using-saved-credentials-securely-in-powershell-scripts/

The Service Principal method, cited by @sptramer, is probably the most scalable for Azure.

**Comment by sptramer** [comment]
Thanks @sdwheeler. @agallimore-gravity hopefully this will answer your question about automation but I'll take a note to update the article regarding the use of a `PSCredential` object stored locally, although there won't be a link to full instructions that Sean has posted, since they aren't part of an official Microsoft site.

**Comment by sptramer** [comment]
@markcowl Consider adding an example which doesn't use `Get-Credential` and instead creates a `PSCredential` object (populated with something). Correct and secure storage of local credentials is obviously outside the scope of reference examples, though.

**Comment by mikefrobbins** [comment]
Information for automating the login process has been added to the most recent versions of the referenced doc. See PR #1430
