### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/azure-docs-powershell#971]
requires 5.1 or higher, 5.0 does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee44614-5f56-f5c3-b729-ed2fcbafcc35
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.3.0)
* Content Source: [docs-conceptual/azps-1.3.0/new-azureps-module-az.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.3.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The version requirements were recently changed to be correct in the [Install Azure Powershell](https://docs.microsoft.com/powershell/azure/install-az-ps) documentation.
