### ISSUE TITLE
Install command doesnt work for me

### ISSUE THREAD

**Issue by AndyWDev** [MicrosoftDocs/azure-docs-powershell#976]
I just get the message: 
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Az'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1feffba-4aa0-5f48-96c7-74031ed897ca
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.4.0)
* Content Source: [docs-conceptual/azps-1.4.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.4.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ArtemProc** [comment]
Please check if you can resolve remote gallery with module
nslookup powershellgallery.com

**Comment by AndyWDev** [comment]
> Please check if you can resolve remote gallery with module
> nslookup powershellgallery.com
It worked when I used PowerShell v6.0  - I was previously using 5.1 (Windows 10).

**Comment by sptramer** [comment]
@AndyWDev This error normally indicates that you're behind a firewall or proxy that is restricting traffic to Azure PowerShell Gallery. PowerShell on Windows should be respecting your machine's firewall and proxy settings, but if this endpoint is blocked, then you won't be able to gain access.

Check with your network admin and try again, and please comment if this is an issue not related to a proxy.

**Comment by AndyWDev** [comment]
Hi thanks,
  As I posted above, it was just a version issue.  It didn't work with 5.1 but did with 6.0,
