### ISSUE TITLE
Get-AzureRmAutomationDscNode (Get-AzAutomationDSCNode) only supports top 20 results

### ISSUE THREAD

**Issue by LeoStack** [MicrosoftDocs/azure-docs-powershell#977]
So I am attempting to run a command similar to

Get-AzureRmAutomationAccount -ResourceGroupName <ResourceGroupName> | Get-AzureRmAutomationDscNode

However, the results only showed that you have 20 out of each automation account. Looking at the HTTP request is was as follows

https://management.azure.com/subscriptions/<SubID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.Automation/automationAccounts/<AutomationAccountName>/nodes?$top=20&$skip=0&api-version=2018-01-15

It has a built in limit of 20 nodes, with no obvious way to increase that limit. Can we have a parameter added to increase the limit above the default?

The version I am running:
Get-AzAutomationDscNode: 1.0.0 - Az.Automation

**Comment by sptramer** [comment]
Please file a bug report or feature request with engineering: https://github.com/azure/azure-powershell/issues
