### ISSUE TITLE
Typo in Get-AzRoleAssignment command

### ISSUE THREAD

**Issue by mhaarbrink** [MicrosoftDocs/azure-docs-powershell#982]
The example command to list the role assignments for a service principal has a typo.  The paramater "-ServicePrincipalName" is misspelled Prinicpal

Get-AzRoleAssignment -ServicePrinicpalName ServicePrincipalName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a900c4-851f-eee4-fbae-412c461c8b27
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.4.0)
* Content Source: [docs-conceptual/azps-1.4.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.4.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed.
