### ISSUE TITLE
Connect-ServiceFabricCluster does not return ClientConnectionEndpoint

### ISSUE THREAD

**Issue by mpotta** [MicrosoftDocs/azure-docs-powershell#984]
Connect-ServiceFabricCluster returns only the ManagementEndpoint, which cannot be used to securely connect to the cluster. What I'd need is the ClientConnectionEndpoint. Is there a reason it is not returned?

**Comment by sptramer** [comment]
Please file a bug with engineering: https://github,com/azure/azure-powershell/issues
