### ISSUE TITLE
Change AzureRmContext to AzContext 

### ISSUE THREAD

**Issue by brent-robinson** [MicrosoftDocs/azure-docs-powershell#986]
In the first code sample, the `AzureRmContext` alias is used for `DefaultProfile`. Given the scope of this document, the `AzContext` alias may be more appropriate and less confusing for users starting with `Az`.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526484cc-e510-3d7c-8590-8de9aba2b97a
* Version Independent ID: f1cd38f3-c594-ddc2-84d2-740b4f62857f
* Content: [Run cmdlets in parallel using PowerShell jobs](https://docs.microsoft.com/en-au/powershell/azure/using-psjobs?view=azps-1.4.0#feedback)
* Content Source: [docs-conceptual/azps-1.4.0/using-psjobs.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.4.0/using-psjobs.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed.
