### ISSUE TITLE
Dead link for New-AzADServicePrincipal.

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/azure-docs-powershell#989]
[This dead link](https://docs.microsoft.com/en-us/module/az.resources/get-azadserviceprincipal) is under this [header](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.4.0#get-an-existing-service-principal). 

404 not found for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a900c4-851f-eee4-fbae-412c461c8b27
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Use Azure service principals with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-1.4.0#get-an-existing-service-principal)
* Content Source: [docs-conceptual/azps-1.4.0/create-azure-service-principal-azureps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.4.0/create-azure-service-principal-azureps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Fixed.
