### ISSUE TITLE
Uninstall from Powershell cmd

### ISSUE THREAD

**Issue by colinweiner** [MicrosoftDocs/azure-docs-powershell#990]
PS command should be "Uninstall-Module -Name AzureRM", not "Uninstall-AzureRm".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96a60a63-cd45-8326-e0c9-d713cad6727a
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.4.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-1.4.0/uninstall-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.4.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The [Uninstall-AzureRm](https://docs.microsoft.com/en-us/powershell/module/az.accounts/uninstall-azurerm?view=azps-1.5.0) cmdlet is provided by `Az` for the explicit purpose of removing old AzureRM installs.
